### ISSUE TITLE
[zigpy-integration] - needs to get network info

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1004]
during the plugin execution, we need to get the current network info.

There is an api in zigpy-znp/application.py self.load_network_info() for that

Would be usefull to get it for zigpy-zigate

**Comment by badzz** [comment]
done
https://github.com/zigbeefordomoticz/zigpy-zigate/commit/0a425c0b33855ec9e0dc1e833e7bd8cabfb28097
