### ISSUE TITLE
[zigpy-integration] - dependecy requirements

### ISSUE THREAD

**Issue by Hedda** [sasu-drooz/Domoticz-Zigate#1007]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/blob/zigpy/requirements.txt

Not sure if it matters but should it not be hyphen instead of underscore in these PyPI module package names for pip install?

* "charset-normalizer" and not "charset_normalizer" as per https://pypi.org/project/pyserial-asyncio/ or?

* "async-timeout" and not "async_timeout" as per https://pypi.org/project/pyserial-asyncio/ or?

* "pyserial-asyncio" and not "pyserial_asyncio" as per https://pypi.org/project/pyserial-asyncio/ or?

* "typing-extensions" and not "typing_extensions" as per https://pypi.org/project/pyserial-asyncio/ or?

**Comment by pipiche38** [comment]
fixed
