### ISSUE TITLE
[zigpy-integration] - zigpy will require Python version 3.7 and soon maybe even require at least 3.8

### ISSUE THREAD

**Issue by Hedda** [sasu-drooz/Domoticz-Zigate#1008]
FYI, see zigpy developers discussion about dropping support for python-version 3.6 and 3.7 (3.7.7):

https://github.com/zigpy/zigpy/pull/861

https://github.com/zigpy/zigpy/pull/861/commits/37671f8c857c987d42ad50387fbe9a5ca44d61d0

As I understand their strategy is drop python-version 3.6 support now and also plan to drop 3.7 soon.

https://github.com/zigpy/zigpy/blob/dev/.github/workflows/ci.yml

When the Domoticz Zigbee Plugin for Domoticz add zigpy it might be a good idea to require Python 3.8 or even Python 3.9?

Noticed that the plugin currently only requires Python version 3.5 according to zigbeefordomoticz wiki here:

https://github.com/zigbeefordomoticz/wiki/blob/zigpy/en-eng/Plugin_Installation.md

https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/Plugin_Installation.md

> _In every installation methodes, the plugin requires Domoticz version 3.87xx or greater and Python version 3.5 or higher.
Make sure that you have __python3-dev package__ installed. More informations on [Domoticz Python page](https://www.domoticz.com/wiki/Using_Python_plugins)._

PS: One of the reasons for this is that Home Assistant 2022.02 which is to be released in February of 2022 will drop support for Python 3.8 (Python 3.8 was previously listed as deprecated in Home Assistant and support for it will now be dropped completely).

**Comment by pipiche38** [comment]
thanks for the information. 
From a domoticz standpoint and the plugin we don't have any requirements on that matters. We just try to be conservative and keep on friends running on old platform happy.

**Comment by pipiche38** [comment]
Noted and documented in the Readme section.
