### ISSUE TITLE
Some commands are not executed

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#102]
IOn my setup I have about 9 shutters. I'm managing them via lua script , and sometimes it happens that I have Open command sent to the 9 devices. Time to time, it happens that not all of them are executed.

When looking at the log, the Zigate command is correctly received see here after, but not executed !
In my LUA script, I have started to use RANDOM in order to have the command delayed in a randomized way (accross 3 to 5 minutes) and then I have a much better behaviour.

Any one experiencing the same ? Not sure it is a Zigate plugin, but maybe more a Zigate HW issue ?

This is also why I think it is important to implement the onHeart function for getting position and on/off of the shutters!

```

Jul 25 12:00:04 pi3 domoticz[749]: 2018-07-25 12:00:04.710  (Zigate) onCommand called for Unit 3: Parameter 'Set Level', Level: 15
Jul 25 12:00:04 pi3 domoticz[749]: 2018-07-25 12:00:04.753  (Zigate) Update 1:'15' (Volet Chambre Parents)
```

**Comment by thiklop** [comment]
J'ai un problème similaire mais avec des volets somfy et un RFXCom. J'utilise du blocky mais les délais ne fonctionnent pas. C'est peut-être plus un problème Domoticz.

**Comment by pipiche38** [comment]
Fix by serialisation in the sendZigateCmd() function
798edefd0eaccbf15923703c3bfff5a6e2834168
