### ISSUE TITLE
Get Zigbee data out of domoticz

### ISSUE THREAD

**Issue by usky73** [sasu-drooz/Domoticz-Zigate#1024]
Hi all
First of all just conect my zigate to domoticz, and I want to thanks all the people that works on this plugin and doc. It was easy to install and the interface is really professionnal.

I have only one thing I would like to adress and I did not find how to do.
I want to maage my energy data outside of domoticz. I have made my own system based on a Mysql database.
Is there a way to record my Zigbee sensor to this database using this plugin ?

Thanks 

Laurent

**Comment by pipiche38** [comment]
This is more a Domoticz question than a Zigbee for Domoticz plugin one. I suggest that you use the https://www.domoticz.com/forum/ for that

**Comment by pipiche38** [comment]
Here is an example of pushing data to outside
https://github.com/tvwerkhoven/domoticz2influxdb/blob/master/smartmeterpusher.lua
Mainly the idea is to use a script (lua, dzVents would be better) to push the incoming data to whatever you want and in your case to the mysql DB.
I'm sure that you can find support on Domoticz forum as well.

Closing the Issue

**Comment by usky73** [comment]
thx for your help, I will have a look on this.
