### ISSUE TITLE
[zigpy-integration] - how to use the zigpy OTA services instead of the plugin OTA

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1026]
The idea is to investigate if there is a way to make the plugin using directly the zigpy OTA service instead of going through the plugin one

**Comment by Hedda** [comment]
FYI, for back-story and reference, you might be interested in reading through these previous related development discussions: 

https://github.com/zigpy/zigpy/pull/849

https://github.com/zigpy/zigpy/issues/535

https://github.com/zigpy/zigpy/issues/154

https://github.com/zigpy/zigpy/discussions/654

https://github.com/zigpy/zigpy/discussions/721

https://github.com/zigpy/zigpy/discussions/951

https://github.com/zigpy/zigpy/discussions/660

https://github.com/zigpy/zigpy/discussions/723

Also check out the little related zigpy and ZHA projects documentation and user information about how to use OTA updates:

https://github.com/zigpy/zigpy/wiki/OTA-Device-Firmware-Updates

https://www.home-assistant.io/integrations/zha#ota-firmware-updates

https://github.com/zigpy/zigpy/blob/dev/README.md#zigbee-device-ota-updates

**Comment by pipiche38** [comment]
Might start from here
https://github.com/zigpy/zigpy-cli/tree/dev/zigpy_cli

**Comment by pipiche38** [comment]
I think this is not really possible, as for now the zigpy integration is at the low level and if we want to have OTA, we will need to integrate ZCL level in order to manage the OTA cluster, which is not the current strategy.

Closing for now
