### ISSUE TITLE
[Zigpy-integration] - Leave during ZNP pairing process

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1030]
This is happening every time with the PIR323 Multi-sensor.
The Pairing process start and then during the process the device send a Leave.

From the sniffer, I have observed that there is a Request Key happening after the process has started and the leave is happening just after the Verify Key

Attached is 2 Sniffs, and the plugin log of the latest sniff
[Archive.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/7944161/Archive.zip)
[Pairing-Leave.txt.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/7944167/Pairing-Leave.txt.zip)

**Comment by pipiche38** [comment]
https://github.com/zigpy/zigpy/discussions/865#discussioncomment-2053334

**Comment by puddly** [comment]
Let's continue this discussion here (and in the future, `@` me in an issue on this repo). The GitHub discussions page for https://github.com/zigpy/zigpy/discussions/865 is already so full of comments that most are getting hidden...

**Comment by pipiche38** [comment]
@puddly for now I gave up on that issue, because I didn't see any pattern. Basically only few time I have been to go through a stable pairing, meanings that the discovery was done, the IAS enrollment completed and the sensor behaving correctly. But in most of the time, it was just failing with a leave message.

So right now, I don't really now how to tackle it. If you have any idea, this would be very welcome

**Comment by pipiche38** [comment]
Here are 2 captures on a zzh key.

One with a full successfull pairing/discovery
One with a leave during the pairing/discovery

[Wireshark capture.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/8008557/Wireshark.capture.zip)

**Comment by puddly** [comment]
Do you mean that it doesn't leave 100% of the time when using the ZZH?

**Comment by pipiche38** [comment]
Yes, exactly.

So Zigate native 100% of cases correctly paired and discovered fully functional
Zigate with zigpy 100% of cases correctly paired and discovered fully functional
ZNP (zzh or SonOff) most of the time leave during the pairing process, I would Once over 10 times success

[edited] The leave is happening in randow way during the pairing process. Some time there is no Leave, but the device doesn't respond and all request failed. However I see some Data Request (from the device)

**Comment by pipiche38** [comment]
for now PIR323 is not supported on zigpy-znp
