### ISSUE TITLE
[zigpy-integration] - bellows/cli/ncp fails

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1079]
```
 python3 -m bellows.cli.ncp.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/bellows/cli/__init__.py", line 2, in <module>
    from . import application, backup, dump, ncp, network
  File "/home/domoticz/domoticz/plugins/Domoticz-Zigbee/bellows/cli/dump.py", line 6, in <module>
    import pure_pcapy
  File "/usr/local/lib/python3.9/dist-packages/pure_pcapy/__init__.py", line 88
    except Exception, error:
                    ^
SyntaxError: invalid syntax
```
CC: @puddly

**Comment by pipiche38** [comment]
this looks to be valid for all cli/program like networks.py ....

**Comment by puddly** [comment]
This was fixed in *2010*: https://github.com/rcloran/pure-pcapy-3/commit/04d434f2234c36bdfb11778055292240df5d3446

Are you manually installing dependencies? There's no need to do this. Any of the following work correctly and properly resolve all dependencies:

 - `pip install bellows`
 - `pip install git+https://github.com/puddly/bellows.git@puddly/zigpy-radio-api`
 - `git clone your-repo && pip install -e ./your-repo`

Also, the bellows CLI shouldn't be called as a module. Its entry point is the `bellows` script:

```console
$ bellows -v DEBUG -d ... dump -c 15 -w capture.pcap
```

**Comment by pipiche38** [comment]
We are not installing bellows with pip.

```
 sudo pip3 install pure-pcapy
 /usr/lib/python3/dist-packages (from pure-pcapy) (52.0.0)
```

**Comment by puddly** [comment]
Why not? Bellows has [specific dependencies](https://github.com/zigpy/bellows/blob/b5ed295b350de394e5c65c1e6d638d3348e4cb86/setup.py#L18-L25), you can't just `pip install` the dependency name and expect it to work.

**Comment by pipiche38** [comment]
Ok. so dependencies has been installed , but indeed the application doesn't work.
Shame as on ZNP it does work

**Comment by puddly** [comment]
"Doesn't work" isn't very helpful. What doesn't work?

**Comment by pipiche38** [comment]
You're right, just confirming your comment that pip install the dependency is not enought!

```
domoticz@pi4:~/domoticz/plugins/Domoticz-Zigbee $ sudo python3 -m bellows.cli.main -d /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0 dump
/usr/lib/python3.9/runpy.py:127: RuntimeWarning: 'bellows.cli.main' found in sys.modules after import of package 'bellows.cli', but prior to execution of 'bellows.cli.main'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Usage: python -m bellows.cli.main [OPTIONS] COMMAND [ARGS]...
Try 'python -m bellows.cli.main --help' for help.

Error: No such command 'dump'.
```
