### ISSUE TITLE
[Update] Readme

### ISSUE THREAD

**Issue by jp-keros** [sasu-drooz/Domoticz-Zigate#1094]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/blob/stable5/readme.md

- [x] Remove ZiGate words
- [x] Add info about coordinators
- [x] Update Wiki links
- [ ] Change (or remove ?) Codefactor link

**Comment by jp-keros** [comment]
You can assigned it to me ;-)

**Comment by pipiche38** [comment]
But you should update ONLY the Readme file of the beta6 branch

**Comment by jp-keros** [comment]
I think about that during the night because I certainly loot at the default branch (stable5).
I appologize.

**Comment by jp-keros** [comment]
[Modifications pushed ](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/pull/1115)

**Comment by pipiche38** [comment]
will follow on #1114
