### ISSUE TITLE
[Stable6] To Do List

### ISSUE THREAD

**Issue by jp-keros** [sasu-drooz/Domoticz-Zigate#1114]
Liste des choses à faire pour la sortie de la stable6 :

- [x] Mettre à jour les liens du webUI vers le wikiUI
     - [x] Modifier les traductions > @jp-keros
     - [x] Pousser la modif des traductions > @jp-keros
     - [x] Mettre à jour le plugin > @pipiche38

- [x] Mettre le WikiUI en ligne
     - [x] Merge de la branche Github-page dans Zigpy > @jp-keros 
     - [x] Merge de la branche ZigPy dans Master > @jp-keros ou @pipiche38 
     - [x] Modifier le paramètre de la GitHub-page pour qu'elle pointe sur la branche master > @pipiche38 

- [x] Mettre le WikiUI à jour
     - [x] Enlever l'indication de basculer sur la beta6 (fin de la phase développement) > @jp-keros 
     - [x] Modifier les pages versions 6 pour pointer vers la branche master et non zigpy > @jp-keros 

- [x] Créer la stable6 > @pipiche38 

- [x] Faire la communication
     - [x] Sur Keybase > @pipiche38 
     - [x] Sur le forum Anglais > @pipiche38 
     - [x] Sur le forum Français > @pipiche38 

- [x] Prévenir nos partenaires (mettre un message dans les sujets de discussions ouverts)
     - [x] zigpy
     - [x] electrolama
     - [x] elelabs
     - [x] Bellows

- [x] Mettre à jour les liens vers le wiki
     - [x] Readme du plugin : https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/1094
     - [x] Signature forum EN @pipiche38 
     - [x] Signature forum FR @pipiche38 
     - [x] Présentation forum FR > @jp-keros
     - [x] Pages Wiki Domoticz.com > @pipiche38 

Les nouveaux liens pour le wiki sont :

https://zigbeefordomoticz.github.io/wiki
https://zigbeefordomoticz.github.io/wiki/en-eng
https://zigbeefordomoticz.github.io/wiki/fr-fr

Pour mémoire, les pages de sommaire Home.md sont remplacées par les pages Readme.md. 
Un lien est mis dans les anciennes pages Home.md pour renvoyer les visiteurs sur le wikiUI.

À compléter, modifier et cocher ;-)

**Comment by jp-keros** [comment]
Les points à communiquer :

- Prise en charge des Coordinateurs TI
- Procédure particulière pour le passage en V6
- Modification des liens vers le wiki avec un affichage sous forme de site web
- Possibilité d'intégrer le WebUI directement dans DomoticZ via le custom menu (voir étape 4 de la procédure d'installation)
- Mise en place de statistiques sur l'utilisation du plugin.
- Future ouverture aux coordinateurs bellows et conbee

**Comment by pipiche38** [comment]
la création de stable6 se ferra au dernier moment, car sinon, on risque d'avoir du monde qui bascule dessus

**Comment by pipiche38** [comment]
@hedda, @puddly for your information we are in the final lap to make the first release of the plugin including zigpy layers and mainly the zigpy-znp and bellows radio libraries.

Up to now it was on beta, and now we consider ready for stable version. this will be pushed during the week-end and announced on the different Domoticz forum.

For that release we will rely on the legacy radio api

thanks a lot for your support and looking forward to continue our working relationship

**Comment by Hedda** [comment]
Nice! Like to suggest writing on GitHub and wikis in English first as primary published language and then translate to French after.

By writing in French first as primary and only later translating to English you risk alienating/excluding new non-French users/devs.

Most other projects are only documented in English and use only in English in forums even if devs are not native English speakers.

**Comment by jp-keros** [comment]
That is all my fault.

Considering this issue, it is written in French because I needed somewhere to write quick notes.

Considering the wiki, at the end of 2020, Pipiche asked for a translation of the wiki in French. I did it and I also improved it. I was able to think about formatting because I was thinking in French. I could not have done the same work in English directly. 

But if you look at the solved point of the wiki https://github.com/zigbeefordomoticz/wiki/issues?q=is%3Aissue+is%3Aclosed, the English element are done at the same moments and there are all checked.

I know, all the wiki issues are written in French. I consider them as quick notes for me, so I wrote them in French.

Pipiche asked me several times if can do it in English first : I can not, sorry.

**Comment by pipiche38** [comment]
I did update the PP-Manager to use stable6 branch instead of stable5

**Comment by pipiche38** [comment]
j'ai updaté egalement le Wiki Domoticz avec les nouveaux liens.

**Comment by jp-keros** [comment]
Every thing is checked, this issue may now be closed  ;-)

Thanks for the work done
