### ISSUE TITLE
Unable to remove broken devices

### ISSUE THREAD

**Issue by tomm1ed** [sasu-drooz/Domoticz-Zigate#1205]
I had an Aqara temperature sensor die on me and I seem unable to remove it from the Zigate. Deleting the device from Domoticz left it in provREQ Status (unclear what that means exactly)
[https://tweakers.net/fotoalbum/image/lwwByUnMh2Sds6gewTA9Sev2.png](url)
Can anyone tell me how to fix this?

**Comment by tomm1ed** [comment]
I also tried removing three Aqara Motion Sensors (which I am no longer using) and even though I receive this in the log:
2022-06-03 10:40:00,155 INFO    : [       MainThread] onDeviceRemoved - removing End Device
2022-06-03 10:40:00,170 INFO    : [       MainThread] onDeviceRemoved - removing End Device
2022-06-03 10:40:00,177 INFO    : [       MainThread] onDeviceRemoved - removing End Device
The devices themselves do not get removed from the Zigate

Is there any way to remove these manually @pipiche38 ? I have a ZiGate Classic with WiFi

**Comment by pipiche38** [comment]
The best is now, to restart the plugin , all entries will be removed, and then while making sure the Zigate is not in pairing mode, you simply reset the Aqara temperature device. In that case it will send a leave message and get removed from the Zigate.

In all cases, you cannot do more as , only the device itself can me removed from the coordinator

**Comment by pipiche38** [comment]
https://github.com/zigbeefordomoticz/wiki/blob/master/en-eng/HowTo_Remove-device.md
