### ISSUE TITLE
Mode appareillage après reboot

### ISSUE THREAD

**Issue by Hydci** [sasu-drooz/Domoticz-Zigate#1279]
Bonjour,

A chaque reboot de domoticz la clé zzh CC2652R ce remet en mode appareillage j'ai regarder dans l'interface du plugin si quelque chose ma échapper mais ça ma pas l'air je signale donc ce problème et si besoin je peu transmettre les infos que tu as besoin

**Comment by pipiche38** [comment]
merci d'utiliser le forum pour ce type de question, ou le channel adequat keybase.io
