### ISSUE TITLE
Tuya TS0601 smoke detector support

### ISSUE THREAD

**Issue by Achterhoeker** [sasu-drooz/Domoticz-Zigate#1295]
I've tried to pair a tuya smoke detector. It seems not supported correctly, it is recognized as:

* zigbee - TS0601_Temp-a4c138740d8646ce-01
* zigbee - TS0601_ThermoSetpoint-a4c138740d8646ce-01
* zigbee - TS0601_ThermoMode_2-a4c138740d8646ce-01 

I would expect a smoke detector.

Log if i try to re-pair it again: 
2022-09-30 11:39:21.532  Status: zigbee: [None] NEW OBJECT: fc33 None
2022-09-30 11:39:24.168  Status: zigbee: [-] NEW OBJECT: fc33 Active Endpoint Response Ep: 01 LQI: 167
2022-09-30 11:39:24.172  Status: zigbee: [-] NEW OBJECT: fc33 Request Simple Descriptor for Ep: 01
2022-09-30 11:39:25.611  Status: zigbee: [-] NEW OBJECT: fc33 Simple Descriptor Response EP: 0x01 LQI: 163
2022-09-30 11:39:25.612  Status: zigbee: [-]    NEW OBJECT: fc33 ProfileID 0104
2022-09-30 11:39:25.613  Status: zigbee: [-]    NEW OBJECT: fc33 ZDeviceID 0051
2022-09-30 11:39:25.613  Status: zigbee: [-]    NEW OBJECT: fc33 Application Version 0001
2022-09-30 11:39:25.614  Status: zigbee: [-]    NEW OBJECT: fc33 Cluster IN Count: 04
2022-09-30 11:39:25.615  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster In 1: 0004 (Groups)
2022-09-30 11:39:25.616  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster In 2: 0005 (Scenes)
2022-09-30 11:39:25.617  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster In 3: ef00
2022-09-30 11:39:25.617  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster In 4: 0000 (Basic)
2022-09-30 11:39:25.618  Status: zigbee: [-]    NEW OBJECT: fc33 Cluster OUT Count: 02
2022-09-30 11:39:25.619  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster Out 1: 0019 (Over-the-Air Upgrade)
2022-09-30 11:39:25.620  Status: zigbee: [-]       NEW OBJECT: fc33 Cluster Out 2: 000a (Time)
2022-09-30 11:39:27.118  Status: zigbee: [1] NEW OBJECT: fc33 Model Name: TS0601
2022-09-30 11:39:27.125  Status: zigbee: [1] NEW OBJECT: fc33 Manufacturer Name: _TZE200_ntcy3xu1
2022-09-30 11:39:27.126  Status: zigbee: [None] NEW OBJECT: fc33 Request Node Descriptor

Last device in raw device list:
[export.json.log](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/9683122/export.json.log)

https://nl.aliexpress.com/item/1005004533181972.html

Thanks for your help,
Ronald.

**Comment by pipiche38** [comment]
could you kindly:

1- remove the object from Domoticz and plugin Db by removing all Domoticz widget associated to this Smoke sensor
2- switch to beta6 branch of the plugin. In case you are on Stable6 version, please follow this https://github.com/zigbeefordomoticz/Domoticz-Zigbee/blob/beta6/VERSION-6.3.md#pre-requisities as there is a configuration update that you have to do in Domoticz for the plugin
3- restart Domoticz 
4- redo the pairing

And let me know. In all cases I would be interested to have the export.json after pairing and after few tests.

[edit] in case you are already on beta6, just do a` git pull t`o get the latest one

**Comment by pipiche38** [comment]
@Achterhoeker have you been able to test ?

**Comment by Achterhoeker** [comment]
@pipiche38  Sorry, I was not able yet to test the beta plugin. I hope that I have some time this evening.

**Comment by Achterhoeker** [comment]
@pipiche38 Great work, i think i have a working smoke detector now :-)

The log from the pairing:

> 2022-10-03 21:20:11.126  zigbee: Enable Assisted pairing
> 2022-10-03 21:20:11.131  Status: zigbee: Request Accepting new Hardware for 240 seconds
> 2022-10-03 21:20:11.180  zigbee: Assisted Pairing: Polling: []
> 2022-10-03 21:20:11.180  zigbee: --> Empty queue
> 2022-10-03 21:20:11.197  Status: zigbee: Accepting new Hardware: Enable (On)
> 2022-10-03 21:20:21.187  zigbee: Assisted Pairing: Polling: []
> 2022-10-03 21:20:21.187  zigbee: --> Empty queue
> 2022-10-03 21:20:28.447  Status: zigbee: [None] NEW OBJECT: 752c None
> 2022-10-03 21:20:28.750  Status: zigbee: [-] NEW OBJECT: 752c Active Endpoint Response Ep: 01 LQI: 0
> 2022-10-03 21:20:28.754  Status: zigbee: [-] NEW OBJECT: 752c Request Simple Descriptor for Ep: 01
> 2022-10-03 21:20:29.817  Status: zigbee: [-] NEW OBJECT: 752c Simple Descriptor Response EP: 0x01 LQI: 200
> 2022-10-03 21:20:29.817  Status: zigbee: [-]    NEW OBJECT: 752c ProfileID 0104
> 2022-10-03 21:20:29.818  Status: zigbee: [-]    NEW OBJECT: 752c ZDeviceID 0051
> 2022-10-03 21:20:29.819  Status: zigbee: [-]    NEW OBJECT: 752c Application Version 0001
> 2022-10-03 21:20:29.820  Status: zigbee: [-]    NEW OBJECT: 752c Cluster IN Count: 04
> 2022-10-03 21:20:29.821  Status: zigbee: [-]       NEW OBJECT: 752c Cluster In 1: 0004 (Groups)
> 2022-10-03 21:20:29.821  Status: zigbee: [-]       NEW OBJECT: 752c Cluster In 2: 0005 (Scenes)
> 2022-10-03 21:20:29.822  Status: zigbee: [-]       NEW OBJECT: 752c Cluster In 3: ef00
> 2022-10-03 21:20:29.823  Status: zigbee: [-]       NEW OBJECT: 752c Cluster In 4: 0000 (Basic)
> 2022-10-03 21:20:29.824  Status: zigbee: [-]    NEW OBJECT: 752c Cluster OUT Count: 02
> 2022-10-03 21:20:29.825  Status: zigbee: [-]       NEW OBJECT: 752c Cluster Out 1: 0019 (Over-the-Air Upgrade)
> 2022-10-03 21:20:29.826  Status: zigbee: [-]       NEW OBJECT: 752c Cluster Out 2: 000a (Time)
> 2022-10-03 21:20:30.089  Status: zigbee: [0] NEW OBJECT: 752c Model Name: TS0601-smoke
> 2022-10-03 21:20:30.096  Status: zigbee: [0] NEW OBJECT: 752c Manufacturer Name: _TZE200_ntcy3xu1
> 2022-10-03 21:20:30.102  Status: zigbee: [None] NEW OBJECT: 752c Request Node Descriptor
> 2022-10-03 21:20:31.166  zigbee: Assisted Pairing: Polling: ['752c']
> 2022-10-03 21:20:31.166  zigbee: --> New device: 752c
> 2022-10-03 21:20:31.166  zigbee: --> inDB , removed 752c from List
> 2022-10-03 21:20:31.167  zigbee: ------> New Cluster: {'ClusterId': '0000', 'ClusterDesc': 'Basic'}
> 2022-10-03 21:20:31.167  zigbee: ------> New Cluster: {'ClusterId': '0004', 'ClusterDesc': 'Groups'}
> 2022-10-03 21:20:31.167  zigbee: ------> New Cluster: {'ClusterId': '0005', 'ClusterDesc': 'Scenes'}
> 2022-10-03 21:20:31.167  zigbee: ------> New Cluster: {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}
> 2022-10-03 21:20:31.168  zigbee: ------> New Cluster: {'ClusterId': '000a', 'ClusterDesc': 'Time'}
> 2022-10-03 21:20:31.168  zigbee: ------> New Cluster: {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}
> 2022-10-03 21:20:31.168  zigbee: ----> New Ep: {'Ep': '01', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0004', 'ClusterDesc': 'Groups'}, {'ClusterId': '0005', 'ClusterDesc': 'Scenes'}, {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}, {'ClusterId': '000a', 'ClusterDesc': 'Time'}, {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}]}
> 2022-10-03 21:20:31.168  zigbee:  --> New Device: {'NwkId': '752c', 'ProvisionStatus': 'inDB', 'ProvisionStatusDesc': 'inDB', 'IEEE': 'a4c138740d8646ce', 'ProfileId': '0104', 'ProfileIdDesc': 'ZHA', 'ZDeviceID': '0051', 'ZDeviceIDDesc': 'Unknow', 'Model': 'TS0601-smoke', 'PluginCertified': 'yes', 'Ep': [{'Ep': '01', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0004', 'ClusterDesc': 'Groups'}, {'ClusterId': '0005', 'ClusterDesc': 'Scenes'}, {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}, {'ClusterId': '000a', 'ClusterDesc': 'Time'}, {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}]}]}
> 2022-10-03 21:20:41.191  zigbee: Assisted Pairing: Polling: []
> 2022-10-03 21:20:41.194  zigbee: --> Empty queue
> 2022-10-03 21:20:45.113  zigbee: Disable Assisted pairing
> 2022-10-03 21:20:45.119  Status: zigbee: Request Disabling Accepting new Hardware
> 2022-10-03 21:20:45.193  Status: zigbee: Accepting new Hardware: Disable (Off)

Raw devices .json list:

[export (1).zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/9700319/export.1.zip)

**Comment by pipiche38** [comment]
Happy man.

Could you kindly let me know which one is it ?
https://zigbee.blakadder.com/Tuya_SA12IZL.html
https://zigbee.blakadder.com/Tuya_YG400A.html
https://zigbee.blakadder.com/Tuya_Qaynn.html
https://zigbee.blakadder.com/Woox_R7049.html
https://zigbee.blakadder.com/Smart9_S9ZB-SA02.html

So I can add the plugin to that list .

Thanks in advance

**Comment by Achterhoeker** [comment]
@pipiche38 It is this one: https://zigbee.blakadder.com/Tuya_YG400A.html

But i dont see a battery level.  Is this correct ?

**Comment by pipiche38** [comment]
Which version of Domoticz are you running ? Are you on 2022.1 or above , or on 2021 ?
In any case, update to the beta6 of today, I just push fix which should make the battery working for all Domoticz version, but you'll need to wait for an update from the device (like a status telling no smoke detected )

**Comment by Achterhoeker** [comment]
I've updated to the latest version, i see now correctly a battery status 90% 

Thanks for all you work.

**Comment by pipiche38** [comment]
I guess we can close the Issue then.
Thanks for your time and sharing the data
