### ISSUE TITLE
Check new Domoticz Blind behaviour

### ISSUE THREAD

**Issue by pitchoun38** [sasu-drooz/Domoticz-Zigate#1310]
Check that plugin blinds usage follow the new Domoticz Blinds behaviours
https://domoticz.com/wiki/Blinds

**Comment by pipiche38** [comment]
https://easydomoticz.com/forum/viewtopic.php?f=28&t=12673

**Comment by pipiche38** [comment]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/commit/cbfbf8032b424a032dc6331a5826e08ef195438f

**Comment by pipiche38** [comment]
For now, it looks like the widget created by the plugin are created as a simple switch !!!

**Comment by pipiche38** [comment]
Creation of BlindInverted doesn't work, and so create a Light widget
