### ISSUE TITLE
ZNP / CCxxxx - unable to send command/message to a Battery based end device operating with polling

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#1341]
When sending message/command to a end device which is doing polling time to time, commands are most of the time failing to be sent.

The typical example is with a Wiser VACT which is doing polling during 5 seconds after sending a report. When sending the command at that time most of the time it is failing. ZNP is doing several retries but all fails.

I understood that @Koenkk firmware are based on a ACK_APS of 1 second (instead of the 6 seconds default). That could be a reason, but I think ZNP is also doing some timeout at the same time.

__When doing the same setup with an elelabs or SonOff E dongle based on Silicon Labs, all work like a charm__

![Screenshot 2022-11-08 at 16 28 27](https://user-images.githubusercontent.com/8291674/200606788-2dd5bca9-f46a-4f1f-bb0b-509dc223d7b5.png)
![Screenshot 2022-11-08 at 16 28 55](https://user-images.githubusercontent.com/8291674/200606802-9da06f8d-0a91-441b-9dde-bdc3c354a63b.png)

**Comment by pipiche38** [comment]
@badzz @deufo if you want to investigate, but for me something is weird 
@puddly if you have any ideas to investigate let me know

**Comment by pipiche38** [comment]
In the here attached Sniff you'll get 

- up to packet 9967 a communication between zzh and wiser vact
- from backet 9967 a communication between elelabs and wiser vact
- 
In short the boths coordinators behaviours are visible on the same sniff


[Problem ZNP VACT.pcapng.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/9962700/Problem.ZNP.VACT.pcapng.zip)

**Comment by MattWestb** [comment]
The reactivating the disabled Zigbee 3 end device handling shall being OK now but they is have some other problems and in the  IT firmware.
Also you is very likely getting problem with normal and source routing with them then its broadcast storming the network then they still have illegal broadcast settings in the firmware and then the routers if being flooded they is blocking broadcast and the routing discovery is not working longer.
