### ISSUE TITLE
[Model Certification] - Livarno Lux LED Strip 22W 2m - Model HG06104A 

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#1361]
1. Please do provide device information such as Brand and Model name.
Livarno Lux LED Strip 22W 2m - Model HG06104A 

2. Provide the URL where you have purchase the device
lidl.fr

3. Finaly copy-paste all information provided in the log

24:
Version: "3"
ZDeviceName: "Led Lit Oscar"
Status: "inDB"
SQN: "1e"
Heartbeat: "51"
RIA: "0"
LQI: 112
Battery:
Model: "TS0505A"
ForceAckCommands:
MacCapa: "8e"
IEEE: "5c0272fffe1c8fea"
Type: "ColorControlRGBWW"
ProfileID: "0104"
ZDeviceID: "010d"
App Version: "80"
Attributes List:
DeviceType: "FFD"
HW Version: "1"
Last Cmds:
LogicalType: "Router"
Manufacturer: "1002"
Manufacturer Name: "_TZ3000_riwp3k79"
NbEp: "2"
PowerSource: "Main"
ReadAttributes:
Ep:
01:
0000:
TimeStamp: "01/12/2022 14:11:40"
iSQN:
0000: "0b"
0001: "0b"
0002: "0b"
0003: "0c"
0004: "0c"
0005: "0c"
0006: "0d"
0007: "0d"
Attributes:
0000: "00"
0001: "00"
0002: "00"
0003: "00"
0004: "00"
0005: "00"
0006: "00"
0007: "00"
ZigateRequest:
0019:
TimeStamp: "01/12/2022 14:11:36"
iSQN:
0001: "03"
0002: "03"
0003: "03"
0004: "04"
0005: "04"
0006: "04"
0007: "05"
0008: "05"
0009: "05"
000a: "06"
Attributes:
0001: "86"
0002: "86"
0004: "86"
0005: "86"
0007: "86"
0008: "86"
000a: "86"
ZigateRequest:
0006:
TimeStamp: "01/12/2022 14:26:11"
iSQN: Object {"0000":"3d"}
Attributes: Object {"0000":"00"}
ZigateRequest: Object {}
0008: Object {"TimeStamp":"01/12/2022 14:26:24","iSQN":{"0000":"3e"},"Attributes":{"0000":"00"},"ZigateRequest":{}}
0300: Object {"TimeStamp":"01/12/2022 14:11:38","iSQN":{"0000":"09","0001":"09","0003":"09","0004":"0a","0007":"0a","0008":"0a"},"Attributes":{"0000":"00","0001":"00","0003":"00","0004":"00","0007":"00","0008":"00"},"ZigateRequest":{}}
f2: Object {"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}
ReceiveOnIdle: ""
Stack Version: "0"
Stamp: Object {"time":1669901184.024358,"Time":"2022-12-01 14:26:24","MsgType":"8102","LastSeen":"01/12/2022 14:26:24"}
ZCL Version: "3"
Health: "Live"
Capability: Array[5] ["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"]
ZDPSQN: "07"
Epv2: Object {"01":{"ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"0300":{}},"ClusterOut":{"0019":{},"000a":{}},"ProfileID":"0104","ZDeviceID":"010d"},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}}
ZCLSQN: "3e"
RollingLQI: Array[11] [102,102,87,83,112,112,112,112,112,112,112]
ConfigSource: "DeviceConf"
Ep: Object {"01":{"1000":{},"0000":{"0004":"_TZ3000_riwp3k79","0005":"TS0505A","0000":"3","0001":"80","0002":"0","0003":"1","0006":"","0007":"1"},"0003":{},"0004":{},"0005":{},"0006":{"0000":"00"},"0008":{"0000":"ff"},"0300":{"0000":"0","0001":"254","0003":"45874","0004":"19660","0007":"153","0008":"2"},"000a":{},"0019":{},"Type":"ColorControlRGBWW","ClusterType":{"26594":"ColorControlRGBWW"}},"f2":{"0021":{},"Type":""}}
ZDeviceVersion: "0001"
PairingInProgress: false
PairingTime: 1669900292.08147
Bind: Object {"01":{"0006":{"Target":"0000","Stamp":"01/12/2022 14:11:32","Phase":"binded","Status":"00","i_sqn":"03"},"0008":{"Target":"0000","Stamp":"01/12/2022 14:11:33","Phase":"binded","Status":"00","i_sqn":"04"},"0300":{"Target":"0000","Stamp":"01/12/2022 14:11:33","Phase":"binded","Status":"00","i_sqn":"05"}}}
BindingTable: Object {"SQN":0,"Status":"Success","TimeStamp":"01/12/2022 14:11:33","BindingTableSize":3,"Devices":[{"5c0272fffe1c8fea":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00124b0014d9b773","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"5c0272fffe1c8fea":{"sourceEp":"01","Cluster":"0008","targetIEEE":"00124b0014d9b773","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"5c0272fffe1c8fea":{"sourceEp":"01","Cluster":"0300","targetIEEE":"00124b0014d9b773","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]}
ConfigureReporting: Object {"Ep":{"01":{"0006":{"TimeStamp":"01/12/2022 14:11:32","iSQN":{"0000":"01"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":"01/12/2022 14:11:32","iSQN":{"0000":"02"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}}
Max Buffer Size: "52"
Max Rx: "0052"
Max Tx: "0052"
macapa: "8e"
bitfield: "4001"
server_mask: "2c00"
descriptor_capability: "00"
ColorInfos:
Hue: 0
Saturation: 254
X: "45874"
Y: "19660"
ColorTemperatureMireds: "153"
ColorMode: 2
SWBUILD_1: ""
ZCL-IN-SQN:
0003: "0e"
ReadConfigureReporting:
Ep:
01:
0006: Object {"0000":{"TimeStamp":"01/12/2022 14:11:40","Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}}
0008: Object {"0000":{"TimeStamp":"01/12/2022 14:11:41","Status":"00","DataType":"20","MinInterval":"0005","MaxInterval":"012c","Change":"05"}}
TimeStamp: "01/12/2022 14:11:41"
GroupMemberShip: Object {"01":{}}
Param: Object {}
CheckParam: false
WriteAttributes: Object {"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0300":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}}
NwkID: "3bf0"

**Comment by pipiche38** [comment]
fixed with PR #1364
