### ISSUE TITLE
[Model Certification] - Livarno Lux E14 4,5W RGB Bulb

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#1362]
1. Please do provide device information such as Brand and Model name.
Livarno Lux E14 4,5W RGB Bulb // Model HG07834B manufactured by Lidl

3. Provide the URL where you have purchase the device
 LIDL.FR

4. Finaly copy-paste all information provided in the log

63:
Version: "3"
ZDeviceName: ""
Status: "inDB"
SQN: "0a"
Heartbeat: "32"
RIA: "0"
LQI: 65
Battery: Object {}
Model: "TS0505B"
ForceAckCommands: Array[0] []
MacCapa: "8e"
IEEE: "0c4314fffe84d42d"
Type: "ColorControlRGBWW"
ProfileID: "0104"
ZDeviceID: "010d"
App Version: "65"
Attributes List: Object {}
DeviceType: "FFD"
HW Version: "1"
Last Cmds: Array[0] []
LogicalType: "Router"
Manufacturer: "1002"
Manufacturer Name: "_TZ3000_th6zqqy6"
NbEp: "2"
PowerSource: "Main"
ReadAttributes: Object {"Ep":{"01":{"0000":{"TimeStamp":"01/12/2022 14:53:42","iSQN":{"0000":"07","0001":"07","0002":"07","0003":"08","0004":"08","0005":"08","0006":"09","0007":"09"},"Attributes":{"0000":"00","0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"00","0007":"00"},"ZigateRequest":{}},"0006":{"TimeStamp":"01/12/2022 14:53:39","iSQN":{"0000":"03"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":"01/12/2022 14:53:39","iSQN":{"0000":"04"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0300":{"TimeStamp":"01/12/2022 14:53:40","iSQN":{"0000":"05","0001":"05","0003":"05","0004":"06","0007":"06","0008":"06"},"Attributes":{"0000":"00","0001":"00","0003":"00","0004":"00","0007":"00","0008":"00"},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}}
ReceiveOnIdle: ""
Stack Version: "0"
Stamp: Object {"time":1669902823.8233352,"Time":"2022-12-01 14:53:43","MsgType":"8011","LastSeen":"01/12/2022 14:53:43"}
ZCL Version: "3"
Health: "Live"
Capability: Array[5] ["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"]
ZDPSQN: "07"
Epv2: Object {"01":{"ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"0300":{}},"ClusterOut":{"0019":{},"000a":{}},"ProfileID":"0104","ZDeviceID":"010d"},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}}
ZCLSQN: "0d"
RollingLQI: Array[11] [65,65,65,61,65,65,65,65,65,61,65]
ConfigSource: "DeviceConf"
Ep: Object {"01":{"1000":{},"0000":{"0004":"_TZ3000_th6zqqy6","0005":"TS0505B","0000":"3","0001":"65","0002":"0","0003":"1","0006":"","0007":"1"},"0003":{},"0004":{},"0005":{},"0006":{"0000":"01"},"0008":{"0000":"fe"},"0300":{"0000":"0","0001":"254","0003":"0","0004":"0","0007":"153","0008":"2"},"000a":{},"0019":{},"Type":"ColorControlRGBWW","ClusterType":{"26596":"ColorControlRGBWW"}},"f2":{"0021":{},"Type":""}}
WriteAttributes: Object {"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0300":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"f2":{"0021":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}}
ZDeviceVersion: "0001"
PairingInProgress: false
PairingTime: 1669902816.0808136
Bind: Object {"01":{"0006":{"Target":"0000","Stamp":"01/12/2022 14:53:36","Phase":"binded","Status":"00","i_sqn":"03"},"0008":{"Target":"0000","Stamp":"01/12/2022 14:53:37","Phase":"binded","Status":"00","i_sqn":"04"},"0300":{"Target":"0000","Stamp":"01/12/2022 14:53:37","Phase":"binded","Status":"00","i_sqn":"05"}}}
BindingTable: Object {"SQN":0,"Status":"Success","TimeStamp":"01/12/2022 14:53:37","BindingTableSize":3,"Devices":[{"0c4314fffe84d42d":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"0c4314fffe84d42d":{"sourceEp":"01","Cluster":"0008","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"0c4314fffe84d42d":{"sourceEp":"01","Cluster":"0300","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]}
ConfigureReporting: Object {"Ep":{"01":{"0006":{"TimeStamp":"01/12/2022 14:53:36","iSQN":{"0000":"01"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":"01/12/2022 14:53:36","iSQN":{"0000":"02"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}}
Max Buffer Size: "52"
Max Rx: "0052"
Max Tx: "0052"
macapa: "8e"
bitfield: "4001"
server_mask: "2c00"
descriptor_capability: "00"
ColorInfos: Object {"Hue":0,"Saturation":254,"X":"0","Y":"0","ColorTemperatureMireds":"153","ColorMode":2}
SWBUILD_1: ""
ZCL-IN-SQN: Object {"0003":"0a"}
ReadConfigureReporting: Object {"Ep":{"01":{"0006":{"0000":{"TimeStamp":"01/12/2022 14:53:43","Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}},"0008":{"0000":{"TimeStamp":"01/12/2022 14:53:43","Status":"00","DataType":"20","MinInterval":"0005","MaxInterval":"012c","Change":"05"}}}},"TimeStamp":"01/12/2022 14:53:43"}
GroupMemberShip: Object {"01":{}}
NwkID: "abb4"

**Comment by pipiche38** [comment]
already certified  as TS0505B
