### ISSUE TITLE
Support for Silicon Labs multiprotocol stack when using Silabs Multi-PAN RPC (Radio Co-Processor) firmware

### ISSUE THREAD

**Issue by Hedda** [sasu-drooz/Domoticz-Zigate#1389]
**Is your feature request related to a problem? Please describe.**

Maybe a bit early but posting as an enhancement feature request for consideration and for tracking: 

Suggest considering adding Silicon Labs CPC daemon (CPCd) and Zigbeeb (Zigbee deamon for EmberZNet Zigbee stack) in order to support Silabs Multi-PAN RPC firmware for multiprotocol adapters such as the new Home Assistant SkyConnect USB adapter (as well as Home Assistant Yellow SBC appliance with embedded EFR32MG21 radio module) now has experimental Multi-PAN RPC (Radio Co-Processor) firmware so that they an run both Zigbee and Thread (OpenThread) networks on the same radio. Read more:

https://github.com/zigpy/zigpy/discussions/894

and

https://github.com/NabuCasa/silabs-firmware

As well as hardware already supporting this with the mentioned experimental firmware:

https://www.home-assistant.io/skyconnect/

https://yellow.home-assistant.io/

https://www.home-assistant.io/blog/2021/09/13/home-assistant-yellow/

https://www.crowdsupply.com/nabu-casa/home-assistant-yellow

OpenThread page does a good job at describing the different architectural design differences between Radio Co-Processor (RCP) and Network Co-Processor (NCP) designs:

https://openthread.io/platforms/co-processor

**Describe the solution you'd like**

Considering looking into maybe adding Silicon Labs CPC daemon (CPCd) and Zigbeeb (Zigbee deamon for EmberZNet Zigbee stack) as a dependency in zigbee-herdsman in order to support Silabs Multi-PAN RPC firmware for multiprotocol adapters in your Zigbee For Domoticz plugin:

https://docs.silabs.com/gecko-platform/4.1/service/cpc/overview

https://www.silabs.com/documents/public/application-notes/an1351-using-co-processor-communication_daemon.pdf

https://docs.silabs.com/gecko-platform/4.1/service/api/group-cpc

https://github.com/SiliconLabs/cpc-daemon

![image](https://user-images.githubusercontent.com/6320001/208865484-cff04ee4-5c8e-49c7-86b1-af9767fa8b6e.png)

Also check out documentation for Home Assistant’s Silabs multiprotocol add-on which describes its architecture here:

https://github.com/home-assistant/addons/blob/master/silabs-multiprotocol/DOCS.md#architecture

![image](https://user-images.githubusercontent.com/6320001/208865417-a2c05e3b-ebf0-416f-8ea5-8b64b09acbed.png)

As I understand it; when you enable multi-protocol support in the add-on inside Home Assistant it automatically flashes a Multi-PAN RCP (Radio Co-Processor) firmware to the dongle as well as enables multi-protocol support with a Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) and accompanying Zigbee deamon (Zigbeed) and OpenThread Daemon (OT Daemon) that runs the Silabs EmberZNet Zigbee networking stack and OpenThread network stack respectivly on the host in order to allow multi-protocol support, so in essence that new firmware is what adds a requirement of at least an additional Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) and accompanying Zigbee deamon (Zigbeed) which is currently only automatically installed and available/supported if using Home Assistant OS or Home Assistant Container. 

The ZHA integration then connects to that Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) over TCP/IP using a socket as that in turn has taken over the serial port connection to the Home Assistant Skyconnect USB stick, and that  Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) handles the accompanying Zigbee deamon (Zigbeed) and OpenThread Daemon (OT Daemon).

As a workaround and for testing to connect remotely over TPC/IP on a local network you can install Home Assistant Skyconnect USB stick on another computer with Home Assistant OS (or Home Assistant Container) with enabled multiprotocol so it has flashed Multi-PAN RCP (Radio Co-Processor) firmware and you only use it for Thread protocol and not for the ZHA integration inside Home Assistant, then the Zigbee for Domoticz Plugin should be able to connect remotely to that Silicon Labs Zigbee deamon (Zigbeed) over TCP/IP using a socket to create a tunnel for EZSP communication as long as there is no firewall rules or container stuff blocking the TPC/IP socket traffic (and the ZHA integration in Home Assistant is not connected to that socket). 

As the Zigbee for Domoticz Plugin does today not install a Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) and accompanying Zigbee deamon (Zigbeed) so as such you can not simply access the Home Assistant Skyconnect USB stick if it has Multi-PAN RCP (Radio Co-Processor) firmware. What is missing for the Zigbee for Domoticz Plugin to be able work with Home Assistant Skyconnect USB stick when it has Multi-PAN RCP (Radio Co-Processor) firmware is its own installation of Silicon Labs [CPC daemon (CPCd)](https://github.com/SiliconLabs/cpc-daemon) and accompanying Zigbee deamon (Zigbeed).

At least in theory.

**Describe alternatives you've considered**

The alternative is to keep only supporting Silicon Labs NCP firmware for EmberZNet Zigbee

PS: This feature is also indirectly related to Thread (OpenThread) and Matter support in Domoticz as at least all EFR32MG1x and EFR32MG21x Silicon Labs IEEE_802.15.4-based radio adapters will be able to support Multi-PAN RCP (Radio Co-Processor) firmware run simulations run a Zigbee stack and a Thread (OpenThread) network stack concurrently at the same time.

**Comment by pipiche38** [comment]
For now we are supporting socket:// connectivity
Will be waiting for the zigpy progress and will see the demands.

Thanks for the information
