### ISSUE TITLE
Ikea Tradfri lightbulb not supported

### ISSUE THREAD

**Issue by manjh** [sasu-drooz/Domoticz-Zigate#1416]
![Export Device List raw (json)](https://github.com/zigbeefordomoticz/wiki/blob/master/Images/ExportDevicesRaw.png)

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
   
Finally you create an issue on GitHub with the following details

* Product Name 
* Brand
* URL on a web site
* What do you expect
* The logs from the pairing process
* export.json file as described here above
[export zipped.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10335532/export.zipped.zip)

**Comment by pipiche38** [comment]
If I'm not mistaken from the IKEA Vendor it seems to be a On/Off, Level Control and White color, but not RGB color. Is that correct ?

https://www.ikea.com/gb/en/p/tradfri-led-bulb-e14-470-lumen-smart-wireless-dimmable-white-spectrum-chandelier-30517643/

**Comment by manjh** [comment]
You are 100% correct!
Hans Man

Op di., jan. 3, 2023 om 17:10, Pipiche ***@***.***> schreef:
	If I'm not mistaken from the IKEA Vendor it seems to be a On/Off, Level Control and White color, but not RGB color. Is that correct ?

**Comment by pipiche38** [comment]
if you want to test it, just just have to switch to dev branch (6.4.119)

```
git checkout dev
git pull
```
then restart the plugin

Otherwise, you'll get it fix when the 3.6.009 will be released

**Comment by manjh** [comment]
I did as you asked, and sure enough: all devices are now green! The orange X's have disappeared.
Thank you for your quick support!
Hans Man

Op di., jan. 3, 2023 om 21:50, Pipiche ***@***.***> schreef:
	if you want to test it, just just have to switch to dev branch (6.4.119) 

	git checkout dev git pull  

	then restart the plugin 

	Otherwise, you'll get it fix when the 3.6.009 will be released
