### ISSUE TITLE
[Model Certification] - 12W Dual White and Color LED Bulb Plus

### ISSUE THREAD

**Issue by pabaillon** [sasu-drooz/Domoticz-Zigate#1426]
1. Please do provide device information such as Brand and Model name.
2. GLEDOPTO GL-B-008ZS
1. Provide the URL where you have purchase the device
2. https://fr.aliexpress.com/i/32906939699.html?gatewayAdapt=glo2fra
1. Finaly copy-paste all information provided in the log

{"Version":"3","ZDeviceName":"SejourAmpEst","Status":"inDB","SQN":"d3","Ep":{"0b":{"0000":{"4000":"2.0.0","0004":"GLEDOPTO","0005":"GL-B-008ZS","0000":"1","0001":"1","0002":"2","0003":"1","0006":"20131206","0007":"1"},"0003":{},"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","0000":"01"},"0008":{"0000":"fe"},"0300":{"0000":"21","0001":"254","0003":"12480","0004":"47190","0007":"158","0008":"1","400a":"31"},"ClusterType":{"2577":"ColorControlRGBWW"}},"0d":{"0000":{}}},"Heartbeat":"794","RIA":"4","LQI":68,"Battery":{},"Model":"GL-B-008ZS","ForceAckCommands":[],"MacCapa":"8e","IEEE":"00124b00210b6b2f","Type":"Switch/LvlControl/ColorControl","ProfileID":"c05e","ZDeviceID":"0210","App Version":"1","Attributes List":{"Request":{"0b":{"0000":1672594686.1256213,"0003":1672594686.1258805,"0004":1672594686.1261704,"0005":1672594686.126425,"0006":1672594686.1266747,"0008":1672594686.126924,"0300":1672594686.1271725},"0d":{"0000":1672594686.127449}}},"DeviceType":"FFD","HW Version":"1","Last Cmds":[],"LogicalType":"Router","Manufacturer":"0000","Manufacturer Name":"GLEDOPTO","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"0b":{"0000":{"TimeStamp":1672940276,"iSQN":{"4000":90721,"0004":90717,"0005":90717,"0000":3622,"0001":90718,"0002":90718,"0003":90718,"0006":90719,"0007":90719,"000a":90719,"000f":90720,"0010":90720,"0015":90720,"f000":90721},"Attributes":{"4000":"00","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","000a":"86","000f":"86","0010":"86","0015":"86","f000":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":1672936676,"iSQN":{"4001":90712,"4002":90712,"0000":3088},"Attributes":{"4001":"00","4002":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":1672936676,"iSQN":{"0000":3089},"Attributes":{},"ZigateRequest":{}},"0300":{"TimeStamp":1672590719,"iSQN":{"0000":90714,"0001":90714,"0003":90714,"0004":90715,"0007":90715,"0008":90715,"400a":90716},"Attributes":{"0000":"00","0001":"00","0003":"00","0004":"00","0007":"00","0008":"00","400a":"00"},"ZigateRequest":{}}},"0d":{"0000":{"TimeStamp":1672590703,"iSQN":{"0004":90695,"0005":90695},"Attributes":{"0004":"86","0005":"86"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":"2","Stamp":{"time":1672940276.4410925,"Time":"2023-01-05 17:37:56","MsgType":"8100","LastSeen":1672940276,"LastPing":1672940276},"ZCL Version":"1","Health":"","WriteAttributes":{"Ep":{"0b":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0300":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}},"0d":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"Bind":{"0b":{"0000":{"Target":"0000","Stamp":1672590716,"Phase":"binded","Status":"00","i_sqn":90700},"0003":{"Target":"0000","Stamp":1672590716,"Phase":"binded","Status":"00","i_sqn":90701},"0004":{"Target":"0000","Stamp":1672590716,"Phase":"binded","Status":"00","i_sqn":90702},"0005":{"Target":"0000","Stamp":1672590716,"Phase":"binded","Status":"00","i_sqn":90703},"0006":{"Target":"0000","Stamp":1672590716,"Phase":"binded","Status":"8c","i_sqn":90704},"0008":{"Target":"0000","Stamp":1672590717,"Phase":"binded","Status":"8c","i_sqn":90705},"0300":{"Target":"0000","Stamp":1672590717,"Phase":"binded","Status":"8c","i_sqn":90706}}},"ColorInfos":{"Hue":21,"Saturation":254,"X":"12480","Y":"47190","ColorTemperatureMireds":"158","ColorMode":1,"ColorCapabilities":"31"},"SWBUILD_3":"2.0.0","Log_UnknowDeviceFlag":1672940564.137632,"CertifiedDevice":false,"GroupMemberShip":{"0b":{}},"RoutingTable":[],"ConfigSource":"8043","Epv2":{"0b":{"ClusterIn":{"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"0300":{}},"ClusterOut":{},"ProfileID":"c05e","ZDeviceID":"0210"},"0d":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"SWBUILD_1":"20131206","ConfigureReporting":{"Ep":{"0b":{"0006":{"TimeStamp":1672590716.142275,"iSQN":{"0000":90708},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":1672590716.143679,"iSQN":{"0000":90709},"Attributes":{},"ZigateRequest":{}},"0300":{"TimeStamp":1672590716.1450076,"iSQN":{"0003":90710,"0004":90710,"0007":90710,"0008":90711},"Attributes":{},"ZigateRequest":{}}}}},"BindingTable":{"SQN":0,"Status":"Not Supported (132)","TimeStamp":1672590717.329233,"BindingTableSize":0,"Devices":[]},"Param":{},"Neighbours":[],"ReadConfigureReporting":{},"ConsistencyCheck":"ok"}

**Comment by pipiche38** [comment]
Should be ok.
If you want to test/check you'll need to move to dev branch, otherwise you can wait until the next release.

if you want to switch

```
git checkout dev
git pull

```
and restart the plugin
