### ISSUE TITLE
[Model Certification] - SAMOTECH SM301Z

### ISSUE THREAD

**Issue by depmicro** [sasu-drooz/Domoticz-Zigate#1445]
1. Please do provide device information such as Brand and Model name.
SAMOTECH SM301Z

2. Provide the URL where you have purchase the device
Amazon, but no longer available

3. Finaly copy-paste all information provided in the log

{"Version":"3","ZDeviceName":"","Status":"inDB","SQN":"2d","Ep":{"01":{"0000":{"0004":"TUYATEC-zn9wyqtr","0005":"RH3040","0001":"69","ffe2":"31","ffe4":"0","ffdf":"\u0010V+\u0012\u0010V+\u0012","0000":"3","0002":"0","0003":"1","0006":"","0007":"3"},"0001":{"0021":200,"0020":21,"0000":0},"0500":{"0002":"alarm1: 0, alaram2: 0, tamper: 0, battery: 0, Support Reporting: 0, restore Reporting: 0, trouble: 0, acmain: 0, test: 0, battdef: 0","0010":"0000000000000000","0000":"01","0001":"000d"},"0019":{},"000a":{},"ClusterType":{"306":"Voltage","307":"Door"}}},"Heartbeat":"35169","RIA":"4","LQI":68,"Battery":200,"Model":"RH3040","ForceAckCommands":[],"MacCapa":"80","IEEE":"8cf681fffe1ae517","Type":"Voltage/Door","ProfileID":"0104","ZDeviceID":"0402","App Version":"69","Attributes List":{},"DeviceType":"RFD","HW Version":"1","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"1002","Manufacturer Name":"TUYATEC-zn9wyqtr","NbEp":"1","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1673788593,"iSQN":{"4000":6556,"0004":6552,"0005":6552,"0000":6552,"0001":6553,"0002":6553,"0003":6553,"0006":6554,"0007":6554,"000a":6554,"000f":6555,"0010":6555,"0015":6555,"f000":6556},"Attributes":{"4000":"86","ffe2":"00","ffe4":"00","ffdf":"00","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","000a":"86","000f":"86","0010":"86","0015":"86","f000":"86"},"ZigateRequest":{}},"0500":{"TimeStamp":1673788572,"iSQN":{},"Attributes":{"0010":"00","0000":"00","0001":"00","0002":"00"},"ZigateRequest":{}},"0001":{"TimeStamp":1673963856,"iSQN":{"0000":6545,"0001":6545,"0003":6545,"0020":6546,"0021":6546,"0033":6546,"0035":6547},"Attributes":{"0000":"00","0001":"86","0003":"86","0020":"00","0021":"00","0033":"86","0035":"86"},"ZigateRequest":{}},"0019":{"TimeStamp":1673788589,"iSQN":{"0001":6548,"0002":6548,"0003":6548,"0004":6549,"0005":6549,"0006":6549,"0007":6550,"0008":6550,"0009":6550,"000a":6551},"Attributes":{"0001":"86","0002":"86","0003":"86","0004":"86","0005":"86","0006":"86","0007":"86","0008":"86","0009":"86","000a":"86"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":"0","Stamp":{"time":1673964760.9484437,"Time":"2023-01-17 15:12:40","MsgType":"8011","LastSeen":1673964760},"ZCL Version":"3","Health":"Live","IAS":{"Auto-Enrollment":{"Status":"Enrolled","Ep":{"01":{"Status":"Enrolled","ZoneId":"00"}}},"01":{"EnrolledStatus":1,"ZoneType":13,"ZoneTypeName":"motion","ZoneStatus":{"alarm1":0,"alarm2":0,"tamper":0,"battery":0,"Support Reporting":0,"Restore Reporting":0,"trouble":0,"acmain":0,"test":0,"battdef":0,"doorbell":0,"GlobalInfos":"0;0;0;0;0;0;0;0;0;0;0","TimeStamp":1673788565}}},"BatteryUpdateTime":1673963856,"ConfigSource":"8043","Log_UnknowDeviceFlag":1673872345.7983296,"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0500":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Bind":{"01":{"0500":{"Target":"0000","Stamp":1673788565,"Phase":"binded","Status":"00","i_sqn":6530},"0000":{"Target":"0000","Stamp":1673788580,"Phase":"binded","Status":"00","i_sqn":6540},"0001":{"Target":"0000","Stamp":1673788581,"Phase":"binded","Status":"00","i_sqn":6541}}},"CertifiedDevice":false,"SWBUILD_1":"","IASBattery":100,"Epv2":{"01":{"ClusterIn":{"0000":{},"0001":{},"0500":{}},"ClusterOut":{"0019":{},"000a":{}},"ProfileID":"0104","ZDeviceID":"0402"}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1673788582.3991184,"BindingTableSize":3,"Devices":[{"8cf681fffe1ae517":{"sourceEp":"01","Cluster":"0500","targetIEEE":"00158d0005be9630","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8cf681fffe1ae517":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00158d0005be9630","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"8cf681fffe1ae517":{"sourceEp":"01","Cluster":"0001","targetIEEE":"00158d0005be9630","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"Param":{"Capability":1},"ConfigureReporting":{"Ep":{"01":{"0500":{"TimeStamp":1673788579.0820687,"iSQN":{"0000":6543,"0001":6543,"0002":6543},"Attributes":{},"ZigateRequest":{}},"0001":{"TimeStamp":1673788579.082899,"iSQN":{"0000":6544,"0020":6544,"0021":6544},"Attributes":{},"ZigateRequest":{}}}}},"Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ConsistencyCheck":"ok","RollingLQI":[59,3,63,59,66,67,63,64,66,68,68],"SQN_000a":"1b"}

**Comment by pipiche38** [comment]
This should ok.

can you kindly move to the dev branch

```
git checkout dev
git pull
```

Then  you need to redo the pairing properly and for that
(1) remove the existing widgets Voltage and Door which have been created from Domoticz
(2) Check in Plugin WebUI Objects List that the device is removed otherwise delete it with the trash icon
(3) redo the pairing
