### ISSUE TITLE
[Model Certification] - OSRAM/LEDVANCE SMART+ culot E27 

### ISSUE THREAD

**Issue by pouilld** [sasu-drooz/Domoticz-Zigate#1449]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
1. Finaly copy-paste all information provided in the log
OSRAM/LEDVANCE SMART+ culot E27 8,5W 

https://www.amazon.fr/Osram-Ampoule-Connect%C3%A9e-Dimmable-Zigbee/dp/B074KJ72MP/ref=sr_1_6?__mk_fr_FR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=2ECJ5DDFSV448&keywords=osram+smart+%2B+E27&qid=1674059027&s=lighting&sprefix=osram+smart+%2B+e27%2Clighting%2C82&sr=1-6

{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"","Ep":{},"Heartbeat":"146","RIA":"6","LQI":{},"Battery":{},"Model":"","ForceAckCommands":[],"MacCapa":"8e","IEEE":"7cb03eaa0a040691","Type":{},"ProfileID":{},"ZDeviceID":{},"App Version":"","Attributes List":{},"DeviceType":"FFD","HW Version":"","Last Cmds":[],"LogicalType":"Router","Manufacturer":"","Manufacturer Name":"","NbEp":"","PowerSource":"Main","ReadAttributes":{},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1674058353.6191096,"Time":"2023-01-18 17:12:33","MsgType":"  4d","LastSeen":1674058353},"ZCL Version":"","Health":"Not Reachable","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"PairingInProgress":true,"ConsistencyCheck":"Bad Pairing"}

Please note that I have been able to pair the device once but I am unable to pair it again after deleting the object from plugin

**Comment by pipiche38** [comment]
As you have a "bad pairing" i cannot make any integration, and we don't even know if it is integrated or not.
please use the forum for that.
