### ISSUE TITLE
[Model Certification] - TRADFRI bulb E27 CWS 806lm

### ISSUE THREAD

**Issue by Chaussette23** [sasu-drooz/Domoticz-Zigate#1481]
Ampoule IKEA Tradfri RGB (multicolor), achetée chez IKEA.

Fonctionne parfaitement, aucune difficulté pour l'appairer (même méthode que les autres ampoules Tradfri. La gestion des couleurs, température, puissance d'éclairage est parfaite.

Dump du plugin : 
`{"PluginInfos":{...}}`

**Comment by pipiche38** [comment]
The change has been done, and will be ready for the next release.

if you want to test, in between

```
git remote add pipiche https://github.com/pipiche38/Domoticz-Zigbee.git
git pull pipiche optimized-device/6.3.010
git checkout optimized-device/6.3.010
```

the  restart the plugin

to fall back

```
git checkout stable6
git status
git remote remove pipiche
```


Please kindly consider enabling the analytics part. This will help us to know who is using the plugin and having more insights to define our priorities.

**Comment by Chaussette23** [comment]
I confirm it now have a green check mark !
