### ISSUE TITLE
[Model Certification] - SonOff SNZB-02D Non optimized plugin

### ISSUE THREAD

**Issue by IW2FAG-11** [sasu-drooz/Domoticz-Zigate#1485]
[export.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10511712/export.zip)
![Export Device List raw (json)](https://github.com/zigbeefordomoticz/wiki/blob/master/Images/ExportDevicesRaw.png)

1. Got to the Tools Menu
1. Select Plugin Raw Devices (json)
1. Export

This will create an export.json file that you can save.
   
Finally you create an issue on GitHub with the following details

* Product Name 
* Brand
* URL on a web site
* What do you expect
* The logs from the pairing process
* export.json file as described here above

**Comment by pipiche38** [comment]
The change has been done, and will be ready for the next release.

if you want to test, in between

```
git remote add pipiche https://github.com/pipiche38/Domoticz-Zigbee.git
git pull pipiche optimized-device/6.3.010
git checkout optimized-device/6.3.010
```

the  restart the plugin

to fall back

```
git checkout stable6
git status
git remote remove pipiche
```

**Comment by IW2FAG-11** [comment]
Thanks. 
Is ok, now is working.

**Comment by pipiche38** [comment]
Release 6.3.010 has been released today, so you can switch to it , if not yet done
```
git checkout stable6
git pull
```
and  if you have tested and used the remote pipiche, you can simply discard it
`git remote remove pipiche`
