### ISSUE TITLE
[Model Certification] - TS0601 Tête thermostatique intelligente 

### ISSUE THREAD

**Issue by joenizar** [sasu-drooz/Domoticz-Zigate#1516]
1. Please do provide device information such as Brand and Model name.
1. Provide the URL where you have purchase the device
1. Finaly copy-paste all information provided in the log
3. Tete thermostatique Zigbee
https://www.planete-domotique.com/tete-thermostatique-intelligente-compatible-zigbee-3-0-moes.html
Coordinateur Clé USB SONOFF
https://www.sonoff.be/a-69234890/accessoires/sonoff-zigbee-3-0-dongle-plus-e/#description
Détails de l'objet:

{"PluginInfos":{"HardwareID":18,"HomeFolder":"/home/freebox/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/freebox/domoticz/","UserDataFolder":"/home/freebox/domoticz/","WebRoot":"","Database":"/home/freebox/domoticz/domoticz.db","Language":"fr","Version":"6.3","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220812082358-if00","Username":"","Password":"","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode5":"http://127.0.0.1:8080","Mode6":"2","DomoticzVersion":"2022.2","DomoticzHash":"eea9db734","DomoticzBuildTime":"2022-11-05 12:05:35","PluginBranch":"stable6","PluginVersion":"6.3.010","TimeStamp":1675347974,"available":"6.3.010","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"e0798dfffe77bf8d","NetworkSize":"Total: 1 | Routers: 1 | End Devices: 0","NetworkDevices":{}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"","Status":"UNKNOW","SQN":"23","Ep":{"01":{"0000":{"0004":"_TZE200_9sfg7gm0","0005":"TS0601"},"0004":{},"0005":{},"ef00":{},"0019":{},"000a":{}}},"Heartbeat":"2295","RIA":"4","LQI":96,"Battery":{},"Model":"TS0601","ForceAckCommands":[],"MacCapa":"80","IEEE":"8cf681fffeb0f29c","Type":{},"ProfileID":"0104","ZDeviceID":"0051","App Version":"","Attributes List":{},"DeviceType":"RFD","HW Version":"","Last Cmds":[],"LogicalType":"End Device","Manufacturer":"1002","Manufacturer Name":"_TZE200_9sfg7gm0","NbEp":"1","PowerSource":"Battery","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1675336499,"iSQN":{"0004":"00","0005":"00"},"Attributes":{"0004":"00","0005":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"Off","Stack Version":"","Stamp":{"time":1675346405.7135985,"Time":"2023-02-02 14:00:05","MsgType":"8011","LastSeen":1675346405},"ZCL Version":"","Health":"Live","Capability":["Reduced-Function Device","Standard security","NwkAddr should be allocated"],"ZDPSQN":"03","RollingLQI":[100,100,92,92,92,96,96,96,96,96,96],"Epv2":{"01":{"ClusterIn":{"0000":{},"0004":{},"0005":{},"ef00":{}},"ClusterOut":{"0019":{},"000a":{}},"ProfileID":"0104","ZDeviceID":"0051"}},"ZCLSQN":"05","WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ZDeviceVersion":"0001","ConfigSource":"8043","ZCL-IN-SQN":{"000a":"1c","ef00":"23"},"SQN_000a":"1c","PairingInProgress":true,"_rawNodeDescriptor":"1002005200522c000080524002","Max Buffer Size":"52","Max Rx":"0052","Max Tx":"0052","macapa":"80","bitfield":"4002","server_mask":"2c00","descriptor_capability":"00","Tuya":{"Valve 0x66":"00000005","Valve 0x69":"0000012c","Valve 0x6a":"00","Valve 0x6b":"00000014","TUYA_MCU_VERSION_RSP":"88"}}}

Pas reconnu dans les dispositifs
Erreur dans les Logs:

2023-02-02 11:15:13.824 Status: Zigbee: Device Annoucement: NwkId: 6e07 Ieee: 8cf681fffeb0f29c MacCap: 80
2023-02-02 11:15:14.092 Status: Zigbee: [2] NEW OBJECT: 6e07 Model Name: TS0601
2023-02-02 11:15:14.092 Status: Zigbee: [2] NEW OBJECT: 6e07 Manufacturer Name: _TZE200_9sfg7gm0
2023-02-02 11:15:19.104 Status: Zigbee: [3] NEW OBJECT: 6e07 Model Name: TS0601
2023-02-02 11:15:19.105 Status: Zigbee: [3] NEW OBJECT: 6e07 Manufacturer Name: _TZE200_9sfg7gm0
2023-02-02 11:15:19.102 Error: Zigbee: processNotinDBDevices - Creat Domo Device Failed !!! for 6e07 status: 8043

Merci

**Comment by pipiche38** [comment]
Can you switch to the branch hotfix-6.3.011

```
git pull
git checkout hotfix-6.3.011
```

then restart the plugin and redo the pairing

**Comment by pipiche38** [comment]
can you do the test on that branch 

```
git pull
git checkout config-release-6.3.011

```

you need to restart the plugin and redo the pairing from 0

**Comment by pipiche38** [comment]
any update return ?
