### ISSUE TITLE
TUYA - PJ-mini-ZSW01 - seen as TS011F switch only (no power meter)

### ISSUE THREAD

**Issue by Overnuts** [sasu-drooz/Domoticz-Zigate#1523]
Hi, 
I bought a TUYA "PJ-mini-ZSW01" 16A module for monitoring : 
https://fr.aliexpress.com/item/1005004128359494.html

Received today, it pairs to my system, device is "certified" as TS011F by plugin, but only as a switch.

This device should have power meter functions.

thanks for your work :-)

Note, while pairing, device was only wired to power, nothing after switched circuit

Here are plugin logs:

> 2023-02-06 18:16:48,679 INFO    : [     MainThread 0] Request Accepting new Hardware for 240 seconds 
2023-02-06 18:16:48,778 INFO    : [    ZigpyCom_16 0] PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 240, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1675703808.6694882, 'ACKIsDisable': False, 'Sqn': None}
2023-02-06 18:16:48,792 INFO    : [    ZigpyCom_16 0] PERMIT-TO-JOIN: duration: 240 for Radio: znp for node: None
2023-02-06 18:16:48,817 INFO    : [    ZigpyCom_16 0] Calling self.app.permit(time_s=240, node=None )
2023-02-06 18:16:49,425 INFO    : [    ZigpyCom_16 0] returning from the self.app.permit(time_s=240, node=None )
2023-02-06 18:16:50,171 INFO    : [ZigpyForwarder_16 0] Accepting new Hardware: Enable (On)
2023-02-06 18:18:28,503 INFO    : [ZigpyForwarder_16 0] --> Adding device 903d in self.DevicesInPairingMode
2023-02-06 18:18:28,522 INFO    : [ZigpyForwarder_16 0] --> ['903d']
2023-02-06 18:18:28,543 INFO    : [ZigpyForwarder_16 0] [None] NEW OBJECT: 903d None
2023-02-06 18:18:28,563 INFO    : [ZigpyForwarder_16 0] ReadAttributeRequest_0000_for_tuya 903d
2023-02-06 18:18:29,192 INFO    : [ZigpyForwarder_16 0] check_found_plugin_model - TS011F _TZ3000_cjrngdr3  None
2023-02-06 18:18:29,444 INFO    : [ZigpyForwarder_16 0] Decode8046 - Match Descriptor response: SQN: 00 Status: 00 Nwkid: 3d90 Lenght: 00 List: 
2023-02-06 18:18:29,571 INFO    : [ZigpyForwarder_16 0] [-] NEW OBJECT: 903d Active Endpoint Response Ep: 01 LQI: 0
2023-02-06 18:18:29,576 INFO    : [ZigpyForwarder_16 0] [-] NEW OBJECT: 903d Active Endpoint Response Ep: f2 LQI: 0
2023-02-06 18:18:32,371 INFO    : [     MainThread 0] [0] NEW OBJECT: 903d Model Name: TS011F
2023-02-06 18:18:32,447 INFO    : [     MainThread 0] [0] NEW OBJECT: 903d Manufacturer Name: _TZ3000_cjrngdr3
2023-02-06 18:18:32,453 INFO    : [     MainThread 0] [None] NEW OBJECT: 903d Request Node Descriptor
2023-02-06 18:18:35,354 INFO    : [     MainThread 0] ----> Tuya Hardware: fffe
2023-02-06 18:18:59,692 INFO    : [ZigpyForwarder_16 0] check_found_plugin_model - TS011F _TZ3000_cjrngdr3 1141 None
2023-02-06 18:19:09,319 INFO    : [     MainThread 0] Request Disabling Accepting new Hardware
2023-02-06 18:19:09,427 INFO    : [    ZigpyCom_16 0] PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 0, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1675703949.307765, 'ACKIsDisable': False, 'Sqn': None}
2023-02-06 18:19:09,443 INFO    : [    ZigpyCom_16 0] PERMIT-TO-JOIN: duration: 0 for Radio: znp for node: None
2023-02-06 18:19:09,465 INFO    : [    ZigpyCom_16 0] Calling self.app.permit(time_s=0, node=None )
2023-02-06 18:19:09,783 INFO    : [ZigpyForwarder_16 0] Accepting new Hardware: Disable (Off)
2023-02-06 18:19:10,127 INFO    : [    ZigpyCom_16 0] returning from the self.app.permit(time_s=0, node=None )

and the json export    (due to github issue limitation to 64ko text, I removed other working devices 3x lexman 16 power / 1x Zlinky / 1x temp/humidity sensor):

> [{"Status":"","RIA":"10","AssociatedDevices":[{"Devices":[],"SQN":0,"Status":"","TimeStamp":"25/01/2023 18:43:12","Time":"25/01/2023 18:43:12"},{"Devices":[],"SQN":0,"Status":"","TimeStamp":"31/01/2023 18:48:15","Time":"31/01/2023 18:48:15"}],"LogicalType":"Coordinator","PowerSource":"Main","Neighbours":[{"SQN":0,"Status":"","TimeStamp":"16/01/2023 08:23:05","Time":"16/01/2023 08:23:05","Devices":[{"003c":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"84fffe21662bc8f9","_permitjnt":"??"}},{"9434":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"69fffe8149185088","_permitjnt":"??"}},{"3aa2":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":106,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf51f","_permitjnt":"??"}},{"7bcb":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":131,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf435","_permitjnt":"??"}},{"01d1":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":26,"_rxonwhenidl":"??","_IEEE":"84ba20fffeceafe4","_permitjnt":"??"}},{"f041":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":125,"_rxonwhenidl":"??","_IEEE":"00158d0005bea862","_permitjnt":"??"}}]},{"SQN":0,"Status":"","TimeStamp":"17/01/2023 17:12:24","Time":"17/01/2023 17:12:24","Devices":[{"003c":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"84fffe21662bc8f9","_permitjnt":"??"}},{"9434":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"69fffe8149185088","_permitjnt":"??"}},{"7bcb":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":127,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf435","_permitjnt":"??"}},{"01d1":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":54,"_rxonwhenidl":"??","_IEEE":"84ba20fffeceafe4","_permitjnt":"??"}},{"3aa2":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":113,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf51f","_permitjnt":"??"}},{"f041":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":126,"_rxonwhenidl":"??","_IEEE":"00158d0005bea862","_permitjnt":"??"}}]},{"SQN":0,"Status":"","TimeStamp":"20/01/2023 09:34:56","Time":"20/01/2023 09:34:56","Devices":[{"003c":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"84fffe21662bc8f9","_permitjnt":"??"}},{"9434":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"69fffe8149185088","_permitjnt":"??"}},{"f041":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":126,"_rxonwhenidl":"??","_IEEE":"00158d0005bea862","_permitjnt":"??"}},{"3aa2":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":124,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf51f","_permitjnt":"??"}},{"7bcb":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":116,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf435","_permitjnt":"??"}},{"01d1":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":37,"_rxonwhenidl":"??","_IEEE":"84ba20fffeceafe4","_permitjnt":"??"}}]},{"SQN":0,"Status":"","TimeStamp":"25/01/2023 18:43:12","Time":"25/01/2023 18:43:12","Devices":[{"003c":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"84fffe21662bc8f9","_permitjnt":"??"}},{"9434":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"69fffe8149185088","_permitjnt":"??"}},{"3aa2":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":123,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf51f","_permitjnt":"??"}},{"7bcb":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":125,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf435","_permitjnt":"??"}},{"01d1":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":67,"_rxonwhenidl":"??","_IEEE":"84ba20fffeceafe4","_permitjnt":"??"}},{"f041":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":126,"_rxonwhenidl":"??","_IEEE":"00158d0005bea862","_permitjnt":"??"}}]},{"SQN":0,"Status":"","TimeStamp":"31/01/2023 18:48:15","Time":"31/01/2023 18:48:15","Devices":[{"003c":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"84fffe21662bc8f9","_permitjnt":"??"}},{"9434":{"_relationshp":"Child","_devicetype":"End Device","_depth":1,"_lnkqty":170,"_rxonwhenidl":"Rx-Off","_IEEE":"69fffe8149185088","_permitjnt":"??"}},{"3aa2":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":119,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf51f","_permitjnt":"??"}},{"7bcb":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":128,"_rxonwhenidl":"??","_IEEE":"0c4314fffe5bf435","_permitjnt":"??"}},{"01d1":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":76,"_rxonwhenidl":"??","_IEEE":"84ba20fffeceafe4","_permitjnt":"??"}},{"f041":{"_relationshp":"Sibling","_devicetype":"Router","_depth":255,"_lnkqty":137,"_rxonwhenidl":"??","_IEEE":"00158d0005bea862","_permitjnt":"??"}}]}],"NeighbourTableSize":12,"ZDeviceName":"Zigbee Coordinator","RoutingTable":[{"SQN":0,"Status":"Success","TimeStamp":"13/01/2023 10:19:35","Time":"13/01/2023 10:19:34","RoutingTableTableSize":2,"Devices":[{"01d1":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"01d1"}},{"3aa2":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"f041"}}]},{"SQN":0,"Status":"Success","TimeStamp":"17/01/2023 17:12:25","Time":"17/01/2023 17:12:24","RoutingTableTableSize":2,"Devices":[{"3aa2":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"7bcb"}},{"0300":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}}]},{"SQN":0,"Status":"Success","TimeStamp":"20/01/2023 09:34:57","Time":"20/01/2023 09:34:56","RoutingTableTableSize":3,"Devices":[{"0300":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}},{"01d1":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"7bcb"}},{"7bcb":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}}]},{"SQN":0,"Status":"Success","TimeStamp":"25/01/2023 18:43:14","Time":"25/01/2023 18:43:12","RoutingTableTableSize":2,"Devices":[{"7bcb":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"7bcb"}},{"0300":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}}]},{"SQN":0,"Status":"Success","TimeStamp":"31/01/2023 18:48:16","Time":"31/01/2023 18:48:15","RoutingTableTableSize":3,"Devices":[{"01d1":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}},{"0300":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"3aa2"}},{"f041":{"Status":"Active (0)","MemoryConstrained":0,"ManyToOne":0,"RouteRecordRequired":0,"NextHopNwkId":"f041"}}]}],"IEEE":"00124b0025e14d57","Ep":{"00":{},"02":{"0000":{}},"01":{"0000":{},"0006":{},"000a":{},"0019":{},"0501":{},"0001":{},"0020":{},"0500":{},"0502":{}}},"Version":"3","Health":"Live","ConsistencyCheck":"","LQI":{},"_rawNodeDescriptor":"000000a000a02c01008f504000","Max Buffer Size":"50","Max Rx":"00a0","Max Tx":"00a0","macapa":"8f","bitfield":"4000","server_mask":"2c01","descriptor_capability":"00","Manufacturer":"0000","DeviceType":"FFD","ReceiveOnIdle":"On","Stamp":{"LasteSeen":{},"Time":"2023-01-31 18:48:47","MsgType":"8002","time":1675187327.2722378,"LastSeen":"31/01/2023 18:48:47"},"SQN":"00","Model":"CC1352/CC2652, Z-Stack 3.30+ (znp)","ZDPSQN":"11","MapLQI":{"3aa2":172,"01d1":114,"7bcb":181},"NwkID":"0000"},
{"Version":"3","ZDeviceName":"MeterCumulus","Status":"inDB","SQN":"27","Heartbeat":"73","RIA":"0","LQI":39,"Battery":{},"Model":"TS011F","ForceAckCommands":[],"MacCapa":"8e","IEEE":"a4c138fbb897b665","Type":"Switch","ProfileID":{},"ZDeviceID":{},"App Version":"77","Attributes List":{},"DeviceType":"FFD","HW Version":"","Last Cmds":[],"LogicalType":"Router","Manufacturer":"1141","Manufacturer Name":"_TZ3000_cjrngdr3","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":"06/02/2023 18:25:17","iSQN":{"0004":"06","0000":"06","0001":"06","0005":"06","0007":"06","fffe":"06"},"Attributes":{"0004":"00","0000":"00","0001":"00","0005":"00","0007":"00","fffe":"00","ffe2":"00","ffe4":"00","ffdf":"00"},"ZigateRequest":{}},"e000":{"TimeStamp":"06/02/2023 18:19:03","iSQN":{},"Attributes":{"d001":"00","d002":"00"},"ZigateRequest":{}},"0019":{"TimeStamp":"06/02/2023 18:18:58","iSQN":{"0001":"02","0002":"02","0003":"02","0004":"02","0005":"02","0006":"02","0007":"03","0008":"03","0009":"03","000a":"03"},"Attributes":{"0001":"00","0002":"00","0003":"00","0004":"00","0005":"00","0006":"00","0007":"00","0008":"00","0009":"00","000a":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":"06/02/2023 18:26:24","iSQN":{"4001":"04","4002":"04","4003":"04","8001":"04","8002":"04","fffd":"05","0000":"0b"},"Attributes":{"4001":"00","4002":"00","4003":"86","5000":"00","8000":"00","8001":"00","8002":"00","fffd":"00","0000":"00"},"ZigateRequest":{}},"e001":{"TimeStamp":"06/02/2023 18:18:37","iSQN":{},"Attributes":{"d010":"00","d030":"00","d000":"00","d001":"00","d002":"00","d003":"00","d004":"00","d005":"00"},"ZigateRequest":{}},"0b04":{"TimeStamp":"06/02/2023 18:25:19","iSQN":{},"Attributes":{"0505":"00","0508":"00","050b":"00"},"ZigateRequest":{}},"0702":{"TimeStamp":"06/02/2023 18:25:20","iSQN":{},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"ReceiveOnIdle":"","Stack Version":"","Stamp":{"time":1675704384.871561,"Time":"2023-02-06 18:26:24","MsgType":"8102","LastSeen":"06/02/2023 18:26:24"},"ZCL Version":"3","Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZCLSQN":"0b","ZDPSQN":"06","RollingLQI":[36,39,36,33,33,36,36,39,39,36,39],"ConfigSource":"DeviceConf","Ep":{"01":{"0000":{"0004":"_TZ3000_cjrngdr3","0000":"3","0001":"77","0005":"TS011F","0007":"1","fffe":"0","ffe2":"54","ffe4":"0","ffdf":"X\u0000t+\u0013Y\u0000t+\u0012\r\u0000\u0000\u0000\u0012\b\u0000\u0000\u0000\u0012"},"0004":{},"0005":{},"0006":{"4001":"0","4002":"0","5000":"1","8000":"00","8001":"1","8002":"0","0000":"00","fffd":"2"},"000a":{},"0019":{"0001":"ffffffff","0002":"0000004d","0003":"0002","0004":"ffffffff","0005":"ffff","0006":"00","0007":"1141","0008":"ffff","0009":"0000"},"Type":"Switch","e000":{"d001":"06","d002":"0a"},"ClusterType":{"1115":"Switch"},"e001":{"d010":0,"d030":0,"d000":0,"d001":"00000000","d002":"0","d003":"0","d004":"0","d005":"0"},"0b04":{"0505":244,"0508":0,"050b":0},"0702":{"0000":0}},"f2":{}},"WriteAttributes":{"Ep":{"01":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"000a":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"e001":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0b04":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0702":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"Epv2":{"01":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"ZCL-IN-SQN":{"e000":"18","0006":"14","e001":"15","000a":"16","0000":"24","0b04":"25","0702":"26"},"PairingInProgress":false,"PairingTime":1675703912.5330448,"Bind":{"01":{"0006":{"Target":"0000","Stamp":"06/02/2023 18:18:38","Phase":"binded","Status":"00","i_sqn":"03"},"0019":{"Target":"0000","Stamp":"06/02/2023 18:18:39","Phase":"binded","Status":"00","i_sqn":"04"}}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":"06/02/2023 18:18:56","BindingTableSize":2,"Devices":[{"a4c138fbb897b665":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00124b0025e14d57","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"a4c138fbb897b665":{"sourceEp":"01","Cluster":"0019","targetIEEE":"00124b0025e14d57","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":"06/02/2023 18:18:32","iSQN":{"0000":"01"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"CertifiedDevice":true,"SQN_000a":"16","_rawNodeDescriptor":"1141004200422a00008e424001","Max Buffer Size":"42","Max Rx":"0042","Max Tx":"0042","macapa":"8e","bitfield":"4001","server_mask":"2a00","descriptor_capability":"00","ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":"06/02/2023 18:19:06","Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}}}},"TimeStamp":"06/02/2023 18:19:06"},"GroupMemberShip":{"01":{}},"Param":{},"CheckParam":false,"NwkID":"903d"}]

**Comment by pipiche38** [comment]
which plugin version are you ?

**Comment by Overnuts** [comment]
running plugin 6.3.009

**Comment by pipiche38** [comment]
So please make sure to run on the latest plugin version 6.3.010
You'll have to remove the existing paired device and re-pair it
