### ISSUE TITLE
Bulb disappeared in network after upgrade plugin to 6.3.010

### ISSUE THREAD

**Issue by RMvdBijl** [sasu-drooz/Domoticz-Zigate#1529]
In plug-in 6.3.009 the bulb Gledopto GL-B-004P was forwarding Zigbee signals to TRADFRI bulb GU10 WW 400lm. Since the update to plugin 6.3.010 the TRADFI (tuinhuisje) is unreachable.

The bulb Gledopto GL-B-004P (buitenlantaan) itself is working fine e.g. switching on/off on time schedule. But in the network diagram (topology) the Gledopto GL-B-004P (buitenlantaan) is disappeared whereas the TRADFRI is still visible but not responding. 

So the issue seems to be the forwarding of Zigbee signals to the TRADFRI via Gledopto GL-B-004P.
I already rebooted the Raspberry Pi and fully turned off the electricity of the Gledopto bulb.
Could this indeed be the case? 

Kind regards, Ronald

P.s. The export.sjon is a file type that is not supported by the drop & drag menu. So, it can not be uploaded. 

[_PluginZigbee_03.2 (1).log](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10710318/_PluginZigbee_03.2.1.log)

**Comment by pipiche38** [comment]
the plugin is not doing anything with Zigbee signals. So I don't understand what you are refering.

Please use the forum and not the GitHub issue which is related to bugs into the plugin

if you want you can switch back to the previous version of the plugin

`git checkout stable6-6.3.009`
