### ISSUE TITLE
unknown device

### ISSUE THREAD

**Issue by Overnuts** [sasu-drooz/Domoticz-Zigate#1549]
Hi 
While trying to pair  the 1 channel device:
https://fr.aliexpress.com/item/1005004371232755.html

I get 
`Error: Zigbee: Decode 8041 - Receive an IEEE: a4c138056b32f770 with a NwkId: f5f4, seems not known by the plugin`
in domoticz logs

nothing in z4d - plugin 6.3.010 - python 3.7

**Comment by pipiche38** [comment]
Please kindly use one of the forum.

the message just tell you that a message has been received by the plugin for which it doesn't have any known device in the plugin
