### ISSUE TITLE
Decode Temperature/Pression/Humidity from cluster 0000 attribute FF01

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#155]
as per http://faire-ca-soi-meme.fr/hack/2017/06/30/xiaomi-mi-gestion-tensions-de-piles/#comment-2044

**Comment by pipiche38** [comment]
From the code, we are expecting to get only BatterLevel with Cluster 0x0000 with attribute 0xff01 in line with what is documented in https://zigate.fr/xiaomi-capteur-temperature-humidite-clusters/

Required further investigations

**Comment by pipiche38** [comment]
https://github.com/sasu-drooz/Domoticz-Zigate/issues/153#issuecomment-418698748

**Comment by mce35** [comment]
From my logs on two temp/humidity sensors v1, each data is composed like this and has a constant length of 31 bytes:
`**0121**XXXX**0421**a813**0521**XX00**0624**XX00000000**6429**XXXX**6521**XXXX**0a21**0000`

Bold text is what I think are tags.

v2 sensors adds 6 bytes after humidity corresponding to the atmospheric pressure (tag 662B + 4 bytes data).
