### ISSUE TITLE
STOFTMOLN ceilingwall lamp WW24[Model Certification] - 

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#1553]
Plugin create a Dimmer who is full fonctionnal, just need a certification

1. Please do provide device information such as Brand and Model name.
IKEA STOFTMOLN ceilingwall lamp WW24

2. Provide the URL where you have purchase the device

https://www.ikea.com/fr/fr/p/stoftmoln-plafonnier-applique-connecte-sans-fil-a-variateur-dintensite-blanc-chaud-blanc-30497490/

https://zigbee.blakadder.com/Ikea_T2035.html

3. Finaly copy-paste all information provided in the log

{"PluginInfos":{"HardwareID":102,"HomeFolder":"/opt/domoticz/userdata/plugins/Domoticz-Zigbee/","StartupFolder":"/opt/domoticz/","UserDataFolder":"/opt/domoticz/userdata/","WebRoot":"","Database":"/opt/domoticz/userdata/domoticz.db","Language":"fr","Version":"6.4","Author":"pipiche38","Name":"Zigbee_RDC","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyUSB1","Username":"","Password":"","Key":"Zigate","Mode1":"ZigpyZNP","Mode2":"USB","Mode3":"False","Mode4":"9445","Mode5":"http://127.0.0.1:8080","Mode6":"2","DomoticzVersion":"2022.2 (build 15013)","DomoticzHash":"64ea1e084","DomoticzBuildTime":"2023-01-29 09:33:36","PluginBranch":"beta6","PluginVersion":"6.4.232","TimeStamp":1677518406,"available":"6.4.232","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"Z-Stack 3.30+ (build 20220219)","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":7,"Zigpy":true,"CoordinatorModel":"CC1352/CC2652, Z-Stack 3.30+ (znp)","CoordinatorFirmwareVersion":"Z-Stack 3.30+ (build 20220219)","DisplayFirmwareVersion":"Znp - Z-Stack 3.30+ (build 20220219)","CoordinatorIEEE":"00124b0024c2c7cd","NetworkSize":"Total: 64 | Routers: 40 | End Devices: 24","NetworkDevices":{"1002":{"_TZ3000_g5xawfcq":["TS0121"],"_TYZB01_xfpdrwvc":["TS0011"],"_TYZB01_6sadkhcy":["TS0002"],"_TYZB01_b8cr31hp":["TS0003"],"_TZ3000_vzopcetz":["TS011F-multiprise"],"_TZ1800_fcdjzz3s":["TY0202"],"_TYZB01_seqwasot":["TS0001"],"_TZ3000_utagpnzs":["TS0505A"],"_TZ3000_adkvzooy":["TS0042"],"_TZE200_nklqjk62":["TS0601-_TZE200_nklqjk62"],"_TZE200_dfxkcots":["TS0601-dimmer"],"_TYZB01_vkwryfdr":["TS0115"],"_TZE200_rddyvrci":["TS0601-curtain"],"_TYST11_zivfvd7h":["TS0601-eTRV1"],"_TZ3000_ecgiiid3":["TS0003"],"_TZ3000_peszejy7":["TS0041"],"_TYZB01_a476raq2":["TS0201"],"_TZE200_c88teujp":["TS0601-eTRV3"],"_TYZB01_ncdapbwy":["TS0203"]},"1037":{"LUMI":["lumi.light.aqcn02","lumi.remote.b186acn01","lumi.sensor_ht","lumi.sensor_86sw2","lumi.ctrl_86plug.aq1","lumi.sensor_motion.aq2","lumi.sensor_motion"]},"0000":{"SZ":["Lamp_01"]},"117c":{"IKEA of Sweden":["TRADFRI control outlet","TRADFRI bulb E27 opal 1000lm","TRADFRI bulb E27 W opal 1000lm","TRADFRI onoff switch","TRADFRI motion sensor","TRADFRI bulb E27 WS clear 950lm"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"Plafonnier Couloir RDC","Status":"inDB","SQN":"26","Ep":{"01":{"1000":{},"0000":{"4000":"1.0.006","0004":"IKEA of Sweden","0005":"STOFTMOLN ceiling/wall lamp WW24","0000":3,"0001":16,"0002":103,"0003":1,"0006":"20210520","0007":1,"000a":"5432303335"},"0003":{},"0004":{},"0005":{"0001":0},"0006":{"4001":0,"4002":0,"0000":"00"},"0008":{"0000":254},"fc57":{},"0019":{},"ClusterType":{"27672":"LvlControl"}},"f2":{}},"Heartbeat":"509","RIA":"4","LQI":120,"Battery":{},"Model":"STOFTMOLN ceilingwall lamp WW24","ForceAckCommands":[],"MacCapa":"8e","IEEE":"040d84fffe4de2f2","Type":"Switch/LvlControl","ProfileID":"0104","ZDeviceID":"0101","App Version":16,"Attributes List":{},"DeviceType":"FFD","HW Version":1,"Last Cmds":[],"LogicalType":"Router","Manufacturer":"117c","Manufacturer Name":"IKEA of Sweden","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1677513339,"iSQN":{"4000":"0d","0004":"09","0005":"09","0000":"09","0001":"0a","0002":"0a","0003":"0a","0006":"0b","0007":"0b","000a":"0b","000f":"0c","0010":"0c","0015":"0c","f000":"0d"},"Attributes":{"4000":"00","0004":"00","0005":"00","0000":"00","0001":"00","0002":"00","0003":"00","0006":"00","0007":"00","000a":"00","000f":"86","0010":"86","f000":"86"},"ZigateRequest":{}},"0019":{"TimeStamp":1677513338,"iSQN":{"0001":"03","0002":"03","0003":"03","0004":"04","0005":"04","0006":"04","0007":"05","0008":"05","0009":"05","000a":"06"},"Attributes":{"0001":"86","0002":"86","0004":"86","0005":"86","0007":"86","0008":"86","000a":"86"},"ZigateRequest":{}},"0006":{"TimeStamp":1677518185,"iSQN":{"4001":"07","4002":"07","0000":"2a"},"Attributes":{"4001":"00","4002":"00","0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":1677518171,"iSQN":{"0000":"2b"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0005":{"TimeStamp":1677514273,"iSQN":{},"Attributes":{"0001":"00"},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":103,"Stamp":{"time":1677518185.340912,"Time":"2023-02-27 18:16:25","MsgType":"8102","LastSeen":1677518185},"ZCL Version":3,"Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZDPSQN":"19","Epv2":{"01":{"ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0008":{},"fc57":{}},"ClusterOut":{"0019":{}},"ProfileID":"0104","ZDeviceID":"0101"},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"ZCLSQN":"2c","RollingLQI":[76,112,112,112,116,131,131,120,123,120,120],"WriteAttributes":{"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0008":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"fc57":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ZDeviceVersion":"0001","ConfigSource":"8043","PairingInProgress":false,"_rawNodeDescriptor":"117c005200522c00008e524001","Max Buffer Size":"52","Max Rx":"0052","Max Tx":"0052","macapa":"8e","bitfield":"4001","server_mask":"2c00","descriptor_capability":"00","PairingTime":1677513336.0922437,"Bind":{"01":{"1000":{"Target":"0000","Stamp":1677513337,"Phase":"binded","Status":"00","i_sqn":"0a"},"0000":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"04"},"0003":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"05"},"0004":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"06"},"0005":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"07"},"0006":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"08"},"0008":{"Target":"0000","Stamp":1677513336,"Phase":"binded","Status":"00","i_sqn":"09"},"fc57":{"Target":"0000","Stamp":1677513338,"Phase":"binded","Status":"00","i_sqn":"0b"}}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1677513340.2639701,"BindingTableSize":8,"Devices":[{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0003","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0004","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0000","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0003","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0004","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0005","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0008","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0005","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0006","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"0008","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"1000","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"1000","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"040d84fffe4de2f2":{"sourceEp":"01","Cluster":"fc57","targetIEEE":"00124b0024c2c7cd","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1677513336.0985496,"iSQN":{"0000":"01"},"Attributes":{"0000":"00"},"ZigateRequest":{}},"0008":{"TimeStamp":1677513336.0990026,"iSQN":{"0000":"02"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"CertifiedDevice":false,"ZCL-IN-SQN":{"0006":"26","0008":"25","0019":"06","0005":"00"},"SWBUILD_1":"20210520","SWBUILD_3":"1.0.006","ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":1677514273.4602573,"Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}},"0008":{"0000":{"TimeStamp":1677514273.4578974,"Status":"00","DataType":"20","MinInterval":"0005","MaxInterval":"012c","Change":"05"}}}},"TimeStamp":1677514273.4602551},"OTAClient":{"ManufacturerCode":"117c","ImageType":"4105","CurrentImageVersion":"00010006"},"Param":{},"CheckParam":false,"GroupMemberShip":{"01":{}}}}

**Comment by pipiche38** [comment]
Will be released with 6.3.011 and later merged into develop branch
