### ISSUE TITLE
TUYA Zigbee presence sensor ZY-M100

### ISSUE THREAD

**Issue by nivekamoud** [sasu-drooz/Domoticz-Zigate#1557]
Hi All,
See below, can u please have a look at it. It is now a switch with temp measuremnt what is not correct. 
Hope to here from u, 
gr kevin

* Product Name: ZY-M100
* Brand: Tuya
* URL on a web site,:  https://smarthomescene.com/reviews/tuya-zigbee-human-presence-sensor-zy-m100-review/
* What do you expect:  expext presence sensor and a Lux measurement
* The logs from the pairing process
[_PluginZigbee_34.log](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10923124/_PluginZigbee_34.log)
![export (1) json](https://user-images.githubusercontent.com/63060174/223783090-8b454a64-d418-48be-a24b-3efc831c2102.jpg)

* export.json file as described here above

**Comment by pipiche38** [comment]
which version of the Plugin do you use ?

**Comment by pipiche38** [comment]
This device has been integrated and is available on the 'develop' branch
please switch to it ( taking assumption that you are on 6.3.011

```
git checkout develop
git pull
sudo python3 -m pip --ignore-requires-python --no-input install -r requirements.txt --upgrade
```

then  restart

you'll have to remove the existing device, and then  when well removed, you can redo the pairing

**Comment by nivekamoud** [comment]
Ok thanks will try-out tonight

**Comment by nivekamoud** [comment]
ok got everything working again, now on develop branch, 6.4.3.12, radar distance gives a lot of updates. Can i set this somewhere in the parameters.

**Comment by pipiche38** [comment]
@deennoo do you have anu advice ?

Here after are the device parameters' default.

distance is in cm
time/duration is in seconds

```
"RadarMotionSensitivity": 7,
"RadarMotionMinRange": 60,
"RadarMotionMaxRange": 690,
"RadarMotionDelay": 1,
"RadarMotionFading": 150
```

**Comment by deennoo** [comment]
> 

i'll add info on wiki very soon

**Comment by nivekamoud** [comment]
Ok, for now i have deleted the distance. I will test it for a couple of dans and let u kmow

**Comment by deennoo** [comment]
> Ok, for now i have deleted the distance. I will test it for a couple of dans and let u kmow

Distance is send only if device get a body on his scope.

Earsing distance widget will only "clean" your log but device keep sending thé value when présence is détected, no way to change this

**Comment by deennoo** [comment]
> > 
> 
> i'll add info on wiki very soon

Wiki Param is update for this device

**Comment by nivekamoud** [comment]
Wow thats fast.
