### ISSUE TITLE
Woolley SA-029 smartplug not optimized

### ISSUE THREAD

**Issue by RMvdBijl** [sasu-drooz/Domoticz-Zigate#1558]
Hi, I installed two new smartplugs but they are not optimized with ZiGate plugin. Hower, I'm able to turn them on/off. The reasons for this brand/product is the range extender functionality. 

* Woolly smartplug SA-029 Zigbee 3.0  
* Brand: Woolly 
* https://www.amazon.nl/dp/B0B96ZPTPD?psc=1&ref=ppx_yo2ov_dt_b_product_details
* Expectations: 1) object to be optimized in ZiGate plugin + 2) range extender functionality
[_PluginZigbee_03.3.log](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10925122/_PluginZigbee_03.3.log)

* The export.sjon file can not be uploaded. A message appears: 'We don't support that file type. Try again'.

**Comment by pipiche38** [comment]
please zip the export.json , without I cannot make much

**Comment by RMvdBijl** [comment]
[export raw.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10925485/export.raw.zip)

I hope this file works for you?

**Comment by RMvdBijl** [comment]
![netwerk-diagram](https://user-images.githubusercontent.com/122694376/223928789-eb5fd1ae-89e1-413d-94c0-b23e69cacaf3.png)
[export errors.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10928117/export.errors.zip)

Hi pipich38,

I attached also the errors.sjon and topology map.

In the topology map you'll find two type of smartplugs e.g. Innr (test 1-2-3) and Woolly (1-2). The are connected with the dimmers (kachel, zithoek, eettafel) but the plugs are not interconnected to each other although they are placed in the same small room. The typology map shows them as end products. Manufacturers of the Innr SP 220 en Woolley SA-029 claims these plugs to be 'range extenders'.

I have 3 requests:
1. Woolley smartplugs to be optimized for ZiGate plugin / Domoticz
2. Woolley smartplugs LED on/off indicator is now always on. Can you make it go on/off when switching?
3. Woolley smartplug and  Innr smartplugs to become range extenders?

Many thanks in advance!

**Comment by pipiche38** [comment]
Please could you kindly switch to the *develop* branch and check if the smart plugs are shown as Optimized

```
git checkout develop
git pull
```

then restart the plugin

As the Topology, we have issues with the Zigate firmware, and we cannot do better than what you currently get.
Zigate is a closed system and we are facing also of issues that we don't have on open coordinator like Texas Instrument and SilLabs

**Comment by RMvdBijl** [comment]
Hi pipiche38,
Thanks for the plugin. 
Unfortunately, the Woolley smartplug is still not optimized with this update.

What I did is the following:
1) via Putty/SSH terminal:
cd domoticz/plugins/Domoticz-Zigbee/
sudo git checkout develop
sudo git pull

2) via webbrowser ZiGate dashboard / admin / restart plug in

**Comment by RMvdBijl** [comment]
[export raw 2.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10946753/export.raw.2.zip)
[export errors 2.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10946754/export.errors.2.zip)

**Comment by RMvdBijl** [comment]
Hi pipiche38,
In addition to my previous message I also restarted the plugin via 'sudo reboot' in Putty.  This makes the Zigate dashboard unreachable probably due to 'develop' branch. So I couldn't check if this way of restarting the plugin resolves the remaining issue.

Anyway I'm back on the 'develop' branche and did the 'git pull' for the second time and restarted the plugin via Zigate webdashboard, but the smartplugs are still not optimized. They can be switched on/off and the blue LED indicator keeps constantly burning as they did in the 'stable' branche. I attached the git pull proces in Putty. 
[export errors 3.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10948701/export.errors.3.zip)
[export raw 3.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10948702/export.raw.3.zip)


Regarding the topology. I read that Zigate firmware is a closed system but does this mean that the smartplugs are still able to 'extend the range' of zigbee signals e.g. forwarding them to the next Zigbee hardware (e.g. smartplug, bulb, dimmer) but that the topology diagram is unable to visualize this? If so, is there a way to check whether the range extender of a smartplug, bulb or dimmer is active? Or is the Zigate firmware blocking all range extender functionalities of the hardware anyway?

Ronald

![develop branche _ git pull](https://user-images.githubusercontent.com/122694376/224489263-f0d3356c-9918-4674-baf7-4274c95600e2.png)

**Comment by pipiche38** [comment]
First `git pull`is not enough to do the update, it is highly recommended to use the WebUI > Admin > Plugin Upgrade (and then restart) to have a correct update done.
If you cannot, it is key that you use

```
git pull  or sudo git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

As the topology, the issue is just on the graph, I had a look to the export and the 2 plug have a Neighbours table, which means they can route and a Full-Function Device so routing is expected.

**Comment by RMvdBijl** [comment]
Hi pipiche38, thanks for the instructions. 
The good news is that Woolley smartplug is now shown as optimized (green) in teh webUI. 
Unfortunately the blue LED indicator keeps burning when switching the smartplug to 'off'. 
Q: are you able to fix this?

[export raw 4.zip](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/10971659/export.raw.4.zip)

**Comment by pipiche38** [comment]
I was not aware of that. Don't know if the plug has the capability to get the led piloted via Zigbee API, I'll investigate

**Comment by pipiche38** [comment]
Unfortunately at that time we don't have information if and how to manage the Led from Zigbee.

https://community.home-assistant.io/t/amazon-woolley-zigbee-plug/433639

**Comment by RMvdBijl** [comment]
Hi pipiche38, thanks for the research. In the meantime the supplier Woolley confirms that the blue LED is a pairing indicator, not power on/off.
We can now close my request. I will confirm the changes that has optimized this smartplug. Many thanks for your support. Kind regards, Ronald
