### ISSUE TITLE
Just cosmetic log info

### ISSUE THREAD

**Issue by mcmikev** [sasu-drooz/Domoticz-Zigate#1570]
When starting the plugin the status shows this line:
`Zigbee: Please watch plugin log into /home/pi/domoticz/plugins/Domoticz-Zigbee/Logs//PluginZigbee_48.log`

After /Logs ther is a double // visible.
The log is in the right place, but just visual it is not right.

**Comment by pipiche38** [comment]
Happy to review a PR catching that

**Comment by pipiche38** [comment]
Would required to activate the PosixPathUpdate parameter.
When activated, the Paths in the Config file will be updated, and the result is the file is not compatible downward .
 #1572
