### ISSUE TITLE
[Model Certification] - iluminize 5120.1200

### ISSUE THREAD

**Issue by rom289** [sasu-drooz/Domoticz-Zigate#1584]
Bonjour,

- iluminize 5120.1200
- https://www.iluminize.com/en/shop/product/5120-1-zigbee-3-0-actuator-mini-for-push-button-200w-400w-for-230v-lamps-black-2

`{"PluginInfos":{"HardwareID":82,"HomeFolder":"/home/pi/domoticz/plugins/Domoticz-Zigbee/","StartupFolder":"/home/pi/domoticz/","UserDataFolder":"/home/pi/domoticz/","WebRoot":"","Database":"/home/pi/domoticz/domoticz.db","Language":"fr","Version":"6.4","Author":"pipiche38","Name":"Zigbee","Address":"0.0.0.0","Port":"9999","SerialPort":"/dev/ttyUSB-sonoffzigbee2","Key":"Zigate","Mode1":"ZigpyEZSP","Mode2":"USB","Mode3":"False","Mode4":"9440","Mode6":"2","DomoticzVersion":"2023.1","DomoticzHash":"f9b9ac774","DomoticzBuildTime":"2023-02-14 15:06:40","PluginBranch":"beta6","PluginVersion":"6.4.420","CertifiedDbVersion":"2.45","TimeStamp":1681844779,"available":"6.4.418","available-firmMajor":0,"available-firmMinor":0,"FirmwareVersion":"6.10.3.0 build 297","FirmwareUpdate":false,"PluginUpdate":false,"LogLevel":2,"Zigpy":true,"CoordinatorModel":"Unknown Silicon Labs","DisplayFirmwareVersion":"UNK - 6.10.3.0 build 297","CoordinatorIEEE":"dc8e95fffe08a614","NetworkSize":"Total: 24 | Routers: 19 | End Devices: 5","NetworkDevices":{"1037":{"LUMI":["lumi.plug","lumi.remote.b286acn02","lumi.remote.b1acn01","lumi.sensor_switch.aq2"]},"1141":{"_TZ3000_cehuw1lw":["TS011F-plug"],"_TZ3000_typdpbpg":["TS011F-plug"],"_TZ3000_54hjn4vs":["TS0002"]},"1166":{"innr":["SP 220"]},"1286":{"SONOFF":["S26R2ZB"]},"110c":{"OSRAM":["Plug 01"]},"0000":{"SONOFF":["BASICZBR3"]},"117c":{"IKEA of Sweden":["TRADFRI bulb E27 CWS opal 600lm","TRADFRI bulb E27 W opal 1000lm"]}}},"Analytics":1,"Device":{"Version":"3","ZDeviceName":"","Status":"inDB","SQN":"32","Ep":{"01":{"1000":{},"0000":{"4000":"2.5.3_r47","0004":"iluminize","0005":"5120.1200","0000":3,"0001":0,"0002":0,"0003":0,"0006":"NULL","0007":1,"0008":255,"0009":255,"000a":"3030","000b":"NULL","fffd":1},"0003":{},"0004":{},"0005":{},"0006":{"4000":"01","4001":0,"4002":0,"4003":255,"0000":"00","fffd":1},"0b05":{},"0019":{},"ClusterType":{"667":"Switch"}},"f2":{}},"Heartbeat":"264","RIA":"4","LQI":84,"Battery":{},"Model":"5120.1200","ForceAckCommands":[],"MacCapa":"8e","IEEE":"804b50fffebbecf3","Type":"Switch","ProfileID":"0104","ZDeviceID":"0100","App Version":0,"Attributes List":{},"DeviceType":"FFD","HW Version":0,"Last Cmds":[],"LogicalType":"Router","Manufacturer":"100b","Manufacturer Name":"iluminize","NbEp":"2","PowerSource":"Main","ReadAttributes":{"Ep":{"01":{"0000":{"TimeStamp":1681842974,"iSQN":{"4000":"11","8000":"11","0000":"0a","0001":"0a","0002":"0a","0003":"0b","0004":"0b","0005":"0b","0006":"0c","0007":"0c","0008":"0c","0009":"0d","000a":"0d","000b":"0d","000c":"0e","000d":"0e","000e":"0e","0010":"0f","0011":"0f","0012":"0f","0013":"10","0014":"10","0015":"10","fffd":"11","fffe":"12","ffdf":"12","ffe0":"12","ffe1":"13","ffe2":"13","ffe4":"13"},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":1681842974,"iSQN":{"0000":"02","0001":"02","0002":"02","0003":"03","0004":"03","0005":"03","0006":"04","0007":"04","0008":"04","0009":"05","000a":"05","fffd":"05","fffe":"06"},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":1681843464,"iSQN":{"4000":"07","4001":"07","4002":"08","4003":"08","fffd":"08","fffe":"09","0000":"1d"},"Attributes":{},"ZigateRequest":{}}},"f2":{"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"ReceiveOnIdle":"On","Stack Version":0,"Stamp":{"time":1681844652.943674,"Time":"2023-04-18 21:04:12","MsgType":"8102","LastSeen":1681844652},"ZCL Version":3,"Health":"Live","Capability":["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"],"ZDPSQN":"10","RollingLQI":[84,84,80,84,84,84,88,80,80,80,84],"Epv2":{"01":{"ClusterIn":{"1000":{},"0000":{},"0003":{},"0004":{},"0005":{},"0006":{},"0b05":{}},"ClusterOut":{"0019":{}},"ProfileID":"0104","ZDeviceID":"0100"},"f2":{"ClusterIn":{},"ClusterOut":{},"ProfileID":{},"ZDeviceID":{}}},"ZCLSQN":"1d","ZDeviceVersion":"0001","ConfigSource":"8043","WriteAttributes":{"Ep":{"01":{"1000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0000":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0003":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0004":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0005":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0006":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0b05":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}},"0019":{"TimeStamp":0,"iSQN":{},"Attributes":{},"ZigateRequest":{}}}}},"PairingInProgress":false,"_rawNodeDescriptor":"100b005200522c00008e524001","Max Buffer Size":"52","Max Rx":"0052","Max Tx":"0052","macapa":"8e","bitfield":"4001","server_mask":"2c00","descriptor_capability":"00","PairingTime":1681842974.1272333,"Bind":{"01":{"1000":{"Target":"0000","Stamp":1681842975,"Phase":"binded","Status":"00","i_sqn":"0a"},"0000":{"Target":"0000","Stamp":1681842974,"Phase":"binded","Status":"00","i_sqn":"04"},"0003":{"Target":"0000","Stamp":1681842976,"Phase":"binded","Status":"00","i_sqn":"05"},"0004":{"Target":"0000","Stamp":1681842976,"Phase":"binded","Status":"00","i_sqn":"06"},"0005":{"Target":"0000","Stamp":1681842974,"Phase":"binded","Status":"00","i_sqn":"07"},"0006":{"Target":"0000","Stamp":1681842976,"Phase":"binded","Status":"00","i_sqn":"08"},"0b05":{"Target":"0000","Stamp":1681842975,"Phase":"binded","Status":"00","i_sqn":"09"}}},"BindingTable":{"SQN":0,"Status":"Success","TimeStamp":1681842978.1473584,"BindingTableSize":7,"Devices":[{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0000","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0003","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0004","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0005","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0006","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"0b05","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}},{"804b50fffebbecf3":{"sourceEp":"01","Cluster":"1000","targetIEEE":"dc8e95fffe08a614","targetNickName":"Zigbee Coordinator","targetEp":"01"}}]},"ConfigureReporting":{"Ep":{"01":{"0006":{"TimeStamp":1681842974.1639957,"iSQN":{"0000":"01"},"Attributes":{"0000":"00"},"ZigateRequest":{}}}}},"CertifiedDevice":false,"ZCL-IN-SQN":{"0006":"32","0019":"31"},"SWBUILD_1":"NULL","SWBUILD":"2.5.3_r47","ReadConfigureReporting":{"Ep":{"01":{"0006":{"0000":{"TimeStamp":1681842978.1140168,"Status":"00","DataType":"10","MinInterval":"0001","MaxInterval":"012c"}}}},"TimeStamp":1681842978.1140122},"OTAClient":{"ManufacturerCode":"100b","ImageType":"081d","CurrentImageVersion":"0000002f"}}}`

Fonctionne correctement mais apparait en non-optimisé.

Merci

**Comment by pipiche38** [comment]
If you are on bullseye and you have at least python3.9 , please switch to develop branch

```
git checkout develop
git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

restart the plugin

The device should then be seen as optimized/certified.

For test purposes, I would appreciate if you can remove /delete the device from Domoticz and the plugin
restart the plugin
redo the pairing
check that it is still functional

**Comment by rom289** [comment]
Objet optimisé. Parfait. Merci
