### ISSUE TITLE
Implement zigpy API to change Zigbee channel for all radio libraires that supports the new API

### ISSUE THREAD

**Issue by Hedda** [sasu-drooz/Domoticz-Zigate#1593]
**Is your feature request related to a problem? Please describe.**

zigpy has now implemented a unified API to change Zigbee channel on an existing network -> https://github.com/zigpy/zigpy/pull/1190

Support for this new feature has also been implemented in all existing active radio libraries for zigpy.

**Describe the solution you'd like**

Ability to migrate/change Zigbee channel for existing Zigbee network if using Zigbee Coordinator via zigpy.

**Describe alternatives you've considered**

Alternative for zigpy libraires before was to to do a Zigbee network backup and then do a restore after changing channel in backups.

**Additional context**

Couple of tips to end-user is to try to make sure that all their devices are online as with this features the Zigbee Coordinator will send hannel change broadcast a few times before actually changing the channel on the network to give devices a chance to switch channel. Also be patient as can take up to an hour before devices reconnect and to speed up the process end-users can try invoking a state change on each sensor device and/or manually power-cycle them starting will mains powered devices.

Be aware that not all radio libraries for zigpy handle changing Zigbee channels the same or as well as some other zigpy radio libraries do, and regardless, sometimes the end-user will need to re-pair either manually power-cycle or even re-pair some of their devices (especially some brands of battery-powered devices have a tendency to get orphaned as they do not react to channel change broadcast,).

**Comment by pipiche38** [comment]
For now I do not plan to move to a more recent zigpy version, as this is impacting us and would require development.
The latest zigpy version which consolidated the coordinator parameter, broke some features like Set TX-Power.

Unfortunatly we don't have the bandwith nor the competences to develop zigpy PR.
