### ISSUE TITLE
Fail to start with dnspython 2.3.0

### ISSUE THREAD

**Issue by xbeaudouin** [sasu-drooz/Domoticz-Zigate#1600]
**Describe the bug**

After upgrading OS from FreeBSD 13.1 to 13.2, and all the packages, plugins complains about DNSpython version.

**To Reproduce**

Upgrade FreeBSD 13.1 to 13.2, pkg upgrade -f

**Expected behavior**

Should NOT  Requirement.parse('dnspython==2.2.1'))

**Screenshots**
May  3 22:05:23 domoticz pkg[59648]: domoticz-devel upgraded: 2023.1.15118 -> 2023.1.15223
May  3 22:05:23 domoticz pkg[59648]: py39-jsonschema upgraded: 4.16.0 -> 4.17.3_2
May  3 22:05:24 domoticz pkg[59648]: py39-dnspython upgraded: 2.2.1_1,1 -> 2.3.0,1
May  3 22:05:24 domoticz pkg[59648]: py39-requests upgraded: 2.28.2 -> 2.29.0
May  3 22:05:24 domoticz pkg[59648]: py39-pyusb upgraded: 1.0.2 -> 1.2.1
May  3 22:05:24 domoticz pkg[59648]: py39-aiosqlite upgraded: 0.18.0 -> 0.18.0_1
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Initialized version 6.3, author 'pipiche38'
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Zigbee for Domoticz plugin started!
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Python3 requires 3.8 or above and you are running 3.9
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Checking Python modules /usr/local/domoticz/plugins/Domoticz-Zigate/requirements.txt
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Call to function 'onStart' failed, exception details:
May  3 22:06:59 domoticz domoticz[9104]: Zigate: Traceback (most recent call last):
May  3 22:06:59 domoticz domoticz[9104]: Zigate:   File "/usr/local/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1537, in onStart
May  3 22:06:59 domoticz domoticz[9104]: Zigate:     _plugin.onStart()
May  3 22:06:59 domoticz domoticz[9104]: Zigate:   File "/usr/local/domoticz/plugins/Domoticz-Zigate/plugin.py", line 285, in onStart
May  3 22:06:59 domoticz domoticz[9104]: Zigate:     if check_requirements( self ):
May  3 22:06:59 domoticz domoticz[9104]: Zigate:   File "/usr/local/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1504, in check_requirements
May  3 22:06:59 domoticz domoticz[9104]: Zigate:     pkg_resources.require(req)
May  3 22:06:59 domoticz domoticz[9104]: Zigate:   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 909, in require
May  3 22:06:59 domoticz domoticz[9104]: Zigate:     needed = self.resolve(parse_requirements(requirements))
May  3 22:06:59 domoticz domoticz[9104]: Zigate:   File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 800, in resolve
May  3 22:06:59 domoticz domoticz[9104]: Zigate:     raise VersionConflict(dist, req).with_context(dependent_req)
May  3 22:06:59 domoticz domoticz[9104]: Zigate: pkg_resources.VersionConflict: (dnspython 2.3.0 (/usr/local/lib/python3.9/site-packages), Requirement.parse('dnspython==2.2.1'))

**Plugin (please complete the following information):**
 - OS: FreeBSD 13.2-RELEASE
 - Plugin version 6.3
 - Plugin branch stable6

**Comment by pipiche38** [comment]
Yes dnspython should be 2.2.1 max

**Comment by pipiche38** [comment]
Here is what is in the requirements.txt file of stable6

`dnspython==2.2.1`

and here is what we have on the develop branch

`dnspython==2.3.0`

So I suggest that you switch to 'develop' branch

```
git checkout develop
git pull
sudo python3 -m pip install requirements.txt --upgrade
```

**Comment by xbeaudouin** [comment]
ok. why on requirement we don't use charset-normalizer >= 2.0.11 ? Having 3.1.0 on systems and have other plugins that use it... 
According to https://pypi.org/project/charset-normalizer/#history 2.0.11 older than one year.
Is there any blocking point to not use the lastest stable version ?
Regards

**Comment by pipiche38** [comment]
I think that is something which is coming from the zigpy library
will re-check

**Comment by pipiche38** [comment]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/1562  was the reason
