### ISSUE TITLE
Platform.dist() removed since Python3.7

### ISSUE THREAD

**Issue by CocoRid** [sasu-drooz/Domoticz-Zigate#1604]
**Describe the bug**
The following error message appeared in Domoticz log, every restart : 
"Error: Zigate: switchPiZigate_mode - unable to find distribution: Assuming debian, Error: module 'platform' has no attribute 'dist'"

Why still using "platform.dist()" or even "platform.linux_distribution()" in "Modules/piZigate.py", it's removed since Python 3.7 and your plugin require Python 3.8 or higher ([Platform Unix Platforms](https://docs.python.org/3.5/library/platform.html#unix-platforms)) ?
Can you check to use another function, that is available and not already deprecated (as "distro.linux_distribution()" 😄)?

**To Reproduce**
=> Just restart Domoticz

**Expected behavior**
Not have this error message

**Plugin (please complete the following information):**
 - OS : Raspbian Bullseye
 - Plugin 6.3
 - Plugin stable6
 - Python : 3.9

**Comment by pipiche38** [comment]
Thanks for that. Would you mind creating a PR ?
I'mnot using any PiZigate nor the Raspbian distrib

**Comment by pipiche38** [comment]
@CocoRid is that something you can help and provide a PR ?

**Comment by CocoRid** [comment]
Hello
I will do a pull request soon about this.
It's not blocking.

Just : what is expected at lines 55/56 ? Linux distribution will return "raspbian" and not "debian". Actually forced as Debian, i have to see if the fonction called at Line 56 really works.
