### ISSUE TITLE
[Model Certification] - ZLinky_TIC-standard-mono

### ISSUE THREAD

**Issue by pub-marcel** [sasu-drooz/Domoticz-Zigate#1618]
1. lixee ZLinky_TIC 
1. https://lixee.fr/produits/37-zigate-usb-ttl-3770014375148.html
1. {'ConfigurationReportChunk': 1, 'PollingCusterff66': 3600, 'ZLinkyPollingGlobal': 86400}
2. 
![Capture](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/assets/128159842/8e32b969-062f-44af-b63e-85e662e62c42)

**Comment by pub-marcel** [comment]
Erreur : ReadCluster 0b04 - a5d7/01 Unexpected 050f/663 linkyMode: None

**Comment by pipiche38** [comment]
What is the issue?
