### ISSUE TITLE
[Model Certification] - RH3052

### ISSUE THREAD

**Issue by leosmiers** [sasu-drooz/Domoticz-Zigate#1631]
1. Please do provide device information such as Brand and Model name.
Nedis SmartLife (ZigBee, Vochtsensor, Binnen, Batterij) I think later versions use TS0201

1. Provide the URL where you have purchase the device
https://www.kabelshop.nl/Nedis-Slimme-temperatuursensor-Nedis-SmartLife-ZigBee-Vochtsensor-Binnen-Batterij-ZBSC10WT-i22007-t1438072.html This might be newer and using TS0201

1. Finaly copy-paste all information provided in the log

[RH3052_json.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12040351/RH3052_json.txt)

**Comment by pipiche38** [comment]
fix [2.74]
