### ISSUE TITLE
New option: WebUI IP

### ISSUE THREAD

**Issue by jf67-07** [sasu-drooz/Domoticz-Zigate#1633]
Hi,

There is already an option "WebUI Port" to set the port of the z4d dashboard.

Would it be possible to add an option "WebUI IP" or" WebUI Interface" ?
The default value would be 0.0.0.0, so the server would listen on all interfaces (as today), but it would be possible to set 127.0.0.1 to restrict the interface and to secure the access to the dashboard (by putting an auth proxy in front of z4d or by using a ssh redirection).
Thanks.

**Comment by pipiche38** [comment]
I like the idea.
Adding an extra parameters would be challenging, but we could probably change parameters WebUI to be
<port> or <ip:port>
So if you have only a port number then we will bind on 0.0.0.0 and if the pare meter has the format x.y.z.a:pppp then we will bind port pppp on ip x.y.z.a

If that makes sense I'll see to implement it

**Comment by pipiche38** [comment]
Unfortunatly not so easy with Domoticz 

https://www.domoticz.com/forum/viewtopic.php?t=40629

**Comment by jf67-07** [comment]
Hi,
Sure, it makes sense to use the current WebUI Port.
Let's wait for a solution from the Domoticz team.
Thanks

**Comment by pipiche38** [comment]
looks like there is not much willingness on the Domoticz side. 
Sorry for that
