### ISSUE TITLE
[Model Certification] - Sonoff SNZB-03 Motion Sensor

### ISSUE THREAD

**Issue by rcrocus** [sasu-drooz/Domoticz-Zigate#1634]
_Please do provide device information such as Brand and Model name =>_ Sonoff SNZB-03 Motion Sensor
_Provide the URL where you have purchase the device_ =>https://www.domotique-store.fr/domotique/usages/domotique-alarme-securite/detection-intrusion-sans-fil-domotique/detection-mouvements-sans-fil-domotique/1481-sonoff-snzb-03-detecteur-de-mouvements-sans-fil-zigbee-compatible-zigate-conbee2-et-homey.html?search_query=%09SNZB-03&results=179
_Finaly copy-paste all information provided in the log_ 
[pairing.log.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12264142/pairing.log.txt)
[export_non_optimisé.json.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12264143/export_non_optimise.json.txt)
[export.json.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12264144/export.json.txt)

Je suis sur la version du plugin: 7.0.004 [2.80]

**Comment by pipiche38** [comment]
Something missing in the logs and in the pairing information. I cannot do much here.

Can you try to do much pairing, may be pair a router before, and pair the motion via the router

**Comment by rcrocus** [comment]
Hi,
I've paired several times and now it detects the product but with the wrong model : MS01 (Moisture Sensor) instead of SNZB-03 (Motion Sensor)
Which infirmation ar missing during the pairing information ? If I can help or try something let me know.

[export.json.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12301983/export.json.txt)
[pairing.log.txt](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/files/12301984/pairing.log.txt)

**Comment by pipiche38** [comment]
MS01 is a motion sensor from SonOff, so that should be correct. what is wrong ?
This is the zigbee model for "Sonoff SNZB-03 Motion detector",

**Comment by rcrocus** [comment]
Sorry for that. I think the model was wrong but it appears to work well.

**Comment by rcrocus** [comment]
The battery level is bad displayed in domoticz and not displayed in the WEB UI of domoticz-zigbee :
![image](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/assets/94319263/db264be8-81e4-4008-9bcd-a77161905e7a)


![image](https://github.com/zigbeefordomoticz/Domoticz-Zigbee/assets/94319263/403470b6-c74e-4c85-b902-3d3940b0039d)

**Comment by pipiche38** [comment]
should be fixed with [2.86] of Certified modules. You need to leave time to the device to report a battery level and get it analysed by the plugin
