### ISSUE TITLE
failed to load 'plugin.py'

### ISSUE THREAD

**Issue by Jacobsentertainment** [sasu-drooz/Domoticz-Zigate#1650]
Hello all,
I followed the steps as per the instructions for linux Buster. After completing the installation without any error messages, I installed the plugin in domoticz. At the time of adding, the following error comes up. 

` 2023-09-20 10:17:16.799 Error: zigate: (Zigate) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/Domoticz-Zigbee/:/usr/lib/python37.zip:/usr/lib/python3.7:/usr/lib/python3.7/lib-dynload:/usr/local/lib/python3.7/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.7/dist-packages'.
2023-09-20 10:17:16.803 Error: zigate: Traceback (most recent call last):
2023-09-20 10:17:16.803 Error: zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/plugin.py", line 99, in <module>
2023-09-20 10:17:16.803 Error: zigate: from importlib.metadata import version as import_version
2023-09-20 10:17:16.803 Error: zigate: ModuleNotFoundError: No module named 'importlib.metadata' `

I have no idea what is going wrong here and have minimal linux experience. Any help is welcome. 

**To Reproduce**
1. Reinstalled the plugin from scratch
2. Added to domoticz, same error in the domoticz log.
3. Stopped the plugin and removed from the domoticz hardware list, as the errors keep building up. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux VERSION="10 (buster)"
 - Browser firefox
 - Domoticz Version: 2023.2 (build 15555)
Build Hash: 94ed578b5
Compile Date: 2023-09-18 11:18:01
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
Active User: Olaf

**Plugin (please complete the following information):**
 - OS: 
 - Plugin version latest 

**Additional context**

**Comment by pipiche38** [comment]
Unfortunatly buster is not supported with the plugin 7.x, so kindly upgrade to bullseye in order to get python3.8

**Comment by Jacobsentertainment** [comment]
Good to know, thanks for the reply
