### ISSUE TITLE
Problems with pairing a third EcoDim dimmer

### ISSUE THREAD

**Issue by Kareltje2495** [sasu-drooz/Domoticz-Zigate#1667]
Hello

I have a problem connecting an ecoDim.07 dimmer
on my raspberry 4 with sonoff zigbee 3.0 usb dongle plus

I have already linked two of the same dimmers, but the third one is causing problems
I get the following error message

_____________________________________________________________________-
:
Time: "08/11/2023 20:28:35"
Module: "Pairing"
nwkid: "None"
PluginHealth: "Enrollment in Progress"
message: "[6] NEW OBJECT: 7213 Not able to get all needed attributes on time"
PermitToJoin: Object {"Duration":0,"Starttime":1699471662}
Thread: "MainThread"
1:
Time: "08/11/2023 20:28:35"
Module: "Pairing"
nwkid: "None"
PluginHealth: "Enrollment in Progress"
message: "processNotinDB - not able to find response from 7213 stop process at 0045"
PermitToJoin: Object {"Duration":0,"Starttime":1699471662}
Thread: "MainThread"
2:
Time: "08/11/2023 20:28:35"
Module: "Pairing"
nwkid: "None"
PluginHealth: "Busy"
message: "processNotinDB - Collected Infos are : {'Version': '3', 'ZDeviceName': '', 'Status': 'UNKNOW', 'SQN': '', 'Ep': {}, 'Heartbeat': '1', 'RIA': '6', 'LQI': {}, 'Battery': {}, 'Model': '', 'ForceAckCommands': [], 'MacCapa': '8e', 'IEEE': '385cfbfffea392b0', 'Type': {}, 'ProfileID': {}, 'ZDeviceID': {}, 'App Version': '', 'Attributes List': {}, 'DeviceType': 'FFD', 'HW Version': '', 'Last Cmds': [], 'LogicalType': 'Router', 'Manufacturer': '', 'Manufacturer Name': '', 'NbEp': '', 'PowerSource': 'Main', 'ReadAttributes': {}, 'ReceiveOnIdle': '', 'Stack Version': '', 'Stamp': {'time': 1699471713.799074, 'Time': '2023-11-08 20:28:33', 'MsgType': ' 4d', 'LastSeen': 1699471713}, 'ZCL Version': '', 'Health': 'Live', 'Capability': ['Full-Function Device', 'Main Powered', 'Receiver during Idle', 'Standard security', 'NwkAddr should be allocated'], 'ZDPSQN': '06', 'PairingInProgress': True, 'ConsistencyCheck': 'Bad Pairing'}"
PermitToJoin: Object {"Duration":0,"Starttime":1699471662}
Thread: "MainThread"
3:
Time: "08/11/2023 20:28:59"
Module: "Input"
nwkid: "None"
PluginHealth: "Busy"
message: "Decode8045 - KeyError: MsgDataShAddr = 7213"
PermitToJoin: Object {"Duration":0,"Starttime":1699471662}
Thread: "ZigpyForwarder_5"
LastLog: 3
StartTime: "08/11/2023 20:06:28"
FirmwareVersion: "6.10.3.0 build 297"
FirmwareMajorVersion: "98"
PluginVersion: "stable7-7.1.004"

_____________________________________________________________________

This is the raw device log

_____________________________________________________________________
3:
Version: "3"
ZDeviceName: ""
Status: "UNKNOW"
SQN: "00"
Ep: Object {}
Heartbeat: "14"
RIA: "6"
LQI: 112
Battery: Object {}
Model: ""
ForceAckCommands: Array[0] []
MacCapa: "8e"
IEEE: "385cfbfffea392b0"
Type: Object {}
ProfileID: Object {}
ZDeviceID: Object {}
App Version: ""
Attributes List: Object {}
DeviceType: "FFD"
HW Version: ""
Last Cmds: Array[0] []
LogicalType: "Router"
Manufacturer: "126a"
Manufacturer Name: ""
NbEp: ""
PowerSource: "Main"
ReadAttributes: Object {}
ReceiveOnIdle: "On"
Stack Version: ""
Stamp: Object {"time":1699471745.2509403,"Time":"2023-11-08 20:29:05","MsgType":"8011","LastSeen":"08/11/2023 20:29:05"}
ZCL Version: ""
Health: "Live"
Capability: Array[5] ["Full-Function Device","Main Powered","Receiver during Idle","Standard security","NwkAddr should be allocated"]
ZDPSQN: "0a"
PairingInProgress: true
ConsistencyCheck: "Bad Pairing"
ZCL-IN-SQN: Object {"0000":"1a"}
RollingLQI: Array[11] [128,124,124,104,104,100,100,112,112,112,112]
_rawNodeDescriptor: "126a005200522c00008e524001"
Max Buffer Size: "52"
Max Rx: "0052"
Max Tx: "0052"
macapa: "8e"
bitfield: "4001"
server_mask: "2c00"
descriptor_capability: "00"
NwkID: "7213"

_____________________________________________________________________

what can i do to solve this problem?

**Comment by pipiche38** [comment]
Unfortunately I cannot help much on that one. The information provided by the device are not enought.
In short the process is the following:
(1) the device join the Zigbee network - this is ok in your case
(2) the plugin start discovering the device. Like what type of device, what are the functionalities ...

And in this 2nd step the device do not response.

We can do much. May be you should insist (which I guess is what you have done).
