### ISSUE TITLE
the plugin expect unique model definition in DeviceConf.tx

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#168]
In case you have a duplicate entry in DeviceConf.txt, you get such error in the log
Sep 09 10:33:30 pi3 domoticz[7251]: 2018-09-09 10:33:30.107  Error: (Zigate) 'onStart' failed 'SyntaxError'.
Sep 09 10:33:30 pi3 domoticz[7251]: 2018-09-09 10:33:30.107  Error: (Zigate) ----> Line 666 in '/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py', function onStart
Sep 09 10:33:30 pi3 domoticz[7251]: 2018-09-09 10:33:30.107  Error: (Zigate) ----> Line 105 in '/var/lib/domoticz/plugins/Domoticz-Zigate/plugin.py', function onStart
Sep 09 10:33:30 pi3 domoticz[7251]: 2018-09-09 10:33:30.109  Status: ASyncSerial: port open! Baud 115200 0

and it reset the DeviceList.txt

**Comment by Smanar** [comment]
Are you try with 
tuple = json.loads(str)
instead of
tuple_List = eval(str)

**Comment by pipiche38** [comment]
Not a problem
Wont' fix
