### ISSUE TITLE
Extract the manufacturerCode during Pairing process

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#169]
It would be great to get the manufacturerCode during the pairing/creation process and store it for the corresponding device in DeviceOfList and finally in DeviceList.txt

**Comment by Smanar** [comment]
I m justly on it atm. Give me 2/3 days.

**Comment by Smanar** [comment]
Are you sure it s the manufacterer code you want ? 
"IKEA of sweden" for exemple ?

**Comment by pipiche38** [comment]
If this is what we get, I think this is still an important information from the Device to be stored in the plugin dictionary , no ?

**Comment by Smanar** [comment]
As you want, easy to put in place, but we can't display it on domoticz, so it's only for the plugin.
Model/Type is usefull yes, because for exemple for clusters gestion(to differenciate devices) but I don't see where to use manufacture, I think it's more accurate to use model/type instead.

**Comment by pipiche38** [comment]
DOne via Node Descriptor request 0x0042/0x8042 

Implemented during IEEE dev and b46f32f4033d394ad4bd7a6b5d4b041b5257c957
