### ISSUE TITLE
Problem with SNZB-02 sensor

### ISSUE THREAD

**Issue by 0phenix** [sasu-drooz/Domoticz-Zigate#1712]
After upgrading from version stable6-6.3.010 to the latest 7.1.008 (2024.1), the SNZB-02 sensor (https://zigbee.blakadder.com/Sonoff_SNZB-02.html) no longer functions correctly. While pairing the sensor is successful, the plugin no longer captures temperature and humidity readings.

**Comment by pipiche38** [comment]
please kindly use one of the forum for that
