### ISSUE TITLE
Zigbee - lumi.remote.b1acn01_SwitchAQ2WithOff-00158d0001e7a126-01

### ISSUE THREAD

**Issue by Hydci** [sasu-drooz/Domoticz-Zigate#1737]
Bonjour,

J'ai une question avec tout mes boutons xiaomi de type Zigbee - lumi.remote.b1acn01_SwitchAQ2WithOff-00158d0001e7a126-01 dans un dzvent ou lua le One click n'est pas reconnu ou bien même Two click l'orthographe et pourtant bonne quelque choses a changer ? 

Voici le scipt un simple script
return {
    on = { devices = { "Bouton gio" }},
               
    execute = function(dz, item)
        dz.log("Script started for device: " .. item.name .. " with state: " .. item.state, dz.LOG_DEBUG)
        
        if item.state == "1 Click" then
            dz.log("One click detected", dz.LOG_DEBUG)
            local etoile = dz.devices("Plan de travail")
            
            if etoile then
                etoile.toggleSwitch()
                dz.log("Toggled Étoile switch", dz.LOG_DEBUG)
            else
                dz.log("Device Étoile not found", dz.LOG_ERROR)
            end
        else
            dz.log("State is not 'One click'", dz.LOG_DEBUG)
        end
    end
}

**Comment by pipiche38** [comment]
Please kindly use the forum https://easydomoticz.com/forum/viewforum.php?f=28&sid=78651ad9cb4716040dd1f35579a3b63d for such question

the github issue is used for code maintenance

**Comment by Hydci** [comment]
Ce n'est pas un problème de script (j'ai joins pour faire voir qu'elle était l'état utiliser) justement c'est un problème de bouton qui ne rapporte pas le bonne état qu'il devrait faire
