### ISSUE TITLE
TypeFromCluster expect a direct match between clusterID and Type - this wrong

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#175]
TypeFromCluster expects a direct match between ClusterID and Type. 

In reallity Xiaomi is currently using 0x000C for Xcube and for PowerMeters !

**Comment by Smanar** [comment]
Wana use attribute 0010 or 0005 instead ?
Or a better deviceConf.txt file, like previous issue ?

**Comment by pipiche38** [comment]
We should address DeviceConf access and then the function associated.
I'll started drafting some specs, to get discussed
