### ISSUE TITLE
Get support for my NodOn zigbee switch

### ISSUE THREAD

**Issue by Bastien92** [sasu-drooz/Domoticz-Zigate#1767]
Hello,

It seems my NodOn switch is ready for an update. May I ask you to confirm I can update this device without any issue?

Here is the technical information you may need:

{'fileVersion': 66816, 'fileSize': 39456, 'manufacturerCode': 4747, 'imageType': 266, 'sha512': 'd866e1dd0614b33a8d24b0d66228d53f4cca93c26a2613f75dcf73edb311e7bf6e3c791fae93c3b9633a4c40dbb6380aee5e6134fdfb9cee7bce70386fb7eb1d', 'url': 'https://github.com/Koenkk/zigbee-OTA/raw/master/images/NodOn/128b-010A-010500-700_nodon_sin_xx_met_fm_stm32_V010500.zigbee', 'path': 'images/NodOn/128b-010A-010500-700_nodon_sin_xx_met_fm_stm32_V010500.zigbee'}

Thanks for your help!

**Comment by pipiche38** [comment]
For now the support is only on the development branch ( wip-stable7-7.1.13 ), but if you do update this is on your own decision and responsibility.

Kindly use the forum for such question, Your first place to get support is here.

    English channel : https://www.domoticz.com/forum/viewforum.php?f=68
    French Channel : https://easydomoticz.com/forum/viewforum.php?f=28&sid=a8633a9d8cb2acccb32872543b50fd47
