### ISSUE TITLE
Update on windows issue 

### ISSUE THREAD

**Issue by seblang** [sasu-drooz/Domoticz-Zigate#191]
Hello I want to do an update at last version without to lost all my materials but I am under windows. I have done a full copy from zip file but with this solution I have lost all device! What file a have to copy to have the last version and keep all my device? Regards

**Comment by zaraki673** [comment]
Hi, you have to keep your devicelist.txt.
Don't know if it will work without creating new device in Domoticz, for that you have to edit devicelist.txt and replace status ='inDb' with status ='' for all devices

**Comment by pipiche38** [comment]
First , you need to have a backup of the Domoticz database and then the plugin informations as mentionned by @zaraki673 which is the DeviceList.txt

If you have lost all devices, I'm afraid this is more on the Domoticz side, rather than the Zigate plugin one.

**Comment by pipiche38** [comment]
Also , make sure that you have the latest version 3.0.3. We have fixed an issue 2 days ago. And with that fix, if you have the Domoticz database, I guess that you can restart and DeviceLIst.txt will be re-populated .

**Comment by pipiche38** [comment]
@seblang is the problem solved ?

**Comment by pipiche38** [comment]
Please re-open the issue if the problem is still pending
