### ISSUE TITLE
Liste d'appareil compatible zigbee

### ISSUE THREAD

**Issue by Smanar** [sasu-drooz/Domoticz-Zigate#192]
Alexa est maintenant compatible zigbee (le nouvel echo plus) donc il y a moyen d'utiliser le site d'amazon pour trouver des devices compatibles.
Sachant que a mon avis leur appareil ne gerera que les devices les plus simples, donc les moins chiants a integrer
cf https://www.amazon.com/b/ref=hqp_dfs_ods_lr_dp_simplesetup?node=17238426011

Edit:
Version fr https://www.amazon.fr/b?node=15605855031
Bizarrement encore aucun produit inconnu.

**Comment by pipiche38** [comment]
@Smanar merci pour l'information.

Je propose de fermer l'issue, car cela n'en est pas vraiment une ;-)
