### ISSUE TITLE
creating an autonomous version of the plugin (not connected with Domoticz)

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#230]
As the plugin is providing the all Zigate communication Framework it might be interesting to create a special Python main program to be used instead of the Domoticz Python Framework.

This would allow to interact with Zigate in an autonomous way for new device discovery, debuging and/or testing ....

**Comment by dpocock** [comment]
Here is a related idea:
https://github.com/Koenkk/zigbee2mqtt

**Comment by pipiche38** [comment]
> Here is a related idea:
> https://github.com/Koenkk/zigbee2mqtt

I do not see that rational here ! This is an other plugin based on an other ZigBee Hardware.

**Comment by dpocock** [comment]
Being more specific: imagine a zigate2mqtt plugin, so that any application can access the Zigate through MQTT, without Domoticz

```
Zigate USB  --> zigate2mqtt  
                   |
                  broker -->   Domoticz (or other software)
                   |
CC2531 USB  --> zigbee2mqtt 
```

This would be useful for people making bespoke applications.  It would also be a useful way to test the Zigate Python code without running Domoticz.

**Comment by pipiche38** [comment]
Will have to be managed though Project and not issue
