### ISSUE TITLE
Power metering for Salus Plug

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#236]
It requires the implementation of cluster 0x0702 /

need to understand how to decode the MsgClusterData

It might also required to send a ReadAttributeRequest for this Cluster on 0x0000 and 0x0400 attribute

**Comment by pipiche38** [comment]
@deennoo for follow-up

**Comment by deennoo** [comment]
ok thx

**Comment by pipiche38** [comment]
First tentative implemented on dev : b350dd3c1a876821d34ef28000606973e095b0df

**Comment by pipiche38** [comment]
Main issue is to understand which Attribute the salus plug is storing information
 Instantaneous demand
Current Summation Delivered

**Comment by pipiche38** [comment]
ConfigureReporting implemnted let see what is the outcome 38a42a49a5f046e0aeda7539f80adad926032236

**Comment by pipiche38** [comment]
Implementation . Working , but required a firmware update of Zigate in order to handle 24bits
