### ISSUE TITLE
Support for Ikea Tradfri LED1623G12

### ISSUE THREAD

**Issue by gte477k** [sasu-drooz/Domoticz-Zigate#256]
Ikea Tradfir LED1623G12 is one of the nicest G27 light bulps available. It would be great if Domoticzs-Zigate would support this.

**Comment by pipiche38** [comment]
Check : https://github.com/sasu-drooz/Domoticz-Zigate/blob/beta-3.3/Compatible-Hardware.md

**Comment by gte477k** [comment]
Merci, I was on the Master branch, where the bulp was not yet in included. Now I see that it is included in the current beta. I think the Zigbee part of the bulp is not working, as I see no action/no messages at all when I reset the bulp (6x off/on).
