### ISSUE TITLE
No transport, write directive to 'Zigate' ignored.

### ISSUE THREAD

**Issue by hkhk12** [sasu-drooz/Domoticz-Zigate#265]
After some time (think between 6 and 12 hours) looks like the module cannot reach the zigate device anymore.

The errors in domoticz log are:

_No transport, write directive to 'Zigate' ignored._
and
_waitForStatus - Timeout 5 on 0092_

At that stage connected devices can no longer be controlled.

Disabling the plugin and enabling it again solved the issue.

Running version beta-3.3 on a Synology NAS.

Is it possible to disable/enable the plugin via domoticz API so I can schedule that to happen on regular interval.

**Comment by pipiche38** [comment]
Will continue on #267
