### ISSUE TITLE
When there is a buggy PluginConf.txt or DeviceConf.txt it zero's DeviceList

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#267]
A buggy DeviceConf.txt or PluginConf.txt are simply reseting to 0 the DeviceList.txt

Today there is backup of the DeviceList done at each startup, but it would be more convenient to have a much better resilience on DeviceList

**Comment by hkhk12** [comment]
Installed this one but the problem doesn't seem fixed. 
Now it crashes Domoticz instead (but after longer time though)

**Comment by pipiche38** [comment]
@hkhk12 I'm not sure I understand your comment. What is related to this issue ? What did you installed ? If this is not related, could you kindly use the Forum to report the problem first ?

**Comment by pipiche38** [comment]
9a0878f..971874a
