### ISSUE TITLE
Make the Motion Resetdevice customizable

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#270]
Today Reset of Motion device is done after 30s. Depending on the user, some might want to have the reset at 60s .
It would be great to have ResetDevice delay as a PluginConf.txt parameter

**Comment by deennoo** [comment]
Why dont allow use to use native domoticz off After xx seconde.

This option already exist on the widget configuration

**Comment by pipiche38** [comment]
Done in Dev 76912fe6ae43bc1f8a98f59c068b760b7595430f

**Comment by pipiche38** [comment]
> Why dont allow use to use native domoticz off After xx seconde.
> 
> This option already exist on the widget configuration

But unfortunatly Domoticz is not providing that information to the Python Plugin Framework
