### ISSUE TITLE
Update Device Only if needed

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#272]
When recieving a reporting from a bulb, even if the device is already on the same state, the plugin update the status.

If you set a Lua Even Script base on devices status, the script run.

Add an ikea Bulb to the plugin
Turn it Off
and after 1 hour looks at the Logs on Domoticz Device

**Expected behavior**
Update device status only when it's needed

**Screenshots**

2018-12-06 20:44:22 | Off
2018-12-06 20:39:22 | Off
2018-12-06 20:34:22 | Off
2018-12-06 20:29:22 | Off

**Plugin  (please complete the following information):**
 - OS: Debian Stretch
 - Plugin version : 4.0.0 stable 
 - Ikea Bulb : Tradfri 980 lm
 - Domoticz : Version: 4.10256

**Comment by pipiche38** [comment]
In fact this is a bit more tricky and apply for all objects which have configure reporting enabled on clusters 0x0006 and 0x0008 and which are defined in Domoticz in 1 single widget .

The main issue in linked to the fact that Domoticz store On/Off and Level in one single datafield sValue.

So I suspect that you get Off but also Level update and that is where the mix is happening.

**Comment by pipiche38** [comment]
Problem occured only for Color bulb. Fix to be done in UpdateDevice

**Comment by pipiche38** [comment]
Implemented in dev-grpmgt branch
