### ISSUE TITLE
Hue bulbs discovered, but inactive.

### ISSUE THREAD

**Issue by santricity** [sasu-drooz/Domoticz-Zigate#273]
Hi,
I bought Zigate USB stick, successfully installed Zigate Plugin on my Raspberry-Domoticz, added Osram Smart Plug, Ikea Tradfri bulbs and Philips Hue bulbs. 

I can control Osram and Ikea devices, but I can't do anything with Hue bulbs. 

![image](https://user-images.githubusercontent.com/45700421/49674705-33ada080-fa73-11e8-8116-8034d3b69e54.png)

As you can see the RF Signal Level is also missing for Hue bulbs. Bulbs are brand new, never paired with anything else. I assume I don't need to reset them before pairing them with ZiGate/Domoticz? 

Is there a special procedure for pairing Hue bulbs with Zigate/Domoticz?

**Comment by santricity** [comment]
OK, I updated plugin to ver. 4.0.0, removed devices and added them again. Hue bulbs detected, I can turn them on and off and also dim them, but I cant change the color.

![image](https://user-images.githubusercontent.com/45700421/49675863-a6207f80-fa77-11e8-843d-cd9d3d542c41.png)

![image](https://user-images.githubusercontent.com/45700421/49675888-bdf80380-fa77-11e8-9a75-f2d01dfea20b.png)

I can only set the brightness and light temperature.

**Comment by pipiche38** [comment]
From the screenshot you are sharing it looks like the plugin detect the Bulb as a WW bul and not a Full RGB one. Is that correct ?

Could you kindly attached the file DeviceList-xx.txt ?

**Comment by santricity** [comment]
Yes, that is correct, it was discovered as WW only. 

I fixed it by removing all Zigate devices, the Zigate Plugin hardware, the plugin itself from domoticz/plugin directory and installing it again. One Bulb was discovered immediately and properly as RGBWW. 

I'm still trying to discover the second Bulb, but without success. Is there something I can do? Before plugin reinstallation it was discovered but as WW Bulb as well. Now it can't show up in the devices list anymore. 

My latest DeviceList file (one Osram plug and one Hue Bulb discovered):
[DeviceList-7.txt_2018-12-08-21_22_22.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2660028/DeviceList-7.txt_2018-12-08-21_22_22.txt)

![image](https://user-images.githubusercontent.com/45700421/49690434-530b0300-fb31-11e8-9091-a29419b2a41c.png)

**Comment by pipiche38** [comment]
When you say , without success, you mean wrong detection ? WW instead of RGBWW ?
If that is the case, I'll provide you a patch

**Comment by santricity** [comment]
The second one cannot be detected at all - it doesn't show up in the device list. And I think I have the same issue with Ikea bulbs, there are not showing up in the list (I have reset them several times).

**Comment by pipiche38** [comment]
OkI, so that is an other issue. What do you have in the Log when you try to Pair them ?
If you want to chat I'm reachable on keybase.io

**Comment by santricity** [comment]
All fixed with great help of pipiche38! All devices paired with proper Domoticz widgets.

Below my DeviceList file, where device 11ca (one of my Hues in this case) was previously not properly paired and had 'UNKNOW' status:
[DeviceList-7_1.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2660081/DeviceList-7_1.txt)

After deleting this line I was able to pair my missing Hue bulb. Ikea bulbs have been finally paired after several resets (I've reset Ikeas using this method https://www.youtube.com/watch?v=mJm9YpPrGzk).

My final DeviceList file:
[DeviceList-7.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2660082/DeviceList-7.txt)

**Comment by pipiche38** [comment]
@santricity could you kindly let me known what are the following devices:
62a2 (000b57fffe20ba82) which has a Domoticz Color Widget DeviceID: 65 ?
9a52 (000b57fffe117dcf) which has a Domoticz Witch, Color widget DeviceID: 66 ?

Why am I asking that is because there is a strange Model for those 2.

**Comment by santricity** [comment]
These are my two Ikea Tradfri bulbs.

**Comment by pipiche38** [comment]
I'm closing the issue.
