### ISSUE TITLE
Allow the possibility to store report on different/customized folder

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#276]
It would be convenient if the user could configure where the LQI report can be stored

**Comment by zaraki673** [comment]
reports should now be created in [Startup folder]/www/zigate/reports
folder is created by z_WebGui.py when GUI files are copied/updated

**Comment by pipiche38** [comment]
#299

**Comment by pipiche38** [comment]
https://github.com/sasu-drooz/Domoticz-Zigate/wiki/PluginConf

**Comment by pipiche38** [comment]
Here after are the default directories based on pluginHome which is given by the Plugin Framework

```
Plugin Directories
-pluginHome: /var/lib/domoticz/plugins/Domoticz-Zigate/
-pluginData: /var/lib/domoticz/plugins/Domoticz-Zigate/./
-pluginZData: /var/lib/domoticz/plugins/Domoticz-Zigate/./Zdatas/
-pluginReports: /var/lib/domoticz/plugins/Domoticz-Zigate/../../www/templates/zigate/reports/
-pluginConfig: /var/lib/domoticz/plugins/Domoticz-Zigate/./
-pluginWWW: /var/lib/domoticz/plugins/Domoticz-Zigate/../../www/templates/
```

**Comment by pipiche38** [comment]
available on the beta branch.
Closing
