### ISSUE TITLE
Update not done on lumi.sensor_cube

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#281]
Using Xiaomi Cube 1st Gene with 4.0.1 plugin

Rotation isn't always update when last cube status is already Rotation

There is my event : 

si cube = rotation et lumière Off alors lumière On
si cube = rotation et lumière On alors lumière Off

But if cube is already on rotation state, i have to made something else (90° eg) and after rotation.

this can be solve using set to off after 1 sec on device widget but get this answer : 

2018-12-09 11:14:29.027 (Zigate) mgtCommand - Look you are trying to action a non commandable device Device Cube Xiaomi has available Type ['Aqara']

**Comment by pipiche38** [comment]
`2018-12-09 11:14:29.027 (Zigate) mgtCommand - Look you are trying to action a non commandable device Device Cube Xiaomi has available Type ['Aqara']`
This make sense, as this is not an actionable device.

As the rotation event, I'm not able to duplicate the issue, except if I inject a lot of event to the cube, and in that case it is not sending any more event.

**Comment by pipiche38** [comment]
clock and anti-clock has been implemented in dev-grpmgt branch.
I suggest to close and to re-open if problem is poping up again
