### ISSUE TITLE
plugin doesn't display error in UI when permissions problem occurs accessing ttyUSB0

### ISSUE THREAD

**Issue by dpocock** [sasu-drooz/Domoticz-Zigate#296]
**Describe the bug**
Domoticz running as Linux user 'domoticz'
The USB device /dev/ttyUSB0 can only be accessed by users in group 'dialout'
The domoticz user is not in the dialout group.
The permission denied error only appears in the log file and only if it is in debug mode.
It would be desirable to make errors like this more visible in the UI to help first time users start more quickly.

**Comment by pipiche38** [comment]
Please report it to Domoticz, this is not a plugin issue

**Comment by dpocock** [comment]
could you be more specific?  For example, do the Domoticz developers provide an API method for plugins to display errors or is that a missing feature in their API?

**Comment by pipiche38** [comment]
Domoticz API ( especially the Python Plugin Framework provides the API to get access to USB, Serial Line, TCP/IP connections). 

Use the domoticz forum Python group for that

**Comment by pipiche38** [comment]
@dpocock I'm going to close this case as it is a pure Domoticz one.

The Zigate Plugin use the Python Plugin Framework to open outside connection as Serial or TCP/IP.
