### ISSUE TITLE
Make the plugin packageable and get the proper Directory Tree

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#299]
In order to get the plugin in a Debian, Fedora or whaterver distribution packaged, it is important to review the directory structure.

#295

**Comment by pipiche38** [comment]
Here after is what could the Directory tree looks like

Domoticz-Zigate
     - config/PluginConf.txt
     - config/DeviceConf.txt
     - data/DeviceList-xx.txt
     - data/DiscoveryDevice-xxxx.txt
     - reports/LQI-reports-xx.txt
     - reports/Network_scan-xx.txt

Using of configparser module. To validate if this comply with Domoticz python Framework and Windows environment.

[DEFAULT]
pluginHome = './'
pluginData = './data/'
pluginReports = './reports'
pluginConfig = './config'

[GROUPSMANAGEMENT]
enablegroupmanagement = 1
discoverZigateGroups = 1
enableConfigGroups = 1

[NETWORKTOPOLOGY]
enableLQI = 2600
enableSCAN = 3600

[DEBUGING]
debugReadCluster = 1

**Comment by pipiche38** [comment]
https://github.com/sasu-drooz/Domoticz-Zigate/wiki/PluginConf

**Comment by pipiche38** [comment]
@dpocock if you want to try this is on the dev-grpmgt branche

**Comment by pipiche38** [comment]
Feel free to check with the latest dev-grpmgt branch

**Comment by pipiche38** [comment]
Available now on the beta-branch.
Closing this issue

**Comment by dpocock** [comment]
I can probably test this in the next few days, should I just checkout from beta?  Is there anything else I need to be aware of when testing?

I also made a note in the forum about another problem, not receiving values from an Osram Lightify/Smart+ Motion sensor, could you please give me feedback there?  I would like to test that at the same time.
https://www.domoticz.com/forum/viewtopic.php?f=68&t=26559

**Comment by pipiche38** [comment]
Daniel,

Beta is the best place .

Here after is the default setup: 
        self.homedirectory is the Plugin Home directory 

        pluginData = self.pluginHome + './'                                         RW
        pluginZData = self.pluginHome + './Zdatas/'                            RW
        pluginConfig = self.pluginHome + './'                                      RO
        pluginWWW = self.pluginHome + '../../www/templates/'          RW
        pluginReports = self.pluginWWW + 'zigate/reports/'               RW

I suggest to leave pluginConfig to default . Or you will have to move manualy the file DeviceConf.txt

The file PluginConf.txt is expected to be in the Plugin Home directory. So ether you do a Sym Link to the Config directory to access it in order to have the Home readonly.

In any case let me know how it works.

**Comment by dpocock** [comment]
> Daniel,
> 
> Beta is the best place .
> 
> Here after is the default setup:
> self.homedirectory is the Plugin Home directory
> 
> ```
>     pluginData = self.pluginHome + './'                                         RW
>     pluginZData = self.pluginHome + './Zdatas/'                            RW

For a package, those should probably become:
/var/lib/domoticz/plugins/Domoticz-Zigate/
/var/lib/domoticz/plugins/Domoticz-Zigate/Zdatas/

Should I just patch Classes/z_PluginConf.py to override them or do you anticipate having them in a config file?  A config file would be ideal.

Which files does it look for in each location?  Could you possibly include a table in readme.md listing each variable (e.g. pluginData), default location and what is expected to be found there?


>     pluginConfig = self.pluginHome + './'                                      RO

Is that used for both DeviceConf.txt and PluginConf.txt ?


>     pluginWWW = self.pluginHome + '../../www/templates/'          RW

I couldn't see www/templates in the repository, do I need to create that directory during package install?


>     pluginReports = self.pluginWWW + 'zigate/reports/'               RW

That implies pluginReports = self.pluginHome + '../../www/templates/' + 'zigate/reports/'

But the actual location in the repository appears to be self.pluginHome + '../../www/' + 'zigate/reports/'

Can you please confirm if the example is wrong or if the directories in the repository are out of sync?

> 
> 
> I suggest to leave pluginConfig to default . Or you will have to move manualy the file DeviceConf.txt
> 

Does DeviceConf.txt need to be changed at runtime?


> The file PluginConf.txt is expected to be in the Plugin Home directory. So ether you do a Sym Link to the Config directory to access it in order to have the Home readonly.
>

Does PluginConf.txt need to be changed at runtime?

**Comment by pipiche38** [comment]
You should patch the file PluginConf.txt where all those information can be configured

See the Wiki for more information
https://github.com/sasu-drooz/Domoticz-Zigate/wiki/PluginConf

**Comment by pipiche38** [comment]
For information:
https://github.com/sasu-drooz/Domoticz-Zigate/wiki/Plugin-directory-structure

**Comment by pipiche38** [comment]
Done in pre-4.1

**Comment by dpocock** [comment]
@pipiche38 thanks for your efforts on this.

I made a package and pushed it here on the debian/sid branch:
https://gitlab.com/dpocock/domoticz-zigate/tree/debian/sid

You can test it:
```
git clone https://gitlab.com/dpocock/domoticz-zigate
cd domoticz-zigate
git checkout debian/sid
dpkg-buildpackage -rfakeroot -i.git -b
```

I also made an updated version of the domoticz.deb package, it includes patches from the Debian ITP and uses a more recent version of the Domoticz code:
https://gitlab.com/dpocock/domoticz-debian-raspbian/tree/debian/backports/stretch

and it can be built with the same procedure:

```
git clone https://gitlab.com/dpocock/domoticz-debian-raspbian
cd domoticz-debian-raspbian
git checkout debian/backports/stretch
dpkg-buildpackage -rfakeroot -i.git -b
```

I was able to install both packages onto a Debian amd64 system using the following command:

```
dpkg -i domoticz_4.10717-1_amd64.deb domoticz-zigate-plugin_4.3.4-1_amd64.deb
```

and they just work.  I'll make them available in an APT repository for other people to test, along with the packages of the firmware update utilities.

I haven't done a Raspbian build yet.  I was able to build older versions of the package on Raspbian.  I'll provide more feedback after testing that.

**Comment by pipiche38** [comment]
@dpocock Daniel, for your information release 4.5 has been out .
