### ISSUE TITLE
Association OK LOG ok mais pas de nouveau dispositif

### ISSUE THREAD

**Issue by seblang** [sasu-drooz/Domoticz-Zigate#30]
J'ai des périphériques qui communique (d’après les logs) mais aucun nouveau dispositif n'est apparu!
comment résoudre ce problème?
merci

**Comment by zaraki673** [comment]
essaie d appuyer sur le bouton, de maniere a ce que le device se represente à nouveau (pas un appuie long, un simple appuie suffit pour la pluspart)

c'est quoi comme périphériques que tu essaies d'ajouter ?

**Comment by seblang** [comment]
rien n'y fait.
j'ai mis en détection pour ajout nouveau périphérique, relancer le plugin,
associe lorsque la led clignote.......mais je ne vois tjr pas de
périphérique
en revanche les logs montrent que çà communique


​
il faut peut être que je fasse un RAZ de la clef ou je sais pas...

**Comment by zaraki673** [comment]
peut tu m envoyer tes logs 
du demarrage du plugin, jusqu a ce que tu appuies 5 secondes sur le capteur et les trames qui vont suivre

merci

**Comment by zaraki673** [comment]
pas de nouvelles, je clos ;)
