### ISSUE TITLE
Showing Device Zigbee Name instead of IEEE

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#318]
Actually when adding a new device to Zigate Plugin, on device Name Domoticz is Showing IEEE.

Looking at the log, Plugin is now able to get Device Zigbee name :  TRADFRI bulb E27 WS opal 980lm

This can be more user friendly

**Comment by pipiche38** [comment]
This could be indeed a good thing. However if you are in situation where you start adding several Bulb you won't see any differences.

In case we won't have the Name, IEEE/EP remain the best

Last I feel that EP is still important in the context where you have widgets on differents EP

**Comment by pipiche38** [comment]
Link to Friendly name

**Comment by pipiche38** [comment]
Merge on beta 37af966
