### ISSUE TITLE
Wrong Energy counter on Xiaomi smart sockets in Domoticz Utility

### ISSUE THREAD

**Issue by blooesky** [sasu-drooz/Domoticz-Zigate#325]
I tested today Energy counter from my Xiaomi smart sockets...and i saw the counter is not correct in Utility page...but in Utility device **log** is correct energy counter. Please check!
![domoticz2](https://user-images.githubusercontent.com/7414312/51272631-45b82280-19d3-11e9-8a56-8a5db67bd6ad.jpg)

**Plugin (please complete the following information):**
 - Raspberry Pi with Raspbian
 - Domoticz-Zigate 4.0.7

**Comment by pipiche38** [comment]
As you wrote the data are correct in the DEVICE Log which means that the information send from the plugin to Domoticz are correct.

I'm having similar behaviour with a Salus Plug

Will see how to report that issue to Domoticz

**Comment by pipiche38** [comment]
@blooesky , could you kindly do a git pull from Beta branch and check ?

**Comment by pipiche38** [comment]
Works for me on beta with Xiaomi and Salus Plug

**Comment by pipiche38** [comment]
[plugin.py.zip](https://github.com/sasu-drooz/Domoticz-Zigate/files/2840148/plugin.py.zip)



Here is a plugin to reproduce what is done by the plugin and i see a similar behaviour as the one reported.

Suggest that you post it to the Domoticz forum ...
