### ISSUE TITLE
Innr BY 265-2

### ISSUE THREAD

**Issue by petitPoulpe** [sasu-drooz/Domoticz-Zigate#332]
Hello,
I have this product and it is compatible with Zigate plugin :
https://www.amazon.fr/gp/product/B07H5S7JV5/ref=ppx_yo_dt_b_asin_title_o09__o00_s00?ie=UTF8&psc=1

In Domoticz, it creates two devices but just one seems to respond.

**Comment by pipiche38** [comment]
Could you kindly let me know what are the 2 widgets created ?
Would appreciate if you could attached the DeviceList-xx.txt file so I can get more information on the device, and maybe avoid the 2nd widget

Patrick

**Comment by petitPoulpe** [comment]
6ce4 : {'ProfileID': '0104', 'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f01', 'IEEE': '00158d0001b97dee', 'RIA': '1', 'RSSI': 105, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548871429, '01-0006': 1548871293}, 'Ep': {'01': {'0000': {'0005': '00', '0000': '00', '0001': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 19:03:49', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'99': 'Switch'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'Heartbeat': '445277', 'SQN': '7c'}
71c0 : {'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'IEEE': '00158d0002772a67', 'RIA': '0', 'Stamp': {'Time': '2019-01-26 16:01:41', 'MsgType': '8102'}, 'LogicalType': 'End Device', 'Ep': {'01': {'0402': 17.8, 'Type': 'Temp/Humi/Baro', 'ClusterType': {'90': 'Temp', '89': 'Temp+Hum', '92': 'Baro', '88': 'Temp+Hum+Baro', '91': 'Humi'}, '0000': {}, '0003': {}, '0405': 55.6, '0403': 995.9, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'ReceiveOnIdle': 'Off', 'DeviceType': 'RFD', 'SQN': '5b', 'ProfileID': '0104', 'Manufacturer': '1037', 'PowerSource': 'Battery', 'ZDeviceID': '5f01', 'RSSI': 54, 'ReadAttributes': {'TimeStamps': {'01-0000': 1547489049}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}}}}, 'NbEp': '1', 'Model': 'lumi.weather', 'Heartbeat': '445271'}
8e8b : {'ProfileID': '0104', 'App Version': '2', 'Type': 'LvlControl/Switch/', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '000c', 'IEEE': '0017880104ef3a9e', 'RIA': '0', 'RSSI': 69, 'ReadAttributes': {'TimeStamps': {'02-0001': 1548833900, '02-0000': 1547391196, '01-0006': 1548149034, '01-0000': 1548497359, '01-0008': 1548149034}, 'Ep': {'02': {'0000': {}, '0001': {'0020': '00', '0021': '00', '0010': '86', '0000': '86'}}, '01': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0001': {}, '0006': {'0000': '86'}, '0008': {'0000': '86'}}}}, 'Stamp': {'Time': '2019-01-27 08:37:33', 'MsgType': '8102'}, 'NbEp': '2', 'Model': 'RWL021', 'Ep': {'02': {'0001': '0;0;28;200', '0019': {}, 'ClusterType': {'104': 'LvlControl'}, '0000': {}, '0003': {}, 'fc00': {}, '000f': {}}, '01': {'0005': {}, '0006': {}, '0004': {}, 'ClusterType': {'103': 'LvlControl'}, '0000': {}, '0003': {}, '0008': {}}}, 'MacCapa': '80', 'GroupMgt': {'01': {'0014': {'Phase': 'TimeOut', 'Phase-Stamp': 1548869703}}}, 'Battery': 200, 'Heartbeat': '63483', 'HW Version': '1', 'Stack Version': '1', 'SQN': '00'}
cc19 : {'App Version': '12', 'Type': 'Switch/', 'Status': 'inDB', 'Version': '3', 'Stack Version': '2', 'IEEE': '7cb03eaa00b21e26', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:03:03', 'MsgType': '8102'}, 'LogicalType': 'Router', 'Ep': {'03': {'0005': {}, '0006': '01', '0004': {}, 'ClusterType': {'87': 'Switch'}, '0000': {}, '0003': {}, 'fc0f': {}, '1000': {}, '0b04': {}}}, 'MacCapa': '8e', 'Battery': {}, 'HW Version': '1', 'ReceiveOnIdle': 'On', 'ConfigureReporting': {'TimeStamps': {'03-0000': 0, '03-0006': 1548791001, '03-0005': 0, '03-1000': 0, '03-0b04': 0, '03-fc0f': 0, '03-0003': 0}, 'Ep': {'03': {'0005': {}, '0006': '00', '0004': '', '0000': {}, '0003': {}, 'fc0f': {}, '1000': {}, '0b04': {}}}}, 'DeviceType': 'FFD', 'SQN': {}, 'ProfileID': 'c05e', 'Manufacturer': 'bbaa', 'PowerSource': 'Main', 'ZDeviceID': '0010', 'GroupMgt': {'03': {'0014': {'Phase': 'OK-Membership', 'Phase-Stamp': 0}}}, 'RSSI': 150, 'ReadAttributes': {'TimeStamps': {'03-0000': 1548832510, '03-0006': 1548871298}, 'Ep': {'01': {'0000': {}, '0001': {}}, '03': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0006': {'0000': '00'}}}}, 'NbEp': '1', 'Model': 'Plug 01', 'Heartbeat': '3016'}
eb85 : {'App Version': '12', 'Type': 'Switch/', 'Status': 'inDB', 'Version': '3', 'Stack Version': '2', 'IEEE': '84182600001009c2', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:02:29', 'MsgType': '8102'}, 'LogicalType': 'Router', 'Ep': {'03': {'0005': {}, '0006': '01', '0004': {}, 'ClusterType': {'85': 'Switch'}, '0000': {}, '0003': {}, 'fc0f': {}, '1000': {}, '0b04': {}}}, 'MacCapa': '8e', 'Battery': {}, 'HW Version': '1', 'ReceiveOnIdle': 'On', 'ConfigureReporting': {'TimeStamps': {'03-0000': 0, '03-0006': 1548790881, '03-0005': 0, '03-1000': 0, '03-0b04': 0, '03-fc0f': 0, '03-0003': 0}, 'Ep': {'03': {'0005': {}, '0006': '00', '0004': '', '0000': {}, '0003': {}, 'fc0f': {}, '1000': {}, '0b04': {}}}}, 'DeviceType': 'FFD', 'SQN': {}, 'ProfileID': 'c05e', 'Manufacturer': 'bbaa', 'PowerSource': 'Main', 'ZDeviceID': '0010', 'GroupMgt': {'03': {}}, 'RSSI': 150, 'ReadAttributes': {'TimeStamps': {'03-0000': 1548833165, '03-0006': 1548871348}, 'Ep': {'01': {'0000': {}, '0001': {}}, '03': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0006': {'0000': '00'}}}}, 'NbEp': '1', 'Model': 'Plug 01', 'Heartbeat': '3018'}
768a : {'ProfileID': '0104', 'App Version': '5', 'Type': 'Aqara', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f03', 'IEEE': '00158d0002564bdc', 'RIA': '0', 'RSSI': 111, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548842507}, 'Ep': {'01': {'0000': {'0005': '00', '0000': '00', '0001': '00', 'ff01': '86'}, '0001': {}}}}, 'Stamp': {'Time': '2019-01-30 18:58:22', 'MsgType': '8102'}, 'NbEp': '3', 'Model': 'lumi.sensor_cube.aqgl01', 'Ep': {'02': {'0012': '0002'}, '01': {'ClusterType': {'106': 'XCube'}, '000c': {}, '0012': {}, '0000': {}}, '03': {'ClusterType': {'105': 'XCube'}, '0005': {}, '0003': {}, '0004': {}, '000c': '80'}}, 'MacCapa': '80', 'Battery': 90, 'Heartbeat': '445275', 'SQN': 'ba'}
1378 : {'ProfileID': {}, 'App Version': '3', 'Type': 'SwitchAQ2', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': {}, 'IEEE': '00158d0002135080', 'RIA': '0', 'RSSI': 141, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548845167, '01-0006': 1548372526}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '86'}}}}, 'Stamp': {'Time': '2019-01-30 11:46:08', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_switch.aq2', 'Ep': {'01': {'ClusterType': {'105': 'SwitchAQ2'}, '0000': {}, '0006': '01'}}, 'MacCapa': '80', 'Battery': 90, 'Heartbeat': '445278', 'SQN': 'fb'}
4d9c : {'ProfileID': '0104', 'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f01', 'IEEE': '00158d0001de61e9', 'RIA': '0', 'RSSI': 153, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548845339, '01-0006': 1548871378}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 19:05:05', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'101': 'Door'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 90, 'Heartbeat': '445272', 'SQN': '48'}
779c : {'ProfileID': {}, 'App Version': '10', 'Type': 'SwitchAQ2', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': {}, 'IEEE': '00158d0001e18d4f', 'RIA': '0', 'RSSI': 84, 'ReadAttributes': {'TimeStamps': {'01-0000': 1547411012, '01-0006': 1548871343}, 'Ep': {'01': {'0000': {'0005': '00', '0001': '00', 'ff02': '00'}, '0006': {'0000': '00', '8000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 18:51:09', 'MsgType': '8102'}, 'Model': 'lumi.sensor_switch', 'Ep': {'01': {'ClusterType': {'106': 'SwitchAQ2'}, '0000': {}, '0006': '03'}}, 'MacCapa': '80', 'Battery': {}, 'Heartbeat': '158749', 'SQN': '00'}
bd30 : {'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'IEEE': '00158d0001e41cd8', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:05:16', 'MsgType': '8102'}, 'LogicalType': 'End Device', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'102': 'Door'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'ReceiveOnIdle': 'Off', 'DeviceType': 'RFD', 'SQN': '80', 'ProfileID': '0104', 'Manufacturer': '1037', 'PowerSource': 'Battery', 'ZDeviceID': '5f01', 'RSSI': 105, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548871515}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}}}}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Heartbeat': '445278'}
b008 : {'App Version': '16', 'Type': 'Switch/LvlControl', 'Status': 'inDB', 'Version': '3', 'Stack Version': '21', 'IEEE': '00158d0001d0c731', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:05:28', 'MsgType': '8102'}, 'LogicalType': 'Router', 'Ep': {'01': {'0005': {}, '0006': '00', '0004': {}, 'ClusterType': {'95': 'LvlControl'}, '0000': {}, '0003': {}, '0008': 'fe', '1000': {}}, 'f2': {'ClusterType': {'96': 'LvlControl'}, '0100': {}}}, 'MacCapa': '8e', 'Battery': {}, 'HW Version': '1', 'ReceiveOnIdle': 'On', 'ConfigureReporting': {'TimeStamps': {'01-0006': 1548790821, '01-0005': 0, '01-0008': 1548790881, '01-0000': 0, '01-0003': 0, 'f2-0100': 0, '01-1000': 0, '01-0004': 0}, 'Ep': {'01': {'0005': {}, '0006': '00', '0004': {}, '0000': {}, '0003': {}, '0008': '00', '1000': {}}, 'f2': {'0100': {}}}}, 'DeviceType': 'FFD', 'SQN': {}, 'ProfileID': 'a1e0', 'Manufacturer': '1166', 'PowerSource': 'Main', 'ZDeviceID': '0061', 'GroupMgt': {'01': {}}, 'RSSI': 108, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548833370, '01-0006': 1548871338, '01-0008': 1548871338}, 'Ep': {'01': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0001': {}, '0006': {'0000': '00'}, '0008': {'0000': '00'}}}}, 'NbEp': '2', 'Model': 'BY 265', 'Heartbeat': '31'}
0807 : {'App Version': '12', 'Type': 'Switch/', 'Status': 'inDB', 'Version': '3', 'Stack Version': '2', 'IEEE': '84182600000fefe0', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:03:26', 'MsgType': '8102'}, 'LogicalType': 'Router', 'Ep': {'03': {'0005': {}, '0006': '01', '0004': {}, 'ClusterType': {'86': 'Switch'}, '0000': {}, '0003': {}, 'fc0f': {}, '1000': {}, '0b04': {}}}, 'MacCapa': '8e', 'Battery': {}, 'HW Version': '1', 'ReceiveOnIdle': 'On', 'ConfigureReporting': {'TimeStamps': {'03-0004': 0, '03-0000': 0, '03-0006': 1548790941, '03-0005': 0, '03-1000': 0, '03-0b04': 0, '03-fc0f': 0}, 'Ep': {'03': {'0005': {}, '0006': '00', '0004': {}, '0000': {}, '0003': '', 'fc0f': {}, '1000': {}, '0b04': {}}}}, 'DeviceType': 'FFD', 'SQN': {}, 'ProfileID': 'c05e', 'Manufacturer': 'bbaa', 'PowerSource': 'Main', 'ZDeviceID': '0010', 'GroupMgt': {'03': {'0014': {'Phase': 'OK-Membership', 'Phase-Stamp': 0}}}, 'RSSI': 69, 'ReadAttributes': {'TimeStamps': {'03-0000': 1548832510, '03-0006': 1548871298}, 'Ep': {'01': {'0000': {}, '0001': {}}, '03': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0006': {'0000': '00'}}}}, 'NbEp': '1', 'Model': 'Plug 01', 'Heartbeat': '3016'}
ad2c : {'App Version': '16', 'Type': 'Switch/LvlControl', 'Status': 'inDB', 'Version': '3', 'Stack Version': '21', 'IEEE': '00158d0001d0c5b9', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:06:01', 'MsgType': '8102'}, 'LogicalType': 'Router', 'Ep': {'01': {'0005': {}, '0006': '00', '0004': {}, 'ClusterType': {'78': 'LvlControl'}, '0000': {}, '0003': {}, '0008': 'fe', '1000': {}}, 'f2': {'ClusterType': {'79': 'LvlControl'}, '0100': {}}}, 'MacCapa': '8e', 'Battery': {}, 'HW Version': '1', 'ReceiveOnIdle': 'On', 'ConfigureReporting': {'TimeStamps': {'01-0006': 1548790941, '01-0005': 0, '01-0008': 1548791001, '01-0000': 0, 'f2-0100': 0, '01-1000': 0, '01-0004': 0}, 'Ep': {'01': {'0005': {}, '0006': '00', '0004': {}, '0000': {}, '0003': '', '0008': '00', '1000': {}}, 'f2': {'0100': {}}}}, 'DeviceType': 'FFD', 'SQN': {}, 'ProfileID': 'a1e0', 'Manufacturer': '1166', 'PowerSource': 'Main', 'ZDeviceID': '0061', 'GroupMgt': {'01': {}}, 'RSSI': 150, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548833370, '01-0006': 1548871338, '01-0008': 1548871338}, 'Ep': {'01': {'0000': {'0005': '00', '0001': '00', 'ff01': '86', '0002': '00', '0010': '86', '0000': '00', '0007': '00', '0004': '00', '0003': '00'}, '0001': {}, '0006': {'0000': '00'}, '0008': {'0000': '00'}}}}, 'NbEp': '2', 'Model': 'BY 265', 'Heartbeat': '31'}
08aa : {'App Version': '5', 'Type': 'Motion/Lux', 'Status': 'inDB', 'Version': '3', 'IEEE': '00158d00022514ec', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 19:04:28', 'MsgType': '8102'}, 'LogicalType': 'End Device', 'Ep': {'01': {'0001': {}, 'ffff': {}, '0500': {}, '0406': '01', 'ClusterType': {'94': 'Lux', '93': 'Motion'}, '0000': {}, '0003': {}, '0006': '00', '0400': 7}}, 'MacCapa': '80', 'Battery': 91, 'ReceiveOnIdle': 'Off', 'DeviceType': 'RFD', 'SQN': '6f', 'ProfileID': '0104', 'Manufacturer': '1037', 'PowerSource': 'Battery', 'ZDeviceID': '0107', 'RSSI': 102, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548845732, '01-0001': 1548833925}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '00'}, '0001': {}}}}, 'NbEp': '1', 'Model': 'lumi.sensor_motion.aq2', 'Heartbeat': '445270'}
e9d8 : {'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'IEEE': '00158d0001b95d5a', 'RIA': '0', 'Stamp': {'Time': '2019-01-30 18:53:15', 'MsgType': '8102'}, 'LogicalType': 'End Device', 'Ep': {'01': {'0402': 17.5, 'Type': 'Temp/Humi/Baro', 'ClusterType': {'81': 'Temp+Hum', '83': 'Humi', '80': 'Temp+Hum+Baro', '82': 'Temp', '84': 'Baro'}, '0000': {}, '0003': {}, '0405': 47.2, '0403': 981.2, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 90, 'ReceiveOnIdle': 'Off', 'DeviceType': 'RFD', 'SQN': 'df', 'ProfileID': '0104', 'Manufacturer': '1037', 'PowerSource': 'Battery', 'ZDeviceID': '5f01', 'RSSI': 117, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548870308}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}}}}, 'NbEp': '1', 'Model': 'lumi.weather', 'Heartbeat': '445271'}
55b5 : {'ProfileID': '0104', 'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f01', 'IEEE': '00158d0001b70559', 'RIA': '0', 'RSSI': 105, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548871478, '01-0006': 1548871368}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 19:04:39', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'100': 'Door'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'Heartbeat': '445280', 'SQN': '7f'}
2a83 : {'ProfileID': '0104', 'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f01', 'IEEE': '00158d0001de5d75', 'RIA': '0', 'RSSI': 102, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548871352, '01-0006': 1548871388}, 'Ep': {'01': {'0000': {'0005': '00', '0000': '00', '0001': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 19:02:33', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'97': 'Door'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'Heartbeat': '445282', 'SQN': '00'}
3760 : {'ProfileID': '0104', 'App Version': '3', 'Type': '', 'Status': 'inDB', 'Version': '3', 'ZDeviceID': '5f01', 'IEEE': '00158d0001b7ac01', 'RIA': '0', 'RSSI': 150, 'ReadAttributes': {'TimeStamps': {'01-0000': 1548871389, '01-0006': 1548871388}, 'Ep': {'01': {'0000': {'0000': '00', 'ff01': '86'}, '0001': {}, '0006': {'0000': '00'}}}}, 'Stamp': {'Time': '2019-01-30 19:03:10', 'MsgType': '8102'}, 'NbEp': '1', 'Model': 'lumi.sensor_magnet.aq2', 'Ep': {'01': {'0006': '00', 'Type': 'Door', 'ClusterType': {'98': 'Door'}, '0000': {}, '0003': {}, 'ffff': {}}}, 'MacCapa': '80', 'Battery': 91, 'Heartbeat': '445270', 'SQN': '79'}
0000 : {'IEEE': '00158d0001edb760', 'Ep': {'01': {'0006': {}, '0004': {}, '0008': {}}}, 'PowerSource': 'Main'}

**Comment by petitPoulpe** [comment]
The two widgets are Dimmer

**Comment by pipiche38** [comment]
@petitPoulpe would it be possible to know what is : 

- device 8e8b ( IEEE 0017880104ef3a9e ) There are 2 Devices in domoticz Idx 103 and 104. Most-likely only 103 works.
- device b008 and ad2c are I believe the BY bulb.

For all what version of the plugin did you use when pairing those devices ?

**Comment by petitPoulpe** [comment]
device 8e8b is Philips Hue remote control, this devices not seem to work.
yes  device b008 and ad2c are 'Model': 'BY 265'
All this devices have been paired with beta plugin.

**Comment by pipiche38** [comment]
Are you using the standard DeviceConf.txt , or did you create/update it ?

**Comment by petitPoulpe** [comment]
i  use the Standard DeviceConf.txt

**Comment by pipiche38** [comment]
Bug found. Fix in progress

**Comment by petitPoulpe** [comment]
Great !! Thank you

**Comment by pipiche38** [comment]
Fix in beta branch f9864c1

**Comment by petitPoulpe** [comment]
How can i test it ?

**Comment by pipiche38** [comment]
You should update to the latest version of beta, remove the 2 devices and then re-do the pairing

**Comment by pipiche38** [comment]
Could you let me know if you have been able to validate the fact that only one device is created now ?

**Comment by petitPoulpe** [comment]
It works ! Thank You
