### ISSUE TITLE
hue bulb

### ISSUE THREAD

**Issue by ben33880** [sasu-drooz/Domoticz-Zigate#333]
hi,
hue bulb and lightstrip are recognized as WW Color switch, not as RGBWWZ.
can u do something ??

thanks.

**Comment by ben33880** [comment]
[DeviceList-35.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2814507/DeviceList-35.txt)

**Comment by pipiche38** [comment]
Before opening an issue, it would be great to qualify if that is an issue via the forum.

You are droping a bunch of data in the DeviceList-35.txt. Thanks to provide some insights

Logs when creating the device 
Version of the plugin

**Comment by ben33880** [comment]
ok sorry, what forum ?
last beta version 4.1 beta
firm 3.0e

les logs dans le fichier joint.
[1.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2818838/1.txt)

thanks

**Comment by ben33880** [comment]
ok, by editing the following line in the file DeviceConf.txt, the LCT007 hue works in RGBWW.

on the other hand, how should I do for the other models in the Hue range?
must we create a new line for each generation of the Hue range?

'Ampoule.phillips.hue':{'Ep':{'0b':{'0000':'','0003':'','0004':'','0005':'','0006':'','0008':'','0300':'','fc01':'','1000':'','Type':'ColorControl','ColorMode':'2'}},'Type':'','ProfileID':'c05e','ZDeviceID':'0210'},

**Comment by pipiche38** [comment]
You can create in DeviceConf.txt a line by Model as you did. So if you are able to identify the model of the others LCT007, LST002

We know that we have to rebuild the management of widget creation for Lights/bulb #326

**Comment by ben33880** [comment]
finally the modification in the file DeviceConf does not work !!!! I had to modify the code to include the Hue correctly.
I do not know the python or the protocol, it's only a phony patch !!

https://github.com/ben33880/Domoticz-Zigate/blame/f68f4156faa32833ac7ba641ee8d18dd026499f9/Modules/z_domoticz.py#L482

les hue ont 2 EP, les zdeviceid et profileid prennent les valeurs du EP 2 : 'f2'  -> a1e0 et 0061 mais ceux qui permettent de créer le bon device sont sur le EP 1 : '0b' -> c05e et 0210

**Comment by pipiche38** [comment]
Thanks for the path. 

I have pushed an update on beta branch . If you want to try

**Comment by pipiche38** [comment]
@ben33880 if you want to chat , you can reach me on keybase.io (we could continue in french)

**Comment by ben33880** [comment]
yes it's cool, thank you very much hue bulb LCT007 and strip LST002 works now.

firm 3.0f
beta plugin 4.1.x

ps: i have another hue bulb but cant test now. i close this issue when tested.

**Comment by ben33880** [comment]
for LCT001, i must insert new line DeviceConf.txt with this  : 
'LCT001':{'Ep':{'0b':{'0000':'','0003':'','0004':'','0005':'','0006':'','0008':'','0300':'','fc01':'','1000':'','Type':'ColorControl','ColorMode':'2'}},'Type':'','ProfileID':'c05e','ZDeviceID':'0210'},

**Comment by pipiche38** [comment]
Integrated into DeviceCOnf.txt beta : b1373b490c17a2916b5edacc3f0e0e3a9cf6ecad

**Comment by ben33880** [comment]
thanks.
now Hue LCT007, LCT001, LST002 works nice.
i only have this one, u can close if u want.

**Comment by pipiche38** [comment]
thanks
