### ISSUE TITLE
Livolo 2 Gang Switch Zigbee

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#337]
Hey guys ! 

I just get a livolo 2 Gang Zigbee switch : https://fr.aliexpress.com/item/Livolo-APP-Touch-Control-Interrupteur-Zigbee-WiFi-Domotique-Intelligent-T-l-commande-Travail-avec-Echo-seulement/32918552579.html?spm=a2g0s.9042311.0.0.40696c3745S41u

Working on channel 26 only

Some dev are done on Zigbee2mqtt : https://github.com/Koenkk/zigbee2mqtt/issues/592

Device discovering frame can be found here : 

https://drive.google.com/open?id=1cfGdCO45b0WEtQzfln2wrZz0uqm6PgEL

**Comment by pipiche38** [comment]
I suggest that you start with ZGUI in order to see if the Zigate is able to retreive all necessary information.
From what I see iun the Discovery Frame:
EndPoint: 06

Last the Log of the all Discovery process from Device Announce to TimeOut would be helpfull.

**Comment by pipiche38** [comment]
In summary:
- Comunication with the Device is Ok. This mean Zigate talk to Livolo on channel 26 back and forth

From the Disocvery Frame:
"8043": {"06": "1b00ef750e0601040000000200000003010006"}, 
        SQN: 1b
        Status: 00
        NwkID: ef75
        Len: 0e
        EP: 06
        Profile: 0104
        DeviceId: 0000
        BitField: 00
        ClusterIn:      02
              0000
              0003
       ClusterOut: 01
             0006
"ZDeviceID": {"0000": "06"}, 
"ProfileID": {"0104": "06"}}

**Comment by pipiche38** [comment]
Bug found, in the Decode8043 - fix to follow

**Comment by pipiche38** [comment]
Fix: 0dc9067..239add0
New json format for the discovery ...

**Comment by deennoo** [comment]
here is some input from ZWGUI : 

premiere connection : 

```
Type: 0x004D (End Device Announce)
  Short Address: 0x283D
  Extended Address: 0x124B0018015B39
  MAC Capability: 0x80
    Alternate PAN Coordinator: False
    Device Type: End Device
    Power Source: Battery
    Receiver On When Idle: False
    Security Capability: Standard
    Allocate Address: True
Type: 0x004D (End Device Announce)
  Short Address: 0x283D
  Extended Address: 0x124B0018015B39
  MAC Capability: 0x80
    Alternate PAN Coordinator: False
    Device Type: End Device
    Power Source: Battery
    Receiver On When Idle: False
    Security Capability: Standard
    Allocate Address: True
Type: 0x8701 (Route Discovery Confirm)
  SQN: 0x00
  Status: 0x00
  Network Status: 0x00
```

  
EP Request : 
```
[Type: 0x8000 (Status)
  Length: 5
  Status: 0x00 (Success)
  SQN: 0x24
  Message: 
Type: 0x8045 (Active Endpoints Response)
  SQN: 0x24
  Status: 0x00
  Short Address: 0x283D
  Endpoint Count: 1
  Endpoint List: 
    Endpoint 0: 0x06](url)
```
	
	
Cluster Request : 
  ```
EndPoint: 0x06
  Profile ID: 0x0104 (ZigBee HA)
  Device ID: 0x0000 (Generic - On/Off Switch)
  Input Cluster Count: 2
    Cluster 0:  Cluster ID: 0x0000 (General: Basic)
    Cluster 1:  Cluster ID: 0x0003 (General: Identify)
  Output Cluster Count: 1
    Cluster 0:  Cluster ID: 0x0006 (General: On/Off)
```
Clearly End Point and Cluster request aren't good as this is a 2 gang device.

After Pairing, nothing comefrom the device to the zigate when switching on/off each relay.

Device doesn't react from ZGWUI solicitations : 
- ON/Off
- Identify

**Comment by deennoo** [comment]
Thx to @KiwiHC16 and https://github.com/KiwiHC16/Abeille/issues/570

Who give a full detailled information about how to drive Livolo Switch.

**Comment by pipiche38** [comment]
With ZGUI can you get the Attribute of the Device ?
- Read Attribute on Device, Ep: 06, Cluster 0x0006 and Attribute 0x0000

With ZGUI did you try to send Level Control (as mentioned in the Abeille subject)
Level: 108, Level: 1, 

Can you also post the latest discovery file (which is now Json format).

**Comment by deennoo** [comment]
Yes i manage to Drive it sending 108/1 or 108/2 or 1/1 or 1/2.

This Works fine.

I have to manage how to set Infinite permit join, because when this end, Switch is out.

I have to get some help to trying to configure reporting

**Comment by pipiche38** [comment]
108 On
1 Off
Gauche : Timing 1
Droit: Timing 2

**Comment by pipiche38** [comment]
Here is what I suggest for the widget side:
- Switch Selector ( like we do for the Xiaomi ). With 
Left On
Left Off
Right On
Right Off

Just need to get the Disocvery file to see how we can identify this . Especially is there a Model name

**Comment by deennoo** [comment]
Ok for selector, 

Even better if this can be a separate on/off switch as we all ready do for xiaomi double switch : This switch is plug to a real bulb, put it on a Plan will show a selector instead of a switch, of course we can make a dummy on/off switch for each side but that a trick.

You can get device discovery here : https://drive.google.com/open?id=1hAMvEm4w8-7c7Icb_58OT98eUnPh9eoX

After setting domoticz on Inclusion On :  

- On/Off widget is created
- This on/off widget can drive L1 who is the left Button when on in front off the switch

On the log : 
`
2019-02-16 05:44:47.112 (Zigate) livolo_OnOff - Level: 01, Timing: 0001

2019-02-16 05:44:47.112 (Zigate) UpdateDevice - (Zigate - Switch-00124b0018015b39-06) 0:Off

2019-02-16 05:44:47.093 Status: User: Admin initiated a switch command (10162/Zigate - Switch-00124b0018015b39-06/Off)


2019-02-16 05:44:49.470 (Zigate) livolo_OnOff - Level: 6c, Timing: 0001

2019-02-16 05:44:49.470 (Zigate) UpdateDevice - (Zigate - Switch-00124b0018015b39-06) 1:On

2019-02-16 05:44:49.451 Status: User: Admin initiated a switch command (10162/Zigate - Switch-00124b0018015b39-06/On)`

When drive the switch manualy : Domoticz Widget isn't update, maybe there is way to configure autoreporte ?

**Comment by deennoo** [comment]
After Testing this morning version : 

This switch doesn't work any more : 

Widget is created as a simple ON/OFF (Not a selector One), trying to activate it doesn't give any output as the previous version on the log and it doesn't work.

**Comment by pipiche38** [comment]
Please provide Logs in order to understand what happen ... Without it is really hard to see

**Comment by deennoo** [comment]
Tested with last pre 4.1 version.

Plugin create 2 Widgets : 
Zigate - LivoloSWL-00124b0018015b39-06
Zigate - LivoloSWR-00124b0018015b39-06

Those widget are working.

Now i'm facing to a loosing connection issue : 

After Pairing and Adding Livolo stop working a few minutes after, this is very similar to what is provied on this issue on Abeille : 

"There is a difference in the switch behaviour that depends on coordinator. The switch always sends 'Data request' commands 3-4 times per second (!!!). If there is no answer even for less than a second the switch sends 'Orphan Notification' then 'Beacon Requests'. If it is paired with original livolo gateway, it's ok, it sends these requests as long as it's necessary, but if it is custom coordinator the switch stops working after a second, and there is only one way to make it work again, it's touch the sensor for 5 secs or power it off then on. So, my switch works fine as long as the connection is perfect, in other way it stops working after some time."

and this one on Zigbee2Mqtt : https://github.com/Koenkk/zigbee2mqtt/issues/592

**Comment by pipiche38** [comment]
Dedicated branch ( git checkout livolo )

**Comment by pipiche38** [comment]
I suggest to park this issue, until Zigate is able to handle it.
Close for now and we will re-open when compatible/managed by Zigate

**Comment by pipiche38** [comment]
To be work on.

**Comment by pipiche38** [comment]
Akila referring that Livolo will be supported on 3.1b ( https://zigate.fr/forum/topic/livolo-compatible-zigbee/#postid-596 )

**Comment by pipiche38** [comment]
In order to force the Extebded PanID
Conf/PluginConf-xx.txt
  "extendedPANID": 5149013381575969,

 Status: (Zigate) Network state UP, PANID: 1fb8 extPANID: 0x00124b00198d7521 Channel: 26

Permit to Join must be always on, as after an electric PowerOff, Livolo restart the Pairing process

**Comment by KiwiHC16** [comment]
Salut
There is no need to force the PanId with mine.

**Comment by pipiche38** [comment]
@KiwiHC16 

> 
> Salut
> There is no need to force the PanId with mine.

Fine for you, anyway I saw quiet a lot of changes done by Akila on the Firmware for 3.1b,

**Comment by KiwiHC16** [comment]
Salut,

Oui suite à ma demande.

Mais ces changement ne changent rien sur le fonctionnement de base de la 
zigate et le fait qu'il n'est pas nécessaire de forcer le PanId. Cette 
info (Forcer le PanId) vient de m2q et pour moi c'est une fausse info.


Le 02/08/2019 à 13:45, Pipiche a écrit :

**Comment by pipiche38** [comment]
drop!
