### ISSUE TITLE
Left and right button support tradfri remote for colour temp

### ISSUE THREAD

**Issue by Gemies** [sasu-drooz/Domoticz-Zigate#347]
Your first place to get support is via the Forums.

    English channel : https://www.domoticz.com/forum/viewforum.php?f=68
    French Channel : https://easydomoticz.com/forum/viewforum.php?f=28&sid=a8633a9d8cb2acccb32872543b50fd47

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Plugin (please complete the following information):**
 - OS: [e.g. Linux Fedora 28]
 - Plugin version
 - Plugin branch

**Additional context**

**Comment by Gemies** [comment]
The Zigate can now read all the button actions off the tradfri remote. It would be nice if the paired bulbs would also change colour temp when pressing left and right button of the tradfri remote.
[remote colour temp log.txt](https://github.com/sasu-drooz/Domoticz-Zigate/files/2866851/remote.colour.temp.log.txt)

**Comment by pipiche38** [comment]
@Gemies it would indeed be great. For that you need to program it by retrieving the event, and then triggering changes to the Bulb.
Basically this is how the Tradfri Hub is reacting by using scene which are programmed there

So every one can do what every he wants

**Comment by pipiche38** [comment]
Let's reopen this issue. 

When capturing the remote event, we can consider sending a color change  to a device or a group.

**Comment by pipiche38** [comment]
First version is delivered on beta branch : 701bf9a

As White Color schema, it works pretty well.
For Color one, this is not fancy and not usfull, I'm thinking to go with a series of preset defined color that left/right could scroll

**Comment by pipiche38** [comment]
Final Version : ee03c0e..c02f09b

You need to add the Remote (which have been paired before with a Bulb) to the Group where you have already added also the Zigate.
