### ISSUE TITLE
Compatibilité Pluzzy 

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#429]
When Pluzzy firmware will be available , make sure that the Pluzzy devices are correctly managed

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/30

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate_HA1.2

**Comment by pipiche38** [comment]
For those whom want to test Pluzzy please use the referenced Firmware, but make sure to switch to beta version of the plugin for now.
If the integration work (which I don't think) becomes important I might create a dedicated branch for the work

**Comment by cleminfo** [comment]
Il y a un tuto pour passer sur ce firmware ?

**Comment by pipiche38** [comment]
I beleive that is the same as the standard Zigate firmware

**Comment by cleminfo** [comment]
C'est pas très clair, quel est le fichier bin a utilisé pour la mise à jour du firmware ?

**Comment by pipiche38** [comment]
Le firmware est disponible ici: https://github.com/fairecasoimeme/ZiGate_HA1.2/releases
En fait Akila a fait un repo dédié à ce firmware (je pense pour éviter toutes confusions)

**Comment by pipiche38** [comment]
Open branch 'pluzzy' to work on it

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate_HA1.2/issues/2

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate_HA1.2/issues/1

**Comment by pipiche38** [comment]
Une première version sur la branche pluzzy ( 77ec89865600bfa7c8d29f6ce0cf89dbe5ec2da0 ) fonctionne avec le capteur de Temp+Humi
Par contre le firmware n'est pas aligné avec le firmware classique de la Zigate et donc je patch le Payload

A first version is working on pluzzy branch ( 77ec89865600bfa7c8d29f6ce0cf89dbe5ec2da0 ). it works with Temp+Humi sensor
However the current zigate-pluzzy-firmware is not aligned with the classical zigate and I have to patch the payload in order to re-order some bytes (quiet nasty)

**Comment by pipiche38** [comment]
Documentation on Temp+Humi sensor: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwjuiY3ixb7jAhUaA2MBHc-hAy0QFjAAegQIARAC&url=http%3A%2F%2Fwww.netvox.com.tw%2Fusermanual%2FZ716A_UserManual_ENG_WEB.pdf&usg=AOvVaw2qaOK1dstzVKoVpEbFXU5c

**Comment by pipiche38** [comment]
<img width="821" alt="Screenshot 2019-07-18 at 17 42 46" src="https://user-images.githubusercontent.com/8291674/61471710-82190b00-a983-11e9-880b-df5d926060ce.png">

**Comment by pipiche38** [comment]
Merged on beta eab8091
Temp+Humi sensor works.
