### ISSUE TITLE
Dimmer Iluminize 511.201

### ISSUE THREAD

**Issue by rom289** [sasu-drooz/Domoticz-Zigate#450]
Bonjour,

La prise en charge du micro-module dimmer Iluminize 511.201 est-elle prévue ? Merci

https://zigate.fr/le-materiel-compatible-zigate/compatible/dimmer511201encastrable/

**Comment by pipiche38** [comment]
There is no reason why it shouldn't work.
Please use the forum next time (Thanks)
https://easydomoticz.com/forum/viewforum.php?f=28&sid=6347c44d2fad193f9313b1e754a444c9
