### ISSUE TITLE
Comment récupérer l'état d'une ampoule zigbee (Osram, Hue, ...)

### ISSUE THREAD

**Issue by cbakira** [sasu-drooz/Domoticz-Zigate#463]
Bonjour,

Je voudrais savoir s'il y a moyen de récupérer l'état d'un périphérique déconnecté.

Par exemple, 1 ampoule compatible Zigbee (Osram, Hue, INNR, ...) alimenté par un interrupteur mural classique (non connecté). Une fois alimenté électriquement, sont état est ON dans domoticz, il est possible de la passer ON/OFF via domoticz. Par contre si par malheur, l'ampoule est éteinte dans l'état ON (Domoticz) par l'interrupteur mural classic. Celle-ci reste ON dans domoticz.
Est-ce qu'il y a un moyen récupérer l'état de déconnexion de la communication Zigbee entre l'ampoule et domoticz afin de passer la l'ampoule a OFF dans domoticz.

Il est possible que cette demande ai déjà été faite mais je n'ai pas trouvé d'information.

Par avance merci pour votre aide 

Alex

Domoticz 4.10714
Zigate 3.1a
Plugin Stable 4.3.6

**Comment by pipiche38** [comment]
Bonjour,

Merci d'utiliser les forums Francophone ou Anglophone pour ce type de question. 
    English channel : https://www.domoticz.com/forum/viewforum.php?f=68
    French Channel : https://easydomoticz.com/forum/viewforum.php?f=28&sid=a8633a9d8cb2acccb32872543b50fd47

je vous recommande notamment la lecture de ce poste: https://easydomoticz.com/forum/viewtopic.php?f=28&t=8251&start=80 qui je pense répond à votre question
