### ISSUE TITLE
Xiaomi Zigbee bulb reconize as batterie device

### ISSUE THREAD

**Issue by deennoo** [sasu-drooz/Domoticz-Zigate#470]
lumi.light.aqcn02 is a 230v bulb.

on zigate dashbord this device is reconnize as a batterie device

**Comment by pipiche38** [comment]
Could you please provide the log ?

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Please provide the device list-xx.txt as well 

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Is that a new paired device ? 
If yes, could you kindly provide the logs during pairing and the DeviceList-xx.txt,
If not, please provide the DeviceList-xx.txt

**Comment by pipiche38** [comment]
Problem duplicated. Looks like Aqara is providing an information of battery level

**Comment by pipiche38** [comment]
Problem is fixed.
