### ISSUE TITLE
Xiamo button, received click but not updated in domoticz

### ISSUE THREAD

**Issue by handfreezer** [sasu-drooz/Domoticz-Zigate#49]
Hello,

   I registered a Xiamo button (it appears as a 1/2/3/4 clicks switch), and When I do a "1 click" press on the button, if I leave a previous state diffrent from one click, the status is updated, but from this point, every one click does not update last change and do not generate event in domoticz, but zigate plugins did received the event from the button.

Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     01 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     12 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     1e .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     30 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     0
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 1e .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     11 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     16 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     11 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     03 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     12 02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 1e .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     31 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     1
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     11 02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 16 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     10 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 11 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     ..
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     02 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 1 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate)     11 .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..     .
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Received 2 bytes of data:
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateDecode - decodind data : 018102120210021e30021ed6f4021102100216021002100210100210021102108703
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - decoded data : 018102000e300ed6f4010006000000100001008703
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - Message Type : 8102, Data : 0ed6f401000600000010000100, RSSI : 87, Length : 000e, Checksum : 30
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - MsgType 8102 - reception data : 018102000e300ed6f4010006000000100001008703 ClusterID : 0006 Attribut ID : 0000 Src Addr : d6f4 Scr Ep: 01
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) MajDomoDevice - Device ID : d6f4 - Device EP : 01 - Type : Switch - Value : 00
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) onMessage - effacement de la trame suite a une erreur de decodage : 018102120210021e30021ed6f4021102100216021002100210100210021102108703
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) Calling message handler 'onMessage'.
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateDecode - decodind data : 018102120210021e31021ed6f4021102100216021002100210100210021102118703
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - decoded data : 018102000e310ed6f4010006000000100001018703
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - Message Type : 8102, Data : 0ed6f401000600000010000101, RSSI : 87, Length : 000e, Checksum : 31
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - MsgType 8102 - reception data : 018102000e310ed6f4010006000000100001018703 ClusterID : 0006 Attribut ID : 0000 Src Addr : d6f4 Scr Ep: 01
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) MajDomoDevice - Device ID : d6f4 - Device EP : 01 - Type : Switch - Value : 01
Jan 10 21:37:48 srvcenter01 domoticz: (zigate) ZigateRead - MsgType 8102 - reception General: On/Off : 01
Jan 10 21:37:50 srvcenter01 domoticz: (zigate) Calling message handler 'onHeartbeat'.

**Comment by zaraki673** [comment]
ok i see, same problem in new version :(

will fix this soon
