### ISSUE TITLE
Not all widgets are created

### ISSUE THREAD

**Issue by blooesky** [sasu-drooz/Domoticz-Zigate#490]
Hi, I paired with zigate an xiaomi plug but in domoticz it was created only 2 widgets, switch and voltage. Two widgets are missing: live electricity usage and general electricity counter. 
After I deleted the device from domoticz and I tried again and is the same result. 

I using domoticz beta, zigate firmware 3.1c and plugin beta 4.8.002

**Comment by pipiche38** [comment]
Please use the forum 

Envoyé de mon iPhone

**Comment by pipiche38** [comment]
Please use the domoticz zigbee forum or the french domoticz zigate forum to post your problem. If qualified a GitHub issue might be open

**Comment by blooesky** [comment]
Ok,.

Thx
