### ISSUE TITLE
onStart failed 'ValueError':'invalid literal for int() with base 10

### ISSUE THREAD

**Issue by rbrouwer** [sasu-drooz/Domoticz-Zigate#492]
With the latest version of Domoticz version numbering has changed, causing this plug-in to fail. It will not be able to load, because it fails to parse the version numbering.

The error in the logs:
onStart failed 'ValueError':'invalid literal for int() with base 10

Populating the variable "self.DomoticzMinor" is the issue and I personally temporary hard-coded it to something > 10355, but I can guess something better is needed!

**Comment by pipiche38** [comment]
fix on b275526
