### ISSUE TITLE
Loosing the color wheel menu for GLEDopto device GL-C-001MC USB Mini LED controller RGB+CCT after 2020.1 update 

### ISSUE THREAD

**Issue by gotchai** [sasu-drooz/Domoticz-Zigate#494]
**Describe the bug**
I have made a clean install of domoticz 2020.1 on raspbian, and of the zigate plugin from github.
After pairing a Gledopto RGB+CCT device with the zigate plugin, the device is correctly displayed in the domoticz dashboard. 
But I loose the ability to choose color on the device, there are only on/off switch and the level of light available (see capture) while this device is RGB + CCT.
The only way to change the color is to send a command via the zigate webserver which is not convenient.

**To Reproduce**
1. After installing zigate plugin on domoticz
2. Allow new device 
3. Pair the Geledopto device
4. Add the new device
5. Now the device is visible on the dashboard
6. Unable to have access to the color menu
7

**Expected behavior**
There is no color wheel displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/58481653/78453131-52c83c80-767f-11ea-969e-47eb167d1325.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser : FF 74

**Plugin (please complete the following information):**
Zigate Plugin version: 4.7.008
Firmware version: 031c

**Comment by pipiche38** [comment]
Should work with beta version of the plugin.

Could you be cross-check in the Forum and especially that one :

https://www.domoticz.com/forum/viewtopic.php?f=68&t=31356

If still it is not solev via this, please report it by following those: https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Dealing-with-none-certified-device.md
