### ISSUE TITLE
more a suggestion than an issue

### ISSUE THREAD

**Issue by handfreezer** [sasu-drooz/Domoticz-Zigate#63]
Hello,

   I just saw this project, and I don't know if it could help to manage the Zigate : the idea if for you to focus on plugin code with domoticz, no?

https://github.com/elric91/ZiGate

Best regards.

**Comment by zaraki673** [comment]
i see thank's, but same things for me,

need to translate zigate or this module
 ;)

**Comment by handfreezer** [comment]
You're the boss.
