### ISSUE TITLE
Erreur à l'initialisation de la Zigate

### ISSUE THREAD

**Issue by Mat2Vence** [sasu-drooz/Domoticz-Zigate#68]
Lors de l'activation de la Zigate, le message d'erreur suivant apparait dans le log domoticz : 
(ZIGATE) 'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'

**Comment by zaraki673** [comment]
il faut etre sur le canal beta, le plugin ne fonctionne pas en version stable
;)
