### ISSUE TITLE
Support Samotech Zigbee Interrupteurs et variateurs 

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#724]
Based on the donation received I have ordered 1 simple item
Tuya ZigBee 3.0 Smart Light Switch Module

https://www.moeshouse.com/search?type=product%2Carticle%2Cpage&q=Tuya+ZigBee+3.0+Smart+Light+Switch+Module

**Comment by pipiche38** [comment]
Wiating for delivery

**Comment by jfcjfc** [comment]
pipiche38 : As dry contact, L1 and L-out are the relay,  L and N are the 220v power  ??? Test after the holidays, it's the heating, I want to be there.

**Comment by pipiche38** [comment]
Device received.
Tuya Brand
Model Name TS0121 (as a Smart Plug from the same brand)
There are Cluster 0b04 and 0702 but seems not to be used !

Par contre grosse galère pour faire le reset ! Pas moyen

**Comment by samea-innovation-it-team** [comment]
Bonjour / Hello. I have the same module here. Can't réinitialize it too. Following the user manual, on/off sequence 5 times. I tried short (1s or less) and long (5s) sequences. Device doesn't beep as the first power on, and not detected.
Did you managed to reinitialize the network and how ?
Thanks, Pascal

**Comment by pipiche38** [comment]
@pdelrot-samea 

> Bonjour / Hello. I have the same module here. Can't réinitialize it too. Following the user manual, on/off sequence 5 times. I tried short (1s or less) and long (5s) sequences. Device doesn't beep as the first power on, and not detected.
> Did you managed to reinitialize the network and how ?
> Thanks, Pascal

Please use the forum to get support, not the github which is dedicated to Bug !
Here is the link I get from the vendor: https://we.tl/t-uUgiOAObOo (link is valid for a week only)
