### ISSUE TITLE
Is it possible support 1 000 000 baud speed?

### ISSUE THREAD

**Issue by itProfi** [sasu-drooz/Domoticz-Zigate#741]
Good day! Is it possible to integrate 1 000 000 baud rate to serial speed to support zigate firmware with 1000000 baud rate?,

**Comment by pipiche38** [comment]
Why ? The ZiGate firmware are only on 115200 which is more than enought.

**Comment by itProfi** [comment]
Not only 115200, and user use 1000000 baud rate also..
![image](https://user-images.githubusercontent.com/6728198/98978837-90e9e080-252b-11eb-9d25-b110a1e3622a.png)

**Comment by pipiche38** [comment]
Yes, I know , but why are you building the firmware and not using the standard one ?
The recommendation is to use 115200 and going to  1M is not providing any benefits

@fairecasoimeme

**Comment by pipiche38** [comment]
If you really want to use 100000 Bauds and you are able to build your own firmware with such speed. I suggest that you change the BAUDS parameter in the source code ( Classes/Transport.py )
