### ISSUE TITLE
Philips Hue remote control button issues

### ISSUE THREAD

**Issue by dpocock** [sasu-drooz/Domoticz-Zigate#763]
There are still issues with this remote / dimmer, I described it in the Domoticz forum and I saw previous discussion here in #335 

https://www.domoticz.com/forum/viewtopic.php?f=11&t=34904

domoticz                        4.11020-2~bpo9+1
domoticz-zigate-plugin          4.4.9~beta1-2~bpo9+1

Copied here from forum:

I went to the Scenes tab and created a Group

I added a bulb to the group

Then I clicked to Add Device

I pressed the button on the Philips remote and it was added in the group

Pressing the button with the big asterisk (*) symbol turns on the group (bulb), log entry like this:

domoticz[548]: (zigate0) UpdateDevice - (zigate0 - RWL021_LvlControl-0017xxxx-02) 1:48
domoticz[548]: Activating Scene/Group: [g0]
domoticz[548]: Activating Scene/Group Device: sitting room ceiling (On)
domoticz[548]: (zigate0) UpdateDevice - (sitting room ceiling) 1:67

Pressing the button with the little asterisk also turns on the group but I found that I have to press it more than once

Pressing other buttons has no impact on the group.

Can anybody provide more details about how to setup the Philips Hue dimmer buttons or it is not fully supported?

**Comment by pipiche38** [comment]
please do you the forum for that until there is a clearly describe bug in the plugin.The Philips Use remote is supported. So suggest that you report the the Zigbee forum.
