### ISSUE TITLE
on_message Error Code: TRANS-onMESS-03

### ISSUE THREAD

**Issue by dpocock** [sasu-drooz/Domoticz-Zigate#769]
I'm using beta 4.12.087 and I tried both firmware 3.1c and 3.1d

I use the Hardware settings page to try and request an initialization of the Zigate.

This error appears in the logs:

```
Installer Version Number: 031c
Status: (zigate0) Erase Zigate PDM
Error: (zigate0) on_message Error Code: TRANS-onMESS-03
```

**Comment by pipiche38** [comment]
This is an expected issue which is due to the Erase PDM it self
