### ISSUE TITLE
Standalone version of this plugin!

### ISSUE THREAD

**Issue by perhusaas** [sasu-drooz/Domoticz-Zigate#790]
This wonderful plugin could have even more users if you made it accessible to non-domoticz users? 

From the outside it seems to be only a minor change to make this run indepenently, as it has its own GUI? 

I understand if you'd like to keep it in the domoticz community, just thought i'd ask. (which should be acceptable in the Open Source World!) :)

**Comment by pipiche38** [comment]
Thanks for the feedback. The plugin in its recent version is more and more decoupled from Domoticz. However, Domoticz is the User Interface used to report the status of devices and to take commands/actions . That part is not in the plugin.

Any suggestions more than welcome

**Comment by perhusaas** [comment]
I think theres only 4 things that's needed:

- Run the plugin as a service
- web address to json data (like from domo: http://<domo ip:port>/json.htm?type=devices&filter=all&used=true&order=Name) for device creation
- place to input variables IP and Port for sending device changes by UDP (.conf file or preferably in web GUI)
- Some way to send change commands to the plugin. (domo: http://<domo ip:port>/json.htm?type=command&param=...)

I would think there is some equivalent functions for the latter 3 in the code already mabye? 
The json data would offcourse be simpler from that of domoticz, but some sort of device type data next to the sensor data would be nessecary.

I have no idea about the amount of changes needed on the plugin side, but thanks for entertaining the idea. :)

**Comment by perhusaas** [comment]
I've been playing a lot with docker and MQTT lately, (and wass thrilled to find a dockerfile in your manual!) and it seems MQTT would be an even better universal interface than HTTP commands w. json?

**Comment by Smanar** [comment]
> MQTT would be an even better universal interface than HTTP commands w. json

I can't say for command, but not for protocol, http is native, you can use it even with a 20 years old computer out of the box, not for MQTT.

**Comment by perhusaas** [comment]
Fair point, but its the instant bi-directional updates that requires more overhead with HTTP, as i have understood it? 
Its either done with polling at intervals (lots of unnecessary traffic) or setting both sides up with some communication code. Thats a lot more bridge specific code than MQTT (or web sockets?) subscriptions..

**Comment by Smanar** [comment]
>Its either done with polling at intervals (lots of unnecessary traffic)

Yeah realy bad idea

> Thats a lot more bridge specific code than MQTT (or web sockets?) subscriptions

I can't be sure, websocket is realy something basic too, and don't need additionnal server.

Another way some devs are looking on my side is Server Sent Events (SSE) for exemple in php https://kevinchoppin.dev/blog/server-sent-events-in-php (unidirectionnal protocol). Don't ask me how it work ^^, it s just an exemple found on an issue.

TCP/IP is realy good protocol, with lot of possibilities, MQTT have lot of advantages but we are realy far away the situation for the one MQTT was created, and have the more advantages.
