### ISSUE TITLE
Osram Smart+ E27

### ISSUE THREAD

**Issue by Th1h4ck** [sasu-drooz/Domoticz-Zigate#792]
Bonjour, je viens d'acquérir une ampoule Osram Smart+ E27, et le plugin ne la reconnait apparemment pas :

* Product Name : Osram Smart+ Classic E27 Dimmable
* Brand : Osram
* URL Amazon : https://www.amazon.fr/gp/product/B074KJ72MP
* URL Osram : https://www.benelux.osram-lamps.com/fr/professionnels/produits/smart-home/produits-intelligents-avec-la-technologie-zigbee/lampes-smart-home/lampes-classiques-avec-technologie-zigbee/smart-classic-dimmable/index.jsp
* Erreur au moment de l'inclusion, le périphérique n'apparait pas dans la liste des équipements (RAW)

Voici le fichier json de l'erreur.
[errors.txt](https://github.com/pipiche38/Domoticz-Zigate/files/5976045/errors.txt)

Merci, cette ampoule est intéressante car vraiment pas cher .

Bonne journée
T1h4ck

**Comment by pipiche38** [comment]
Please use the French Domoticz forum 

The bulb should be running without any issue
the errors you are providing is not showing anything wrong and has nothing to do with the pairing of the bulb.

please use the forum to get the issue fixed, or qualified before submission to the GitHub
https://easydomoticz.com/forum/viewforum.php?f=28
