### ISSUE TITLE
Do not use f1,f2,F3 EndPoint for fake endpoint

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#848]
F1, f2, F3 End Point seems to be reserved and cannot be used or at least we must avoid to do 0043

**Comment by SylvainPer** [comment]
Endpoints above 240 (f0) are all reserved.

There are two special endpoints: 0 and 255. Endpoint 0 is used for the configuration and management of the entire Zigbee devide. Through this endpoint, the application can communicate with other layers of the Zigbee stack to initialize and configure them. Attached to endpoint 0 is the Zigbee device object (ZDO). Endpoint 255 is used to broadcast to all endpoints, while endpoints 241-254 are reserved for special functions.

Refer Chapter 4 "Application Framework" of the Software Reference Manual for ZigBee attached.


[BSSRMZB2007.pdf](https://github.com/pipiche38/Domoticz-Zigate/files/7292531/BSSRMZB2007.pdf)
