### ISSUE TITLE
[zigpy integration] - handle_message() / request() / mrequest()

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#890]
handle_message() should return the source nwkid. as of today get_device() is returning none.
Do we have to implement a device structure (or map it to the existing plugin ListOfDevices) ? If so which would make sense, we need to see how to interface .

similar issue with request and mrequest

**Comment by badzz** [comment]
https://github.com/pipiche38/Domoticz-Zigate/pull/894

**Comment by pipiche38** [comment]
thanks
