### ISSUE TITLE
[zigpy-integration] - call_handler do not report LQI 

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#891]
call_handler is filtering the LQI coming from the message receive. In fact it seems to be store in the zigpy database that we won't use. 
Can we store the LQI into the plugin (ListOfDevices) database ?

cd: device.radio_details(lqi, rssi)

**Comment by badzz** [comment]
handle_message should be called with a device that include the lqi now
device.lqi should work ? 
#894

**Comment by pipiche38** [comment]
thanks
