### ISSUE TITLE
[zigpy-integration] - what is the purpose of the sequence parameter

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#892]
In request()/mrequest() sequence is an expected parameter which is not used in the raw_aps_data_request(), for ZNP it seems that the sequence called TSN is expected, does that mean that we have to have a dedicated counter/sqn ?

Is that a simple counter, do we get it back in the call_handler ?

**Comment by badzz** [comment]
interesting subject. The NXP function does not allow the manipulation of the ZPS sequence number.
It is the NXP stack that assigns them and keep the counter.  check ZPS_eAplAfApsdeDataReq for reference in NXP doc
Hence when using zigate, no sequence number needed to be send. 
However to keep track of ACK, the NXP stack and zigate firmware sends back the SQN assigned

**Comment by pipiche38** [comment]
get_sequence() is provided by zigpy.application so everything good.
