### ISSUE TITLE
[zigpy-integration] - APS SQN management (at plugin level)

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#897]
With zigpy we don't have to managed APS sqn , but via the raw 0x0530 (the sqn is embeeded into the RAW_APS payload). These is the ZCL/ZDP sqn we will get back when receiving the answer from the device.

**Comment by pipiche38** [comment]
https://github.com/badzz/zigpy-zigate/commit/6f22a49ad17635b1c1fec36826bf62a6afd5fbca

**Comment by badzz** [comment]
delivered .. there might some perf issues but let's make a separate bug for it ?

**Comment by pipiche38** [comment]
@badz that one is still open, tI need to fix the use of the ZCL SQN instead of the i_sqn . like for configure reporting and bind responses.

**Comment by pipiche38** [comment]
Issue remains on Zigpy-ZNP as the SQN seems to be overwritten .
https://github.com/pipiche38/Domoticz-Zigate/issues/932

**Comment by badzz** [comment]
rewording the issue to APS SQN would be better ?

**Comment by pipiche38** [comment]
I close that one, as the pending issue is under #932
