### ISSUE TITLE
Cannot find the way to pair Phillips Hue bulbs

### ISSUE THREAD

**Issue by gelitoam** [sasu-drooz/Domoticz-Zigate#90]
Hello.

I am trying to use some Phillips Hue bulbs with Zigate and your plugin with no success. Would you kindly tell me if it is possible, and if so the steps to get it done?

Best regards.

**Comment by pipiche38** [comment]
Did you try ? : and sorry that is in French

- https://faire-ca-soi-meme.fr/zigate/2017/11/27/maitrisez-vos-ampoules-zigbee/
- https://zigate.fr/837-2/

**Comment by pipiche38** [comment]
@gelitoam , any news ? Did you succeed ?

**Comment by pipiche38** [comment]
Close this . In case you still have the issue with the recent version published, let us know .
