### ISSUE TITLE
Domoticz-Zigate plugin doesn't work on Beta V3.9639 Build Hash: 786b9638 Build Date: 2018-06-14 16:44:52

### ISSUE THREAD

**Issue by davidllerena** [sasu-drooz/Domoticz-Zigate#92]
Hello,

after update Domoticz to beta V3.9639
Build Hash: 786b9638
Build Date: 2018-06-14 16:44:52
Domoticz-Zigate plugin doesn't work. I've tried to uninstall and install again but no changes. Doesn't appear in the list of hardware type.

Regards

**Comment by thiklop** [comment]
The plugin works with beta v3.9651.

**Comment by thiklop** [comment]
Did you solve your problem with the plugin ?

**Comment by pipiche38** [comment]
Beta V3 is an old one.
Please upgrade to V4 and to the latest version of the Plugin 2.4.0

I'm closing the issue for now!
