### ISSUE TITLE
[zigpy-integration] - get_device() and controller infos

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#926]
Let's check if we can get some extra controller information like version ... via the get_device() or simply 

- ZiGateDevice for Zigate
- ZNPCoordinator for ZNP

For both classes, we have model and version

**Comment by pipiche38** [comment]
@badz what do you think ?

**Comment by badzz** [comment]
it should work if you get AppZnp.get_device(nwk=0x000).mode() or AppZigate(nwk=0x0000).mode().
However for zigate , I might need to check a lot of logic in zigate.

**Comment by badzz** [comment]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/pull/976

**Comment by pipiche38** [comment]
Thanks what would I do without you !
