### ISSUE TITLE
[zigpy-integration] - ZDP command over ZNP seems to overwrite the Sequence number

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#932]
When doing a bind, it looks like the ZNP stack doesn't take the sequence number given when calling request() and instead take a self generated one. The result is when bind_reponse is coming back, the Sqn is unknown from out side !

**Comment by pipiche38** [comment]
@badzz

**Comment by badzz** [comment]
you have a log of this ? it seems that zdo function do not use the SQN/TSN . hence it just sends back the same sqn that you put in request.

**Comment by pipiche38** [comment]
[SQN-log.log](https://github.com/pipiche38/Domoticz-Zigate/files/7777261/SQN-log.log)

**Comment by pipiche38** [comment]
Fixed with the new ZDO implementation from znp
