### ISSUE TITLE
[zigpy-integration] - znp Nwk_link_quality_request

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#938]
we have an issue that we are not able to send a LQI request to 0x0000. As this is part of the Topology report, how can we get access and send command to controller ?

**Comment by zigbeefordomoticz** [comment]
this is link to the handle_message() filtering out what is coming from 0x0000

https://github.com/zigbeefordomoticz/Domoticz-Zigbee/pull/947/commits/e0e03e73d93c93c0eae5d065adef2190fc855169
