### ISSUE TITLE
[zigpy-integration– ZNP Endpoints

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#940]
in order to align ZNP controller on the Zigate, we must make sure that ZNP is listening on the same Endpoint as Zigate

EndPoint 0x00 (0) --> ZDP
EndPoint 0x01  (1) --> ZCL
EndPoint 0x0b (11) --> Wiser Schneider
EndPoint 0x0a  (10) --> ORVIBO
EndPoint 0x6E (110)   --> TERNCY
EndPoint 0x15 (21)   ---> KONKE
EndPoint 0x08 (8) --> LIVOLO
EndPoint 0x03 (3) --> New Wiser Schneider

https://github.com/zigpy/zigpy/discussions/865#discussioncomment-1879846

**Comment by pipiche38** [comment]
For Wiser Thermostat, we will have register the endPoint ( https://github.com/zigpy/zigpy/discussions/865#discussioncomment-1879846 )

Same issue as on ZiGate EndPoint receiving command needs to be registered in order to capture the event!

Need to see how to do that in the integration side

**Comment by pipiche38** [comment]
@badzz to be check if we can use _register_endpoints() from AppZNP during startup and hving the possibility to add additional Endpoint on top of the 0x00, 0x01 and 0x02

**Comment by badzz** [comment]
Yep seen that..  I will dig into it . Thx

**Comment by badzz** [comment]
https://github.com/zigbeefordomoticz/Domoticz-Zigbee/pull/959
