### ISSUE TITLE
Apparition de devices inconnus ...

### ISSUE THREAD

**Issue by pipiche38** [sasu-drooz/Domoticz-Zigate#95]
Comme ci-après dans le screenshot, j'ai des devices Zigate qui apparaissent au fil du temps !!!!

<img width="1324" alt="screen shot 2018-07-04 at 11 00 03" src="https://user-images.githubusercontent.com/8291674/42267514-7cbd2d4c-7f79-11e8-9f25-cd4221cf19ee.png">

**Comment by thiklop** [comment]
C'est marrant, on dirait que ton device est en mode association continuellement. Le device d'origine continue à fonctionner ou non après ces ajouts ?

**Comment by pipiche38** [comment]
A priori ces devices sont sur la Zigate, car j'ai Ouvert l'appairage et ils sont revenus.
Peut-etre que le problème est sur la Zigate elle meme.

Il faut que je la branche sur un PC avec Windows, pour supprimer ces devices
